### ISSUE TITLE
ETMのクライオスタット付近への出張ラックがない

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#10]
https://github.com/gw-analysis/detector-characterization/issues/96#issue-323460215 から。

ETMは最寄りのラックとクライオスタットの距離が遠い。
そのため、DC電源も遠く、配線も面倒で、しかも回路の置き場所がないので、クライオスタット周りに環境モニターを置くのがちょっと大変。
なので、クライオスタット周りに、小さい出張ラックを置けないか。
出張ラックには、Dsub3ピン電源(DC18 V)と、Dsub9ピンを何本か(ADCに接続。必要数はセンサー類の設置数による。これは別issueで考える。)を、大本のラックから持ってくる。
その上で、出張ラックに、18 V->15 VレギュレータやBNC-Dusbコンバータ、アンプ・ホワイトニングフィルタ類を置けば環境モニターが設置しやすい。
確か、BS周りにそういうのがあった気がする。(これと同じ使い方をしているかは不明。)

**Comment by yokozawa1985** [comment]
宮川さんに相談して、10個が12月末に届く予定です。
PR系やBS,SR系のすぐそばに置いてあるミニラックです。
Dsub 3pin電源はどのように配線するか、分配するかは要相談。

**Comment by yokozawa1985** [comment]
本日届きました。必要な方はおっしゃってください。closeします。
