### ISSUE TITLE
PXのおんどとりの写真撮影

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#102]
**改善案**
どのように改善してほしいか書いてください。
　
#82 でPXのおんどとりの撮影を残してcloseしたため、新たにissueを立ち上げ
Miyoさんが写真を撮って横澤にメールを送ったら完了

- [x] PXのおんどとりの写真をとる

- [x] 画像を横澤に送る

**Comment by yokozawa1985** [comment]
すみません、画像を見た覚えがありません、、、もう一度送っていただけますでしょうか？

**Comment by yokozawa1985** [comment]
三代さんに許可を取って取ってくる。

**Comment by MiyoKouseki** [comment]
押野さんと探してみたが、結局FIELDの音頭取りは見つからなかった。
