### ISSUE TITLE
溜まっているIssueの整理

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#103]
**問題について** 何が問題か書いてください
とあるIssueのせいで他のIssueが止まっている。たとえばチャンネル名の変更がそれ。これはもう1ヶ月以上前から続いていて、もう少しでCloseできる。

しかし、その他の優先順位が見えないIssueが散見される。優先順位をつけてIssueを明確に処理したい。
今やらなくていいIssueが溜まっているのを見ると精神衛生上よくない。少なくとも自分は。

**正しい状態** どうなっているべきか書いてください
少なくとも、なんでそのOpenされているかわからないIssueがあるので、それを明確にする。
例えば、別のIssueからの派生なら、その依存を明記する。
もし本当に新しいなら、ちゃんと背景を書く。
もし解決方法がわかるならTodoリストまで落とし込む。

ちなみに、1ヶ月経ってもCloseしないIssueは、早くCloseしたい。
そもそも粒度が大きすぎた、とか
Openした本人しかそのIssueを理解していなくてしかも本人が放置している、とか

**Comment by yokozawa1985** [comment]
全員一度プロジェクトを見直して、自分のissueを見返しましょう。

**Comment by yokozawa1985** [comment]
一度僕の方で整理します。closeで。
