### ISSUE TITLE
チャンネル名変更のための準備

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#104]
#77 でもう少ししたら名前がきまりそうなので、変更するための準備が必要。

確認しながら進める。

**Comment by MiyoKouseki** [comment]
現在モデルに登録されている名前全部
>less /opt/rtcds/kamioka/k1/chans/daq/K1PEM* | grep -e "^\[K1:PEM.*_DQ" | cut -d"[" -f2 | cut -d"]" -f1 | sort > old_pemchname.txt

PEM関係のiniファイル
$ ls -la /opt/rtcds/kamioka/k1/chans/daq/K1PEM* | awk '{print $9}'
/opt/rtcds/kamioka/k1/chans/daq/K1PEMBS.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMEX0.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMEX1.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMEY0.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMEY1.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMEY.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMIMC0.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMIOO1.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMIX0.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMIX1.ini
/opt/rtcds/kamioka/k1/chans/daq/K1PEMIY0.ini

**Comment by yokozawa1985** [comment]
チーフサブチーフ、gokagraに投げました。コミッショナーとは直接話して見ます。

**Comment by MiyoKouseki** [comment]
今のPEMのモデル
>$ l /opt/rtcds/userapps/release/pem/k1/models/ | awk '{print $9}' | grep -e ".*.mdl$"
k1pemex0.mdl
k1pemex1.mdl
k1pemex.mdl
k1pemey0.mdl
k1pemey1.mdl
k1pemimc0.mdl
k1pemioo1.mdl
k1pemix0.mdl
k1pemix1.mdl
k1pemiy0.mdl
k1pemmcf.mdl

一つずつ確かめる。
### k1pemex0.mdl

>$ less /opt/rtcds/kamioka/k1/chans/daq/K1PEMEX0.ini | grep -e "^\[K1:PEM.*_DQ\]" | cut -d"[" -f2 | cut -d"]" -f1 | sort
K1:PEM-EX_ACC_TMS_TABLE_OUT_DQ
K1:PEM-EXA_PDA1_DC_IN1_DQ
K1:PEM-EXA_TEST_DC_IN1_DQ
K1:PEM-TMSX_WEATHER_HUMD_OUT_DQ
K1:PEM-TMSX_WEATHER_PRES_OUT_DQ
K1:PEM-TMSX_WEATHER_TEMP_OUT_DQ


### k1pemex.mdl：
対応する.iniファイルが存在しない。なので、このモデルは削除する。

**Comment by MiyoKouseki** [comment]
上記のチャンネルが本当にモデルで作られているか手作業で確認した。
- スプレッドシートのCheckが「OK」なのはその意味。
- 「？？？？？」なのは，モデルのどこにも書かれていなかった謎のチャンネル。
- 「保留」なのは，オンドトリはリアルタイムモデルではないので確認していないという意味。

「OK」がついたのを赤く塗りつぶした。
スプレッドシートは以下に再掲。
https://docs.google.com/spreadsheets/d/1EIZCBXdf2wDwFqenr5S71jXwEpNRyjVgdeh0v0K3mBU/edit?usp=sharing

**Comment by yokozawa1985** [comment]
15 DOFをYにしたのは？
21 PDA1はPEM範囲外のため、PEMというチャンネル名をつけていても変えたくない、コミッショニングチーム管轄。
あとは横澤管轄のものはOKです。

**Comment by MiyoKouseki** [comment]
15 は最初からYでした。Zに変えました。
21 は変更対象外として「保留」にしました。

**Comment by MiyoKouseki** [comment]
### EX0
![image](https://user-images.githubusercontent.com/24282734/51645698-cae59d80-1fb8-11e9-8aa2-89fa0f5d44ca.png)

### EX1
![image](https://user-images.githubusercontent.com/24282734/51645681-be614500-1fb8-11e9-9bca-ebc0ead2d796.png)


### EY0
![image](https://user-images.githubusercontent.com/24282734/51645669-b1445600-1fb8-11e9-83df-00a50b8c13dc.png)

### EY1
![image](https://user-images.githubusercontent.com/24282734/51645654-a4276700-1fb8-11e9-81a2-33600772fa65.png)

### IMC0
![image](https://user-images.githubusercontent.com/24282734/51645633-92de5a80-1fb8-11e9-9ea7-23095ed4007c.png)


### IOO1
![image](https://user-images.githubusercontent.com/24282734/51645618-81954e00-1fb8-11e9-8c53-73dc85975ea1.png)


### IX1
![image](https://user-images.githubusercontent.com/24282734/51645600-6d515100-1fb8-11e9-9312-bbf1581013bd.png)

### IY0
![image](https://user-images.githubusercontent.com/24282734/51645584-5ad71780-1fb8-11e9-9fff-11eafed119e2.png)

**Comment by yokozawa1985** [comment]
IX0
1. MIC_BS_BOOTH_BS_Y
先ほどご指摘の通り
MIC_BS_BOOTH_BS_Z
へ

2. MIC_OMC_TABLE_AS_Z
ADC0_20の方を
ACC_OMC_TABLE_AS_Z
へ

3. 
ADC0_0 - ADC0_7はIX0のAAに直接Dsubでさせるタイプ
ADC0_21 - ADC0_30はSR3 RackにインストールしたBNC - Dsub converterにinputできるタイプ。
後半の方を
SENSOR_SR_RACK_IX0_(DOF)
にしたい。

**Comment by yokozawa1985** [comment]
月曜日の午前中にGoのつもりで動きましょう。

**Comment by yokozawa1985** [comment]
残りOKです。EY0すみませんでした。

**Comment by MiyoKouseki** [comment]
変更後のチェック
- [ ] sdf の再設定
- [ ]

**Comment by yokozawa1985** [comment]
PSLのcalibration & medmは復旧しました。

**Comment by MiyoKouseki** [comment]
$ python check_chname.py chname.txt 
Bad "SENSOR" name!
  ['BS', 'EYA', 'IMC0', 'EY', 'EXA']
Bad "AREA" name!
  ['ACC', 'SEIS', 'TEST26', 'TEST27', 'TEST20', 'TEST21', 'TEMP', 'TEST25', 'TEST22', 'MIC', 'TEST23', 'PDA1', 'TEST19', 'TEST18', 'TEST24', 'MAG', 'TEST', 'TEST17', 'TEST16']
Bad "LOCATION" name!
  ['WE', 'Z', 'IN1', 'DC', 'FILED', 'NS', 'OUT']
Bad "DOF" name!
  ['IN1', 'BLRMS', 'UD', 'EW', 'NS', 'SENSINF', 'DQ']

**Comment by neouniverse** [comment]
> @neouniverse これはどう消せばいいのでしょうか。

どういう意図で聞かれてるのかちゃんと理解できてないですが
今は無きモデルのiniファイルをどうするか？と言う話ですか？

**Comment by yokozawa1985** [comment]
チャンネル名自身は、変更が完了したので、closeしたい、@MiyoKousekiさんが新しいissueを立ち上げたらcloseする

**Comment by yokozawa1985** [comment]
closeします。
