### ISSUE TITLE
Sus drift monitorのpythonコード改良

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#105]
**改善案**
どのように改善してほしいか書いてください。

Commissioning teamからの要望。
苔山さんがLIGOから輸入したSus drift monitorのpython部の改良を行っていただきたい。
Sitemap->Commissioning->Sus Drift Mon

中野くんからの具体的な要望を聞き次第タスクリスト化する。

**Comment by yokozawa1985** [comment]
/opt/rtcds/userapps/trunk/vis/common/scripts/visdrift/driftmon_update.py
か？

**Comment by MiyoKouseki** [comment]
Site map / commssioning tool / oplev でモニターしているOPLEVをドリフトモンに追加してほしいとのこと。

作業は別issue切って開始します。

**Comment by yokozawa1985** [comment]
Miyoさんに引き渡すことができたのでcloseします。
