### ISSUE TITLE
DriftMonにOplevを追加

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#106]
### 目的　（なぜそれをやりたいのか、）
DriftMonにOplevを追加する。

### ToDo　(どうすればIssueをCloseできるか)
 - [x] 1. DriftMonの中身を理解。
 - [x] 2. Oplev用の画面をつくる。( SUS_DRIFTMON_TM.adl ) 
 - [x] 3. driftmon_update.pyでSTAGEを指定できるようにOptionを追加する。
 - [x] 4. ！ボタンですぐに閾値を個別に設定できるようにする。
 - [x] 完了。Klogに投稿

**Comment by MiyoKouseki** [comment]
まちがって、PRM_BFの閾値を1232344474の10秒間のデータをつかって設定してしまった。。

**Comment by MiyoKouseki** [comment]
TM_DAMPではなくて、OPLEVのOUTMONを見る場合ちょっと面倒。

Commisioning のOPLEV一覧のチャンネル名は、PITだけを抜粋すると、
- K1:VIS-MCO_TM_OPLEV_PIT_OUTMON
- K1:VIS-MCE_TM_OPLEV_PIT_OUTMON
- K1:VIS-MCI_TM_OPLEV_PIT_OUTMON
- K1:VIS-IMMT1_TM_OPLEV_PIT_OUTMON
- K1:VIS-IMMT2_TM_OPLEV_PIT_OUTMON
- K1:VIS-PR2_TM_OPLEV_PIT_DIAGMON !!!
- K1:VIS-PR3_TM_OPLEV_PIT_DIAGMON !!!
- K1:VIS-PRM_TM_OPLEV_PIT_DIAGMON !!!
- K1:VIS-BS_TM_OPLEV_PIT_DIAGMON
- K1:VIS-SR2_TM_OPLEV_PIT_DIAGMON
- K1:VIS-SR3_TM_OPLEV_PIT_DIAGMON
- K1:VIS-SRM_TM_OPLEV_PIT_DIAGMON
- K1:VIS-ITMX_TM_OPLEV_PIT_DIAGMON
- K1:VIS-ETMX_TM_OPLEV_PIT_DIAGMON
- K1:VIS-ITMX_TM_OPLEV_PIT_DIAGMON
- K1:VIS-ETMX_TM_OPLEV_PIT_DIAGMON

**Comment by MiyoKouseki** [comment]
メモ
LOLOとかEPICSの仕様について。
https://epics.anl.gov/EpicsDocumentation/AppDevManuals/RecordRef/Recordref-8.html

**Comment by MiyoKouseki** [comment]
ふと思ったが、間違って誰かが閾値を上書きしたりすると困るので、(1)いつの閾値かわかるようにするか(2)SDF？か何かで管理した方がいいかもしれない。

**Comment by MiyoKouseki** [comment]
昨日とりあえずコミッショニングむけにTMのOplevのDriftMonをつくった。
sitemap -> Commissioning -> SusDriftMon -> TM_Miyo を押せばいけます。

![image](https://user-images.githubusercontent.com/24282734/51723941-5be27480-209e-11e9-93b0-2a7aadad7d8a.png)

**Comment by MiyoKouseki** [comment]
とりあえず、Reviewへ。

**Comment by MiyoKouseki** [comment]
チャンネル毎に、押したらそのチャンネルの時系列がポップアップできたら嬉しい。色が変わっても、いつから、どんな感じに動いてるのか知りたくなるし。

**Comment by yokozawa1985** [comment]
ポップアップ時系列はあったら面白いですね、これまではdataviewerで代用していたことがいろいろ変わるかもですね。
(dataviewerがあるからそんな高いプライオリティではない？)

**Comment by kokeyama** [comment]
ポップアップ時系列めっちゃ便利そう！

**Comment by yokozawa1985** [comment]
ndscope!

**Comment by kokeyama** [comment]
良き

**Comment by yokozawa1985** [comment]
三代さん、ありがとうございました。時系列ポップはとりあえず置いておいて、このissueはcloseします。
