### ISSUE TITLE
地震計の向きを揃える

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#107]
**問題について** 何が問題か書いてください
すべての地震計の向きが揃っていない。
![image](https://user-images.githubusercontent.com/24282734/51719065-647d7f80-208b-11e9-9a64-c86b8f5599d9.png)

**正しい状態** どうなっているべきか書いてください
どうやら、IXVを反転。
マスセンタリング

完了したら、Klogに投稿！

**Comment by yokozawa1985** [comment]
closeします。
