### ISSUE TITLE
PlayBackToolを作る

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#108]
詳細は#106 で。

playback —channel K1:HOGE_HUGE —startgps 1234567890 —endgps 1234567899 

というコマンドを作って、時系列プロットが出るようにする。
ベストはndscopeでインタラクティブな操作だけど、gwpyでとりあえず静的な画像ファイルがポップアップされるようにする。

**Comment by neouniverse** [comment]
この件の進捗どんな感じですか？

k1ctr*には全てndscopeを入れました。
MEDMの右クリックメニュー Execute->ndscopeからポップアップできます。
時刻指定するGUIをlaunchさせて過去データも読めるようにせよと言われれば30分あれば出来る。

ただ色々弄ってみたけどトレンドデータが読めない。。。
なんで1時間超えるような長さのデータをプロットするのはちょっと辛い。
(dataviewerの完全上位互換とは言えない)

あと全てNDS経由なのでDAQされてないEPICSチャンネル(*_OUTMONとかK1:DAQ-*)が扱えない。
(StripToolの完全上位互換とも言えない)

というわけで
リアルタイムDQチャンネル -> ndscope
リアルタイムEPICSチャンネル -> StripTool
過去fullデータ -> ndscope
過去trendデータ -> gwpy
みたいな感じの交通整理してくれるスクリプトを被せるのが良いのかなと。

**Comment by neouniverse** [comment]
ndscopeでtrendが見れることがわかった。
右クリックメニュー Execute->ndscope(playback)を実装
これでclose待ち？

**Comment by neouniverse** [comment]
<img width="840" alt="screenshot_2019-02-19" src="https://user-images.githubusercontent.com/6687389/52997810-eb443300-3464-11e9-998f-b050bd78d707.png">

**Comment by MiyoKouseki** [comment]
いいですねぇ
