### ISSUE TITLE
KAGRAの電源ノイズが評価されていない

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#11]
https://github.com/gw-analysis/detector-characterization/issues/93#issue-316578829 から

KAGRAの電源のクオリティを、安東研のものと比較する

- [ ] 安東研の坪野研電源を測定
- [ ] KAGRAの中央の電源(18 V)を測定
- [ ] KAGRAのYエンドの電源(18 V)を測定
- [ ] KAGRAのXエンドの電源(18 V)を測定

## 関連issue
電源モニターの整備 issue #80

**Comment by yokozawa1985** [comment]
こちらは、霜出さんと話をしている、しているだけで手は動かせていない。
ただ、特にGND問題はKAGRA全体で解決しなくてはいけない問題なので
来年早々には動き始めることを計画している。

**Comment by yokozawa1985** [comment]
特にXendのGNDがひどい可能性あり。

**Comment by yokozawa1985** [comment]
都丸さんと議論することが決定したので少し進むかもしれない。
場合によっては何人かの手をお借りするかもしれない。

**Comment by yokozawa1985** [comment]
霜出さんと議論を進めた。
そもそも電源ノイズを理解する前に、KAGRA共通のグランドを決めないとノイズもクソもないとの話。
基準グランドの設置の検討を開始した。

**Comment by koji-n** [comment]
忘れられているかもしれませんが、一応以下のログのように中央で測ってみたことはあります。
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4837

**Comment by yokozawa1985** [comment]
ありがとうございます。まさにこのようなデータ測定を相談しに行ったら
上記のことを言われてしまったという経緯があります。
長野さんの結果とconsistencyをみるために僕の方でもコネクタを設計してみて測定してみます。

**Comment by yokozawa1985** [comment]
やれていなかったっぽいので一旦closeして段階的にやっていく。
