### ISSUE TITLE
18V, 24V DC電源の評価回路の作成

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#117]
現在、KAGRAでは(やっと)電源の問題に取り組み始めているグループがいくつか出てきた。
特に、
18V電源
24V電源
100V電源
書く回路やラックのGND、ループしちゃったりしていないか、無駄にノイズが乗ってしまっていないか？
などなどまだ目に見えていないだけで、いずれ見えてくることは目に見えている状況である。
一つ一つこなしていって解決する。

手始めに、18V, 24V電源をモニターするための回路作成をする。
回路図や必要な部品はすぐに思いつきそうだが、good first issueということなので
とりあえず伏せておく。
希望者募集。

**Comment by TatsukiWashimi** [comment]
ここのissueに書くか微妙ですが、冷凍機コンプレッサーによる電源ノイズについて忘備録として挙げておきます。
今週のCRYミーティングで、少し議論してこようと思います。

**Comment by yokozawa1985** [comment]
ありがとうございます。今日から冷やし始めるので何かアクションを起こしたかったのですが、それはエンドの課題に回しておきます。。。

**Comment by TatsukiWashimi** [comment]
18V DC電源ノイズモニターについて少し検討してみました。

まず、回路室でAA chassisのピンの間の抵抗値を測ったら、
・ground と 1~4, 6~9 pin の間は10kΩ
・ground と 5番 pin の間は導通
・1~4, 6~9 pin の間は20kΩ
でした。

次に、回路シミュレーションソフトのLTspiceを使って、20kΩ抵抗に適当なコンデンサをはさんで18Vdc + 0.01Vac の電圧をかけてみたところ、10uF くらいのコンデンサを使えば数Hz以上の領域でほぼ一様にAC成分を取り出せるということになりました。

![spice](https://user-images.githubusercontent.com/18456905/55313367-8d166100-54a2-11e9-86ef-42c8ba84e3a7.png)

使うコンデンサは、安全・頑丈・安価なフィルムコンデンサがいいと思います
https://jp.rs-online.com/web/c/passive-components/capacitors/polyester-film-capacitors/?searchTerm=%E3%83%95%E3%82%A3%E3%83%AB%E3%83%A0%E3%82%B3%E3%83%B3%E3%83%87%E3%83%B3%E3%82%B5%E3%83%BC%E3%80%80&applied-dimensions=4292744228,4294597393,4294585371,4294596742,4293711152&sort-by=P_breakPrice1&sort-order=asc

**Comment by TatsukiWashimi** [comment]
Grichモニターだけなら、↓のように各端子にコンデンサを挟むだけで、±18Vと±24VをひとつのADC Dsub-9 でモニターできる。
![20190401_173302318](https://user-images.githubusercontent.com/18456905/55314526-46763600-54a5-11e9-9d9f-0805a02772b3.jpg)

**Comment by TatsukiWashimi** [comment]
GrichだけでなくDC値の安定性も見たければ、60kΩ抵抗を挟んで1/4にすれば10Vに収まる


![20190401_174508597](https://user-images.githubusercontent.com/18456905/55314912-2004ca80-54a6-11e9-9b91-374fec9842b5.jpg)

**Comment by TatsukiWashimi** [comment]
1uFにするとこんな具合で、10Hz以上がflatになる。
1uFのフィルムコンデンサはこの前秋葉原で4個買って手元にある。
grichモニターならこれでよいか
![spice1uF](https://user-images.githubusercontent.com/18456905/55366647-98aa6c00-5524-11e9-8dcf-e7e953bbb762.png)

**Comment by TatsukiWashimi** [comment]
100Vac の電源ノイズ測定については、ノッチフィルターを検討する。
https://detail-infomation.com/notch-filter/
![ノッチフィルタの回路図と設計方法](https://user-images.githubusercontent.com/18456905/55370200-b1228280-5534-11e9-9a55-8509b8e97c50.jpg)

**Comment by TatsukiWashimi** [comment]
C=1uF, R=2.65kΩ にすると、60Hzをカットできる。
![spice_notch](https://user-images.githubusercontent.com/18456905/55375476-3f076900-5547-11e9-9b2a-d22b1c1f8642.png)

**Comment by TatsukiWashimi** [comment]
今CRY meetingでもらったコメント
・ADCノイズ測定用の回路に使っている抵抗の足がアンテナになってRFノイズを拾ってしまうかもしれないので、シールドした方が良い
・トンネル内で特に消費電力が大きい機器は排水ポンプなので、古田さんに連絡してON/OFFしている時間帯を教えてもらうとよい
・AC電源ノイズ測定用のノッチフィルターの周波数を調整するために可変抵抗を使うといいかも

**Comment by TatsukiWashimi** [comment]
DC電源モニター回路を一つ作った。
が、現在回路室のADCがラックから取り外された状態で、テストできない。

**Comment by TatsukiWashimi** [comment]
AC電源用のノッチフィルターに用いる抵抗値、静電容量が個体差(±5%)でばらついたときに周波数特性がどうなるか見てみる。

理想的な場合
![spice_notch](https://user-images.githubusercontent.com/18456905/55528778-1616dd80-56d9-11e9-917a-90fcd89ec13b.png)

乱数でばらつかせたとき
![spice_notch_rndm](https://user-images.githubusercontent.com/18456905/55528808-33e44280-56d9-11e9-90ac-e098008383ff.png)

**Comment by TatsukiWashimi** [comment]
前述のように4個の抵抗とコンデンサでノッチ回路を組み、それらの素子の値が σ=5% でばらついたとき、振幅100*√2 V, 周波数 60Hz の電源によってAA chassisのピンの間にかかる電圧をみつもった。
手計算で式を書き下し、乱数でR, Cの値を決めるMCを10万回試行した結果が以下。

![notchMC_5ppc](https://user-images.githubusercontent.com/18456905/55538691-fa6fff00-56f9-11e9-9419-eb9b33078f49.png)

< 6V なので、ADCのダイナミックレンジに十分収まる。

**Comment by TatsukiWashimi** [comment]
バグチェックのため、ノッチ周波数が60Hzにならないような状態での60Hzの出力値を、LTspiceと自分のMCで比較する。

R = 2kΩにしたLTspiceは、
![spice_notch_2kOhrm](https://user-images.githubusercontent.com/18456905/55541019-175b0100-56ff-11e9-8cce-8d31a4cb44d7.png)

~ 19V @60Hz

**Comment by TatsukiWashimi** [comment]
実際に使用した素子の値を入れた場合

![spice_notch_actualy](https://user-images.githubusercontent.com/18456905/55691577-685a4600-59da-11e9-871f-3fee60e15467.png)

**Comment by TatsukiWashimi** [comment]
DCモニター回路の試作機
しゃしん

R=50kΩ、C=1uF

• Ch1 : Glitch noise monitor for +18V / +24V
• Ch2 : Stability monitor of DC voltage for +18V / +24V ( -> x 1/4)
• Ch3 : Glitch noise monitor for -18V / -24V
• Ch4 : Stability monitor of DC voltage for -18V / -24V ( -> x 1/4)


昨日、X-endにDCモニター回路を入れてきた。
回路をAAにつなぎ、電源側のコネクタにテスタを当てて抵抗値を確認したら、+/-両方ともground線との間は70kΩ

![Screenshot from 2019-04-10 09-45-58](https://user-images.githubusercontent.com/18456905/55843878-7bede400-5b75-11e9-8c2a-a26520af17cf.png)

ch1, 3はDC成分が止められていることが確認できる。
ch2, 4は~4500counts -> 2.7V
expectとしては、18V * 20kΩ/70kΩ = 5.1V なので、およそ半分程度しか見えていない。

とりあえずmodel上でVに換算した
![Screenshot from 2019-04-10 10-19-10](https://user-images.githubusercontent.com/18456905/55844818-29fb8d00-5b7a-11e9-9e0e-de0b6c4c56e9.png)

**Comment by TatsukiWashimi** [comment]
読みだされる電圧値が予想の半分程度になっている事について。
AAの各pinは、groundとの間に10kΩの抵抗があり、pin同士はそれを通じて20kΩで繋がっている。
しかし、AA自体の駆動のために18V電源ラインがあるため、電源ケーブルとAA筐体のgroundが繋がっている場合、DCモニター回路のground線がpinの10kΩを通らずにショートカットしてしまう。

![IMG_20190410_104131](https://user-images.githubusercontent.com/18456905/55846581-291a2980-5b81-11e9-9b93-eff46380eb49.jpg)

その結果、18V線とground線の間の抵抗値は60kΩになり、ADCされる電圧値は
18V * 10kΩ/60kΩ = 3V となる。

**Comment by TatsukiWashimi** [comment]
spectrum
![Screenshot from 2019-04-10 11-43-27](https://user-images.githubusercontent.com/18456905/55847858-f0c91a00-5b85-11e9-82bb-cc24d240c8cd.png)

**Comment by yokozawa1985** [comment]
山本さんか押野さんに聞いて、FScanしてみましょう。

**Comment by TatsukiWashimi** [comment]
さっき山本さんに入れてもらいました。
明日の朝9時から見えるそうです

**Comment by TatsukiWashimi** [comment]
Fscanは、チャンネル名に誤植があり、今日は見れませんでした。
明日から見えるようになるはずです

**Comment by TatsukiWashimi** [comment]
AC電源モニター回路の試作機

![20190409_123537982trm](https://user-images.githubusercontent.com/18456905/55941620-8398b000-5c7d-11e9-9b23-22edaabcf9c0.jpg)
![20190411_170703287](https://user-images.githubusercontent.com/18456905/55941639-8dbaae80-5c7d-11e9-9a9f-23beae05d5a9.jpg)
![20190411_170713498](https://user-images.githubusercontent.com/18456905/55941780-e5f1b080-5c7d-11e9-9ac8-187bd863f5f9.jpg)

コンセントに挿してテスターで電圧を測ったところ、~1.5Vにできていた。

**Comment by TatsukiWashimi** [comment]
本日(4/12)、EX0ラックにAC電源モニター回路を設置してきた。
![ACpowerMoniter](https://user-images.githubusercontent.com/18456905/56043409-2cc3d100-5d78-11e9-80fc-b41b958661c0.png)

**Comment by TatsukiWashimi** [comment]
AC抵抗分割チャンネルの時系列波形
![ACtimeseries](https://user-images.githubusercontent.com/18456905/56076559-d6a16d00-5e0d-11e9-898b-791ff31884b0.png)

非常に汚い

**Comment by TatsukiWashimi** [comment]
AC monitor spectrum
![8632_20190413072252_screenshotfrom20190413142210](https://user-images.githubusercontent.com/18456905/56076578-1bc59f00-5e0e-11e9-9f53-cc7586065878.png)

**Comment by TatsukiWashimi** [comment]
よくわかっていない点：
Notch Filterで60Hzを落とす際、その周り(10~200Hzくらい)も影響を受けてV字のスペクトルになるはずだが、実際はほぼフラットになっている。
また、抵抗分割したほうは周波数によらず一律に1/20になっているはずだが、Notch Filterよりも2桁大きい。

**Comment by yokozawa1985** [comment]
そういえば、glitch monitorはADCノイズに埋もれていませんか？？
必要ならばwhitening filterでゲインを上げることを検討してみてください。

**Comment by TatsukiWashimi** [comment]
4/16の電源モニターのFscanを見ると、DQが抜けている期間を挟んでfloor levelが大きく変わっている。

DC電源
![spec_0 00_100 00_K1_1239408018_1239494418](https://user-images.githubusercontent.com/18456905/56420161-e02c4880-62d7-11e9-982b-492abddfdab0.png)


AC電源
![spec_0 00_100 00_K1_1239408018_1239494418](https://user-images.githubusercontent.com/18456905/56420225-1ff33000-62d8-11e9-8281-bfd28f683835.png)

**Comment by TatsukiWashimi** [comment]
比較的最近のAC電源波形

![Screenshot from 2019-04-19 19-21-00](https://user-images.githubusercontent.com/18456905/56420294-592ba000-62d8-11e9-9bcc-cb35b0a535e3.png)

**Comment by TatsukiWashimi** [comment]
4/17に横澤さんがセンターでオシロを使って見た100V AC波形
![IMG_2187](https://user-images.githubusercontent.com/18456905/56420890-deb04f80-62da-11e9-87f0-5a477bbd14a7.jpg)

**Comment by TatsukiWashimi** [comment]
XendのDCモニター回路ですが、DQしていないし改良もしたいので、回収しました。

**Comment by yokozawa1985** [comment]
必要に応じて、別issue立てます。
