### ISSUE TITLE
おんどとりのmedm画面の更新

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#118]
**改善案**
どのように改善してほしいか書いてください。

今年初めから今日にかけて、たくさんのおんどとり (特に新規ラック)に追加が完了した。
今あるmedmに追加でもいいですし、新たなmedm画面を作成してくれてもいいので
やってくれそうな人募集。

**Comment by neouniverse** [comment]
これは設置した人が設置したものを追加してMEDM上であたいの確認までできて
初めて一つ設置が完了しましたと言えるものであって、
とりあえず置きまくって後でまとめてモニタを作りましょうという進め方は
あまりお勧めできないです。

他のところでも1つずつ確実に進めましょうと提案しているのはそういう事です。

**Comment by yokozawa1985** [comment]
了解いたしました、今後は注意いたします。
