### ISSUE TITLE
今後インストールするセンサーのためにADCを確保できるかどうか

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#12]
https://github.com/gw-analysis/detector-characterization/issues/92#issue-316548000 から

bKAGRA phase1を通して、PEMの仕事を周知できたので、phase2以降のADCの追加について相談する土壌が整ったかもしれない。
また、山本さんがぽろっと、ADCだけならなんとかなるかもしれないと言っていた。
そこで、せめて以下の通りのような感じでADCを追加したいといってみる。
(最終的には宮川さんになると思うが、とりあえず山本さんに相談してみよう)

まあ、いずれにせよ、いまのIY0のADCを全て埋めるのが先ではある。

優先度 最高
EX0, EY0(両エンド1階)に1枚ずつ

優先度 高
IY0(中央1階)にもう一枚 (PSLからPR系までの環境センサーを接続。今あるものはITMY周り用というイメージ。ただし、IX0ができるまではBS周りもIY0に集める)

優先度 中
EX1, EY1(両エンド2階)に1枚ずつ
IX1 (or IY1)に1枚 (中央2階環境センサー用)

優先度低
IX0に2枚 (ITMX周りとBSからOMCまでの環境センサー用。)
IY1 (or IX1)に1枚

**Comment by yokozawa1985** [comment]
これは、少し前の記事かもしれません。
EX0, EY0はclio ADCを追加したことにより最低限は確保、
PCal ADCを追加するかは、山本さん達と要相談

IY0, IX0ともにまだ空きはあるため、埋まってさらに追加ADCが必要になってから相談
EX1, EY1, IX1 or IY1は設置したい環境チャンネルが決定してから相談。
今の所、weather station, 地震計が設置されている。
