### ISSUE TITLE
おんどとりxmlファイルから電波強度と電池残量の情報を取得する

### ISSUE THREAD

**Issue by shoichioshino** [gw-pem/kagra-pem#120]
### 目的　（なぜそれをやりたいのか、）
おんどとりに問題が発生した時に検知しやすくする

### ToDo　(どうすればIssueをCloseできるか)
 - [x] 1. プログラムの修正方法確認
 - [x] 2. プログラム修正作業＆テスト
 - [x] 3. 現行システムでのテスト
 - [ ] 4. 現行システムの置き換え

### レビュー用まとめ　（ToDoが終わっているかどうか簡潔に示す）
1.
2.
3.
4.

**Comment by shoichioshino** [comment]
1.プログラムの修正方法確認

1. 現在は親機ごとにプログラムが用意されているが違いはxml_dir, archive_dir, exe_commandに入力している値
今回のようにプログラムを修正する時に手間がかかるのでプログラムは一つにして値を入力して親機を指定する
2. 値の取り出し方法をsscanf関数に変更する
3. 電池残量は子機ごとではなくチャンネルごとに記載されているので出力時に注意する
4. 中継器がある時の電波強度の値取り出し方法は要検討

**Comment by shoichioshino** [comment]
1.プログラムの修正方法確認

親機ごとにプログラムを用意しなければならない訳ではないそうなので入力値で親機を指定する方式で修正を行なってみる。
テスト環境として茂住計算機室のおんどとりは自由に使用できる

**Comment by shoichioshino** [comment]
引数を指定する形に修正したのでmozumiを置き換えてテストを行う。

**Comment by neouniverse** [comment]
温湿度、電波強度、電池残量など値を記録するチャンネルに加えて
通信状態(0=error, 1=no errorみたいなもの)を記録するチャンネルも定義すると
アラート画面作りに便利だと思います。

**Comment by shoichioshino** [comment]
> 通信状態(0=error, 1=no errorみたいなもの)を記録するチャンネルも定義すると
> アラート画面作りに便利だと思います。

ありがとうございます。
電波強度が5~1で表示され、通信できないときに0を返すそうなので、
シェルスクリプトの段階で通信状態の判別を入れられないか試してみます。

**Comment by shoichioshino** [comment]
シェルスクリプトの第４引数に電波強度、第５引数に電池残量が入力されるようにした。
現在はmozumiで動作している。
電波強度と電池残量のチャンネル名をどうするか議論する必要がある。
とりあえず試験的に以下のように設定する
K1:PEM-ONDTR_MOZUMI_RACK_DMG1_RSSI　電波強度
K1:PEM-ONDTR_MOZUMI_RACK_DMG1_BATT　電池残量

**Comment by shoichioshino** [comment]
現行のおんどとり用EPICSはk1rackで動いている。
テスト用に新しくk1remを作成してEPICSチャンネルを作成した。
値が入力されているのを確認したので、あとはmedmを作成する。

**Comment by shoichioshino** [comment]
userappsのrem以下に電波強度と電池残量表示用のmedmを作成した。
REM_ALERT_RSSI_BATT.adl
K1REM_RB_ALERT.adl

通信できないときは黄色の点滅、電池残量が0のときは赤が点灯するようにした。
![medm](https://user-images.githubusercontent.com/23567378/53543641-b754c600-3b66-11e9-8ad9-f941181cd1b3.png)

**Comment by shoichioshino** [comment]
温度と湿度も表示するよう変更した。
![medm](https://user-images.githubusercontent.com/23567378/53622841-7e882000-3c3e-11e9-8538-476b3329973b.png)

現行システムの置き換えについては日程や手順が決まっていないので本件はここまでで完了とする。
