### ISSUE TITLE
EXC磁場データ解析 : 夜の時間変動

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#121]
1/31の夕方から2/1の朝にかけて取得した、EXCクライオスタット内部の磁場データの解析です。
#115 とは論点が少し異なるので、別issueにしました。

スペクトルを重ね描いたものがコチラ
![jan31_incry_night](https://user-images.githubusercontent.com/18456905/52530922-ec80ac00-2d50-11e9-8300-88318201fad1.png)

**Comment by TatsukiWashimi** [comment]
ほとんど違いは見られないが、110Hz付近のピークの周波数が時間とともに変化している。
![night_110hz](https://user-images.githubusercontent.com/18456905/52530935-11751f00-2d51-11e9-8372-bb3e74577185.png)

**Comment by TatsukiWashimi** [comment]
それぞれGaussian + constantの関数でFitし、ピーク周波数を求めてplotした。
![110hz](https://user-images.githubusercontent.com/18456905/52530946-42edea80-2d51-11e9-91b2-ede5b4313564.png)
1時間あたり約1Hz減っている。

**Comment by TatsukiWashimi** [comment]
同様の現象が、420Hz付近でも見られる。
200Hzや300Hzのまわりにはない
![night_420hz](https://user-images.githubusercontent.com/18456905/52531704-f3adb700-2d5c-11e9-964c-6cf69bf15f88.png)
![420hz](https://user-images.githubusercontent.com/18456905/52531709-045e2d00-2d5d-11e9-8def-a170dcf989ee.png)
1時間あたり約1.9Hz減っている。

**Comment by TatsukiWashimi** [comment]
確認のため、ほかのピークの周波数の時間依存性を見てみると、10時間で0.1Hz未満の変動に収まっている。

![17hz](https://user-images.githubusercontent.com/18456905/52531721-3079ae00-2d5d-11e9-858a-90882b30c714.png)
![60hz](https://user-images.githubusercontent.com/18456905/52531724-34a5cb80-2d5d-11e9-836d-b57fe71d14ac.png)
![311hz](https://user-images.githubusercontent.com/18456905/52531729-3b344300-2d5d-11e9-9e1e-dd744aa85927.png)

**Comment by TatsukiWashimi** [comment]
xyz成分で見ると、115Hzはy軸方向、430Hzはx軸方向に偏っている。
![exc_incry_42_115hz](https://user-images.githubusercontent.com/18456905/52531853-6f106800-2d5f-11e9-9f52-d43c09759a58.png)
![exc_incry_42_430hz](https://user-images.githubusercontent.com/18456905/52531855-7172c200-2d5f-11e9-8748-09ed08ad3411.png)

**Comment by TatsukiWashimi** [comment]
DC成分の時間変化
時系列波形の平均値をplotしている。
![dc](https://user-images.githubusercontent.com/18456905/52533559-a93a3380-2d78-11e9-89f4-18310bcef69f.png)

2013年の端山さんの測定([https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/DocDB/ShowDocument?docid=1997](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/DocDB/ShowDocument?docid=1997))と比べると、オーダーは合っている(10^-6 T)が、factor 2だけ異なる。
変動も小さい。

**Comment by TatsukiWashimi** [comment]
温度変化
![screenshot from 2019-02-12 11-00-23](https://user-images.githubusercontent.com/18456905/52686889-f72a8380-2f92-11e9-839f-fa7889fd30a9.png)

**Comment by TatsukiWashimi** [comment]
データをexportしてrootでplotし、spline補完した値を書き出す。

![temperature](https://user-images.githubusercontent.com/18456905/52767818-ee0ee480-306e-11e9-8b61-6a9275eb135b.png)

25.7214
25.3725
25.1647
25.0051
24.9112
24.8003
24.7403
24.5674
24.3647
24.2985

**Comment by TatsukiWashimi** [comment]
これを使って温度vs周波数のplotにすると、
![110hz_temp-freq](https://user-images.githubusercontent.com/18456905/52768470-f536f200-3070-11e9-8344-99f0453f69d7.png)
![420hz_temp-freq](https://user-images.githubusercontent.com/18456905/52768476-f8ca7900-3070-11e9-8a9a-4cb0d94bfea0.png)

**Comment by TatsukiWashimi** [comment]
1/31の昼(14:48)に取った空調off, 冷凍機offのデータ(EXC_inCRY_36.xml)も見てみる。
このときのbooth内温度は26.50度だった。
![exc_incry_36_115hz](https://user-images.githubusercontent.com/18456905/52830271-71821180-3113-11e9-8348-889984c1a355.png)
![110hz_addhiru](https://user-images.githubusercontent.com/18456905/52830490-3c29f380-3114-11e9-9029-670cf481b284.png)
![110hz_temp-freq](https://user-images.githubusercontent.com/18456905/52830476-2ddbd780-3114-11e9-8bc5-fe5c206cf2e6.png)

420Hz付近の方はハム以外のピークが見当たらない
![exc_incry_36_420hz](https://user-images.githubusercontent.com/18456905/52830524-624f9380-3114-11e9-9178-119f86ba555a.png)

**Comment by TatsukiWashimi** [comment]
クライオスタット内部で同時にデータを取得していた、もう片方のMagのスペクトルも見てみる。

![exc_incry_42_115hz_mag2](https://user-images.githubusercontent.com/18456905/52834220-160c4f80-3124-11e9-9fbd-ec5292c11726.png)
![exc_incry_42_430hz_mag2](https://user-images.githubusercontent.com/18456905/52834223-199fd680-3124-11e9-82f0-d18d2317bfc3.png)
115Hzにも430Hzにもピークは見られない。

このことから、クライオスタット外部から侵入した磁場だとは考えにくい。

WAVの機械的共振で磁石が振動していると考えると、両方のMagで見えるはずだが、距離が近いMag①では大きく、遠いMag②では小さくて埋もれているのかもしれない。
これは、H田中君のposition scan dataで検証可能。

一番ありえそうなのは、Magの設置に使用しているゴミ箱の機械的共振が原因で、Mag①のところでは振動振幅が大きく、②のところでは小さかった。というシナリオ。
これは、加速度計で検証できる。

**Comment by TatsukiWashimi** [comment]
WAVの共振だった場合の磁場勾配を計算する。
x成分(ビーム軸方向)のピークの高さは、fitから
![exc_incry_42_115hz_mag1_x](https://user-images.githubusercontent.com/18456905/52835361-7f429180-3129-11e9-9509-6eb0f0075ea1.png)
1.298x10^-13 T/√Hz

これが16cm離れたところでゼロになっているとすると、
∂Bx/∂x = 8.1x10^-13 T/m/√Hz

**Comment by TatsukiWashimi** [comment]
H田中君に、クライオスタット内磁場マップ測定データを見てもらった。

WAVに近い列の5点
![x-20cm](https://user-images.githubusercontent.com/18456905/52990957-d019f900-344d-11e9-82d3-6406c5e26b0c.png)

中央列の5点
![x0](https://user-images.githubusercontent.com/18456905/52990959-d4461680-344d-11e9-9704-96282541d433.png)

WAVから遠い列の5点
![x 20cm](https://user-images.githubusercontent.com/18456905/52990993-f3dd3f00-344d-11e9-80ac-830192d4cbe6.png)

これらを見ると、どの点でもピークの大きさはほとんど変わらない。
WAVの磁石からの磁場ではなく、地磁気による一様なDC磁場にMag固定具の機械的共振がカップルしたものである可能性が高い

**Comment by yokozawa1985** [comment]
加速度計で試験しましょう。

**Comment by TatsukiWashimi** [comment]
> DC成分の時間変化
> 時系列波形の平均値をplotしている。
> ![dc](https://user-images.githubusercontent.com/18456905/52533559-a93a3380-2d78-11e9-89f4-18310bcef69f.png)
> 
> 2013年の端山さんの測定(https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/DocDB/ShowDocument?docid=1997)と比べると、オーダーは合っている(10^-5 T)が、約半分の値。
> 変動も小さい。

国土地理院の[地磁気計算サイト](https://vldb.gsi.go.jp/sokuchi/geomag/menu_04/index.html)で、Xend付近をクリックして確認した結果
![ike](https://user-images.githubusercontent.com/18456905/53224649-d8c23780-36b8-11e9-8968-25a795f4c1ab.png)
[2015年の地磁気図](http://www.gsi.go.jp/common/000148086.pdf)
[2010年の地磁気図](http://www.gsi.go.jp/common/000148081.pdf)

**Comment by TatsukiWashimi** [comment]
610 uV/count で作り直したplot

![spec_night](https://user-images.githubusercontent.com/18456905/53331777-0ca99100-3935-11e9-9093-b8c814b065d8.png)
![110hz_spec](https://user-images.githubusercontent.com/18456905/53331787-13d09f00-3935-11e9-953a-888a8b004fc0.png)

**Comment by TatsukiWashimi** [comment]
換算値を直したDC成分

![dc](https://user-images.githubusercontent.com/18456905/53457059-31f0e900-3a74-11e9-9f50-590e2ac3b90a.png)

![default](https://user-images.githubusercontent.com/18456905/53457072-39b08d80-3a74-11e9-8eb8-ee65cec4d1c3.png)

**Comment by TatsukiWashimi** [comment]
DC成分の時間変動について、端山さんの測定と比べると変動が小さい。
気象庁地磁気観測所のwebサイトを見ると、

柿岡観測所(茨城)のデータ
![10 23](https://user-images.githubusercontent.com/18456905/53458859-06253180-3a7b-11e9-8fd4-3bdb24a7952c.png)
![1 31](https://user-images.githubusercontent.com/18456905/53458866-0ae9e580-3a7b-11e9-97a3-22d7e5579668.png)

**Comment by TatsukiWashimi** [comment]
closeします
