### ISSUE TITLE
加速度計を扱う練習

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#125]
加速度計を扱う練習を行う。
ついでに#121 で挙がった、磁場測定のときに使用した固定具の機械的共振を調べる。

使用するものは、IYCのポータブルチャンネルの加速度計3つとマイクひとつ
![s_20190221_121038629](https://user-images.githubusercontent.com/18456905/53141090-27e16d00-35d2-11e9-97ed-b14c30363580.jpg)
![sitemap](https://user-images.githubusercontent.com/18456905/53139660-b3a4ca80-35cd-11e9-88a1-8ec612bd0f5e.png)

K1:PEM-SENSOR_IYC_RACK_IY0_12_OUT16
K1:PEM-SENSOR_IYC_RACK_IY0_13_OUT16
K1:PEM-SENSOR_IYC_RACK_IY0_14_OUT16
K1:PEM-SENSOR_IYC_RACK_IY0_15_OUT16

**Comment by TatsukiWashimi** [comment]
とりあえず定盤に置かれたままの状態でデータを取ってみた。

![test1](https://user-images.githubusercontent.com/18456905/53140392-e059e180-35cf-11e9-8b4c-200bb9ee1cbc.png)

**Comment by TatsukiWashimi** [comment]
定盤に向かって叫びながら取ったデータ
![test2](https://user-images.githubusercontent.com/18456905/53140677-d5ec1780-35d0-11e9-8ef2-ab817f88ded2.png)

**Comment by TatsukiWashimi** [comment]
スマホのバイブを鳴らせて定盤に置くと、
![test3](https://user-images.githubusercontent.com/18456905/53140878-780bff80-35d1-11e9-83bb-2db9fbc4ca00.png)

**Comment by TatsukiWashimi** [comment]
特に振動や音を加えていない状態でも、時折　K1:PEM-SENSOR_IYC_RACK_IY0_13_OUT16　に
パルス状のノイズが生じる。
![test4](https://user-images.githubusercontent.com/18456905/53141669-4b0d1c00-35d4-11e9-9a17-3fbbfa2f743d.png)

**Comment by TatsukiWashimi** [comment]
Magのときと同じ設定
    range : 0 - 7000 Hz
    bw : 0.05Hz
    average : 20
にする。coherenceも見るようにする。
![test5](https://user-images.githubusercontent.com/18456905/53142957-4dbe4000-35d9-11e9-9c7c-4fc4412eec8f.png)

**Comment by yokozawa1985** [comment]
ch13の加速度計のglitch気になりますね。

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 ですね。次に作業するときは、加速度計のケーブルを抜いたり入れ替えたりしたデータも取っておこうと思います。

**Comment by TatsukiWashimi** [comment]
昨日取ったデータのリスト。
_1 ~ _7 はゴミ箱の共振、_8はマイクスタンドの共振測定。
固定は、とりあえずその辺にあったピンクの養生テープを使った。

IY0_1.xml ： 天井面に3軸方向に設置
IY0_2.xml ： 上に同じ
IY0_3.xml ： x-面(Mag①を設置していた面)に3軸方向設置
IY0_4.xml ： x+面(Mag②を設置していた面)に3軸方向設置
IY0_5.xml ： y+面(Yend方向の面)に3軸方向設置
IY0_6.xml ： y-面(↑の逆の面)に3軸方向設置
IY0_7.xml ： x-面、y+面、天井面(z)のそれぞれの方向を向いて設置
IY0_8.xml ： マイクスタンド。Z天頂方向、x首の方向, y余った方向。↓の絵の通り
![img_2147](https://user-images.githubusercontent.com/18456905/53215225-05635880-3693-11e9-8c17-ac1abec0f514.jpg)

**Comment by TatsukiWashimi** [comment]
各fileのpower spectrum

![iyc_1 power](https://user-images.githubusercontent.com/18456905/53220976-998cea00-36aa-11e9-95b2-eb5ebd041e81.png)

![iyc_2 power](https://user-images.githubusercontent.com/18456905/53220981-9e519e00-36aa-11e9-991a-4d817bac348d.png)

![iyc_3 power](https://user-images.githubusercontent.com/18456905/53220985-a1e52500-36aa-11e9-9ce2-9ab5d8c7c0ab.png)

![iyc_4 power](https://user-images.githubusercontent.com/18456905/53220986-a4e01580-36aa-11e9-923a-b4a7b4d37804.png)

![iyc_5 power](https://user-images.githubusercontent.com/18456905/53220991-a8739c80-36aa-11e9-8fc2-7ffab296e9b3.png)

![iyc_6 power](https://user-images.githubusercontent.com/18456905/53220994-ac072380-36aa-11e9-97d0-c2eb62e3b1ad.png)

![iyc_7 power](https://user-images.githubusercontent.com/18456905/53220998-af021400-36aa-11e9-9316-5efb33ee178f.png)

![iyc_8 power](https://user-images.githubusercontent.com/18456905/53221001-b32e3180-36aa-11e9-8559-52a9fa27cbf8.png)

**Comment by TatsukiWashimi** [comment]
磁場測定のときにMag①を付けていた面(IY0_3.xml)の、110Hzおよび420Hz付近をよく見てみる。
![110hz](https://user-images.githubusercontent.com/18456905/53221101-3bacd200-36ab-11e9-82ba-222d7128c6e9.png)
![420hz](https://user-images.githubusercontent.com/18456905/53221104-3ea7c280-36ab-11e9-8945-6850f0ca71d6.png)

**Comment by TatsukiWashimi** [comment]
改善点
・バックグラウンド測定(ケーブル、ADC)
・固定方法をしっかりしたものにする
・ゴミ箱単体ではなく、Mag-13も取り付ける (場合によってはケーブルも)
・温度を変化させて、ピークが移動するか確認する

**Comment by TatsukiWashimi** [comment]
固定方法について：
↓のような、立方体にネジ穴(TEAC706の場合はM6)が開いたものがあれば、3軸方向を向けて固定できる。
![mono37596544-150722-02](https://user-images.githubusercontent.com/18456905/53223129-acf08300-36b3-11e9-93bf-396072aefd18.jpg)
[monotaro](https://www.monotaro.com/g/00345716/)
しかし、既製品でちょうどいいサイズ・穴数のものは見つからない。

↓のようなアルミキューブを買って、工作室で自分で穴を開ければよいか。
![mono86194465-180314-04](https://user-images.githubusercontent.com/18456905/53223208-f4770f00-36b3-11e9-9ef4-1e6bb4f2049c.jpg)
[monotaro](https://www.monotaro.com/g/03397846/)

もしくはアクリル等のプラスチック
[acry-ya.com](http://www.acry-ya.com/acry-ya_new/html/diy/htm/block.htm)

**Comment by TatsukiWashimi** [comment]
Femtetでゴミ箱をモデリングし、応力解析の共振解析を走らせた。
素材はポリプロピレンと裏に書いてあるが、マテリアルリストに入っていないので、ポリエチレンで代用。

![model](https://user-images.githubusercontent.com/18456905/53230756-b89b7400-36ca-11e9-9c74-3e644ec8567c.png)

**Comment by TatsukiWashimi** [comment]
磁場解析と比べて、超簡単


<<固有値解析>>
固有値（共振周波数）:[Hz]
Mode[ 0] =  1.64551723e+01
Mode[ 1] =  2.01683636e+01
Mode[ 2] =  3.87580411e+01
Mode[ 3] =  4.91244696e+01
Mode[ 4] =  5.17696679e+01
Mode[ 5] =  5.30897592e+01
Mode[ 6] =  7.66046862e+01
Mode[ 7] =  7.91339812e+01
Mode[ 8] =  8.09150484e+01
Mode[ 9] =  8.71415551e+01
Mode[10] =  1.06650237e+02
Mode[11] =  1.09261664e+02
Mode[12] =  1.10349324e+02
Mode[13] =  1.23958321e+02
Mode[14] =  1.24539556e+02
Mode[15] =  1.37465371e+02
Mode[16] =  1.46157141e+02
Mode[17] =  1.46774834e+02
Mode[18] =  1.53218961e+02
Mode[19] =  1.54326603e+02

応力共振解析で得られるフィールド値（変位、ひずみ、応力など）はすべて相対値です。

計算終了
計算時間     : 00:01:04 (ソルブ:00:01:04)
メモリ使用量 : 2277[MB]
計算終了日時 : 2019.02.22 17:54:41

![mode0](https://user-images.githubusercontent.com/18456905/53232442-75430480-36ce-11e9-90f1-00f42a77776a.png)
![mode1](https://user-images.githubusercontent.com/18456905/53232443-75430480-36ce-11e9-943a-96941ad91d8b.png)
![mode2](https://user-images.githubusercontent.com/18456905/53232444-75430480-36ce-11e9-999c-c80703a0eab6.png)
![mode3](https://user-images.githubusercontent.com/18456905/53232445-75430480-36ce-11e9-8ef2-ffa1206ed852.png)
![mode4](https://user-images.githubusercontent.com/18456905/53232446-75db9b00-36ce-11e9-8897-fdb09b99d651.png)
![mode5](https://user-images.githubusercontent.com/18456905/53232447-75db9b00-36ce-11e9-8fe1-41ecdf384bde.png)
![mode6](https://user-images.githubusercontent.com/18456905/53232449-75db9b00-36ce-11e9-9953-ec4ee544878e.png)
![mode7](https://user-images.githubusercontent.com/18456905/53232450-75db9b00-36ce-11e9-97e0-54313460dfcc.png)
![mode8](https://user-images.githubusercontent.com/18456905/53232436-7411d780-36ce-11e9-8707-87dbbaedaeae.png)
![mode9](https://user-images.githubusercontent.com/18456905/53232437-74aa6e00-36ce-11e9-8b57-28c493b6e95e.png)
![mode10](https://user-images.githubusercontent.com/18456905/53232439-74aa6e00-36ce-11e9-8935-f8a98a0e12f9.png)
![mode11](https://user-images.githubusercontent.com/18456905/53232440-74aa6e00-36ce-11e9-9d44-c03c64b821f0.png)
![mode12](https://user-images.githubusercontent.com/18456905/53232441-74aa6e00-36ce-11e9-88d2-1e63963c2bc6.png)

**Comment by yokozawa1985** [comment]
ゴミ箱の固有振動解析すごい。

**Comment by TatsukiWashimi** [comment]
ground loop問題を回避するため、加速度計の筐体を定盤から絶縁したほうがいいという説がある。
これを検証するため、来る途中に秋葉原でM6のプラネジを買ってきた。
ワッシャーは在庫切れだったので、M8のもので代用する。
![20190320_170005542](https://user-images.githubusercontent.com/18456905/54670311-b8aa5a80-4b36-11e9-9e24-27a260c646d3.jpg)

3個ほど頭を切り落とした
![20190320_173204831](https://user-images.githubusercontent.com/18456905/54670340-cb249400-4b36-11e9-9663-a5567174f91f.jpg)

**Comment by TatsukiWashimi** [comment]
年度が明けてちゃんと買う場合
https://jp.misumi-ec.com/vona2/detail/221006308002/?CategorySpec=00000239007%3a%3amig00000002456534%0900000239362%3a%3ad&clkid=clkid_list_template

**Comment by yokozawa1985** [comment]
お疲れ様です。
電流は流れないでしょうか？
試験運用を経て、来年度になったら本格的に考えましょう。

**Comment by TatsukiWashimi** [comment]
ACC1 : プラネジ, K1:PEM-SENSOR_IYC_RACK_IY0_12_OUT16
ACC2 : 金属ネジ, K1:PEM-SENSOR_IYC_RACK_IY0_14_OUT16

**Comment by TatsukiWashimi** [comment]
BNCのgroundと定盤の電位差は、両者とも25~30mV

プラネジの方は絶縁され、金属ねじの方は導通していることを確認

**Comment by TatsukiWashimi** [comment]
ACC1 (S1809325) : プラネジ, K1:PEM-SENSOR_IYC_RACK_IY0_12_OUT16
ACC2 (S1809327) : 金属ネジ, K1:PEM-SENSOR_IYC_RACK_IY0_14_OUT16
![ACC1-p_ACC2-m_1](https://user-images.githubusercontent.com/18456905/54796290-f6bc9100-4c92-11e9-87db-1d190defe5c6.png)

**Comment by TatsukiWashimi** [comment]
![ACC1-p_ACC2-m_1](https://user-images.githubusercontent.com/18456905/54796413-82362200-4c93-11e9-8bae-a8aae870ffe4.png)

**Comment by TatsukiWashimi** [comment]
ネジを逆にする (ACC1 : 金, ACC2 : プラ)
場所はそのまま

![IYC_12 power](https://user-images.githubusercontent.com/18456905/54796796-0b9a2400-4c95-11e9-8d8a-32fb030473b9.png)

**Comment by TatsukiWashimi** [comment]
ネジを戻す

![IYC_13 power](https://user-images.githubusercontent.com/18456905/54797004-d510d900-4c95-11e9-97fb-37b4671602bc.png)

**Comment by TatsukiWashimi** [comment]
TEAC706
金属ネジ
![IYC_14 power](https://user-images.githubusercontent.com/18456905/54797435-73516e80-4c97-11e9-8e74-c37ac3fc66b2.png)

**Comment by TatsukiWashimi** [comment]
プラねじ
![IYC_15 power](https://user-images.githubusercontent.com/18456905/54797594-23bf7280-4c98-11e9-87d3-120f57975e48.png)

**Comment by TatsukiWashimi** [comment]
練習という意味では完了したので、closeします
