### ISSUE TITLE
卒論作成後に実施したいこと@音場測定

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#126]
卒論をまとめていく上で、新たに発生した測定したい項目や
確認したいことをまとめていく。
まとまったら、新たなissueとして立ち上げて、closeする。

**Comment by KiichiKaihotsu** [comment]
- SR3、OMCチェンバーの横にある送風機の前では100 Hz以下で多くのピークが立っていた。全ての送風機で当てはまるか確認。
- エンドエリアでの測定
- in airのレーザーの動き(揺らぎ)と音響雑音の相関
- 光学定盤の振動と音響雑音の相関
- 冷風機、送風機、Koach filterのon、off

ひとまず思いつくものです。

**Comment by yokozawa1985** [comment]
ありがとうございます。
4月以降、インジェクションにも力を入れ始めたいと思っておりますので、そこと合わせて議論していきましょう。
あと、前回のマップ作成から一つ大きく変わったところがあり、それは、冷却装置(メインの鏡を冷やす装置)が動いていることです。結構うるさいので注意深く観測することが重要となると思います。

**Comment by TatsukiWashimi** [comment]
送風機など特定の機器からの音を測るときは、筒で囲むなどして他からの音を遮蔽するのがいいかもしれません

**Comment by yokozawa1985** [comment]
そうですね、そろそろ観測中に止めるべき装置、止められない装置がわかってくるはずですので、装置の雑音の測定方法を含めて議論していきたいですね。

**Comment by yokozawa1985** [comment]
別issueにて立ち上げ
