### ISSUE TITLE
卒論作成後に実施したいこと@磁場測定

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#127]
卒論をまとめていく上で、新たに発生した測定したい項目や
確認したいことをまとめていく。
まとまったら、新たなissueとして立ち上げて、closeする。

**Comment by TatsukiWashimi** [comment]
PEM wikiを見る限り、現在常設の磁束計はなさそうですが、坑内の地磁気を長期観測してみるのはどうでしょうか。
#121 で言及したように、結構時間変動があるようですし、アメリカ出張のときに地下の地磁気は地上と比べてどうなのか聞かれたりしたので、簡単な割に面白いトピックスかと思います。

**Comment by yokozawa1985** [comment]
そうですね。今までは局所的な磁束の調査をメインにしていたのですが、
どこかに長期的に設置してもいいですね。
ただ、長期観測できるほど静かな環境でデータ取得ができるのかがわかりません。
作業の影響がないところで長期測定して初めて信頼できるデータが得られると思います。

**Comment by yokozawa1985** [comment]
別issueにて立ち上げ
