### ISSUE TITLE
冷凍機由来の電源ノイズ評価

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#129]
冷凍機およびコンプレッサによって生じるADCノイズを測定する。
IXCおよびIYCは既に冷却が始まっているので、EXCで行う。

目標は、ADCのポートを適当に終端して、
・冷凍機用電源の配電盤 ON/OFF
・コンプレッサー主電源 ON/OFF
・冷凍機モーター ON/OFF
それぞれの状態でノイズスペクトルを取得すること。

電源ラインの直接測定は別issueにする。

**Comment by TatsukiWashimi** [comment]
作成した回路。
Dsub-9のコネクタを、
　pin1-6 : 短絡
　pin2-7 : 51Ω 抵抗
　pin3-8 : 1MΩ 抵抗
　pin4-9 : 開放
の終端にして、4ch分の同時測定を行う。
GNDの共通化はしていない。
引っこ抜けるようにビニールひもを付けている。
適当なコンデンサを付けたものもやりたがったが、抵抗しか手短になかったので見送った。

![s-trm_20190307_132018214](https://user-images.githubusercontent.com/18456905/53933707-dca38000-40e2-11e9-8d6c-35db34ab08c9.jpg)

セロハンテープでぞれぞれのチャンネルを絶縁する。
![s-20190307_132824779](https://user-images.githubusercontent.com/18456905/53933786-36a44580-40e3-11e9-99af-2517369c90fa.jpg)

**Comment by TatsukiWashimi** [comment]
CRYの木村さんに確認をとったら、まだ冷却水を入れていないためコンプレッサの電源ONや冷凍機モーターONはできないとのこと。
配電盤のON/OFFだけはやっていいそうなので、本日はそれだけ測定する。

**Comment by TatsukiWashimi** [comment]
配電盤のブレーカーを入れる前
![1](https://user-images.githubusercontent.com/18456905/53936429-14afc080-40ed-11e9-91a6-cb5ad35ed23c.png)

配電盤のブレーカーを入れた状態
![2](https://user-images.githubusercontent.com/18456905/53936440-1ed1bf00-40ed-11e9-9227-2863ff9042ae.png)

特に違いは見られない

**Comment by yokozawa1985** [comment]
ありがとうございます。
4月に行われる冷凍機再開に向けてもう少し議論をして今度は100V電源やDC電源も見ていきましょう。

**Comment by TatsukiWashimi** [comment]
3月頭に入れたADCノイズ評価回路のデータを

![ch1_1-180Hz](https://user-images.githubusercontent.com/18456905/55522930-e7d9d380-56c1-11e9-9db7-aa80d65833d3.png)
![ch1_82-89Hz](https://user-images.githubusercontent.com/18456905/55522939-edcfb480-56c1-11e9-87b8-d1b9dcc10d2f.png)
![ch1_110-120Hz](https://user-images.githubusercontent.com/18456905/55522943-f1633b80-56c1-11e9-9498-1ef961f9a3d9.png)

**Comment by TatsukiWashimi** [comment]
![ch1_370-450Hz](https://user-images.githubusercontent.com/18456905/55523032-69c9fc80-56c2-11e9-9328-2bf6debdc045.png)
370~450Hz付近にも同じようなピークがある。

これらは、磁場測定のとき(#121 )に見えていたものと似たような挙動・周波数帯域である。
ゴミ箱の機械的共振ではなく、これが見えていたのか

**Comment by TatsukiWashimi** [comment]
3/5の夜から、このチャンネルDAQしている。
トレンドを見るとこんな感じ


![Screenshot from 2019-04-08 18-52-26](https://user-images.githubusercontent.com/18456905/55715369-8ef69c00-5a2f-11e9-840d-dcda1e4f28e1.png)

**Comment by TatsukiWashimi** [comment]
#90 を参考に、フレームファイルを読んで時系列波形とパワースペクトルをplotしてみた。

![result_timeseries](https://user-images.githubusercontent.com/18456905/55715467-c402ee80-5a2f-11e9-8201-99de21a153f1.png)
![result_powerspectrum](https://user-images.githubusercontent.com/18456905/55715476-c6fddf00-5a2f-11e9-8d86-6d5fbf3c4ba9.png)

**Comment by TatsukiWashimi** [comment]
https://gwpy.github.io/docs/stable/examples/spectrogram/plot.html
を見ながらspectrogramを表示させた。

specgram = data.spectrogram(1,fftlength=1,overlap=.5) **(1/2.)


![result_spectrogram](https://user-images.githubusercontent.com/18456905/55767409-be4eec80-5ab3-11e9-946f-a10a273f99fb.png)

**Comment by TatsukiWashimi** [comment]
z軸の範囲を調整
![result_spectrogram2](https://user-images.githubusercontent.com/18456905/55767677-e428c100-5ab4-11e9-94a3-dd25b31d3378.png)
![result_spectrogram3](https://user-images.githubusercontent.com/18456905/55767691-f0ad1980-5ab4-11e9-8e7b-0ad6d56f2d2a.png)
