### ISSUE TITLE
PEMのSDFが完成されていない

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#13]
https://github.com/gw-analysis/detector-characterization/issues/91#issue-316490171 から

モデルを再起動したとき等に、いまはPEMのセンサーのフィルタースイッチを手動で戻す必要がある。
これは、非効率的かつヒューマンエラーが入り込む余地があるので、MEDMにburt(snapshot)関連のボタンを作る。

**Comment by yokozawa1985** [comment]
今日やります。

**Comment by yokozawa1985** [comment]
safe.snapの設定は完了いたしました。

**Comment by MiyoKouseki** [comment]
レビュー待ち

**Comment by yokozawa1985** [comment]
/opt/rtcds/kamioka/k1/target/k1pemioo1/k1pemioo1epics/burt
に12/16のsafe.snapを登録したことにより完了。
