### ISSUE TITLE
抗口に気象計を設置

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#130]
**改善案**
KAGRA検出器付近のトンネル外の気象情報を保存するための気象計の設置
百葉箱のようなイメージ
GIF, VIS, DETの意見を聞きながらデータ取得するものとデータ取得法をまとめる。
5月末くらいまでのタスク

- [ ] 温度計

- [ ] 湿度計

- [ ] 圧力計

- [ ] 雨量計

- [ ] 風量計

- [ ] その他

**Comment by MiyoKouseki** [comment]
雨量計について
- 山の歪みと降雨の関係をモニターするために設置する。
- 光進電気の雨量計（[TR-011H](http://www.koshindenki.com/productdetail.aspx?id=237)）の見積もり待ち。RS232Cでシリアル通信できるので適当な計算機（みんなだいすきラズパイ）をおいてEPICSには流せそう。
- 坑口に設置する。設置場所と方法とかはまだ決まっていない。方法とかは光進電気と気象庁のが参考になる[1][2]。

[1] http://www.koshindenki.com/setting.aspx
[2] https://www.jma.go.jp/jma/kishou/know/kansoku_guide/tebiki.pdf
 




http://www.koshindenki.com/productdetail.aspx?id=237

**Comment by yokozawa1985** [comment]
GIFのメールが来なかったらこちらで勝手に決める。

**Comment by yokozawa1985** [comment]
早河さんにきいて、乗鞍でも使用しているものを買ってみることにした。
物品が届いたら次のissue

**Comment by MiyoKouseki** [comment]
物品が届いたのでClose
