### ISSUE TITLE
Acoustic injection@PSL room

### ISSUE THREAD

**Issue by TTanakaTT** [gw-pem/kagra-pem#132]
### 目的
PSL roomにacoustic injectionを行い、PSLおよびIMCのチャンネルとの相関を見る。

2018年の夏に一度PSL roomでacoustic injectionを行なっている。
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Reports/2018Toyama?action=AttachFile&do=view&target=Acoustic-injection-PSL.pdf

2019年冬にIMCにinjectionを行い、IMCの制御信号との相関は評価している。（資料の実験3）
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9943

中野さんからPSLからのノイズもIMCの制御系で見えるとのことだったので、PSLからinjectionを行い、PSLおよびIMCのチャンネルとの相関を評価しようと思う。

また、今回はリモートでinjectionを行おうと思っており、そのテストも兼ねている。

### ToDo
 - [x] 1. 取得チャンネルのリストアップ
 - [x] 2. 実験系のセットアップ
 - [x] 3. リモートでのinjection&測定
 - [x] 4. 解析
 - [x] 完了。Klogに投稿

### レビュー用まとめ
1.
K1:PEM-ACC_MCF_TABLE_IMCREFL_Z_OUT_DQ
K1:PEM-ACC_MCF_TABLE_REFL_Z_OUT_DQ
K1:PEM-MIC_MCE_TABLE_IMCTRANS_Z_OUT_DQ
K1:PEM-MIC_MCF_TABLE_IMCREFL_Z_OUT_DQ
K1:PEM-MIC_MCF_TABLE_REFL_Z_OUT_DQ
K1:PEM-ACC_PSL_PERI_PSL1_Y_OUT_DQ
K1:PEM-ACC_PSL_PERI_PSL2_X_OUT_DQ
K1:PEM-ACC_PSL_PORTABLE_1_OUT_DQ
K1:PEM-ACC_PSL_PORTABLE_2_OUT_DQ
K1:PEM-ACC_PSL_TABLE_PSL1_Z_OUT_DQ
K1:PEM-ACC_PSL_TABLE_PSL2_Z_OUT_DQ
K1:PEM-ACC_PSL_TABLE_PSL3_Z_OUT_DQ
K1:PEM-MIC_PSL_TABLE_PSL4_Z_OUT_DQ
K1:IMC-CAV_REFL_OUT_DQ
K1:IMC-CAV_TRANS_OUT_DQ
K1:IMC-MCL_SERVO_OUT_DQ
K1:PSL-REFCAV_ERR_OUT_DQ
K1:PSL-REFCAV_REFL_OUT_DQ
K1:PSL-REFCAV_TRANS_OUT_DQ
K1:PSL-TTFSS_TEMP_MON_OUT_DQ
K1:PSL-TTFSS_MIXER_MON_OUT_DQ
K1:PSL-TTFSS_EOM_MON_OUT_DQ
K1:PSL-TTFSS_PZT_MON_OUT_DQ
K1:PSL-PMC_MIXER_MON_OUT_DQ
K1:PSL-PMC_PZT_HV_MON_OUT_DQ
K1:PSL-PMC_REFL_DC_OUT_DQ
K1:PSL-PMC_TRANS_DC_OUT_DQ
K1:PSL-PMC_SLOW_MON_OUT_DQ
K1:PSL-PMC_FAST_MON_OUT_DQ
K1:PSL-PMC_TEMP_OUT_DQ

2.
スピーカーをPSL全室に設置
excitationチャンネルはK1:VIS-SR3_EXCITATION_BNC2_EXC

3.
測定データはここのpdfに軽くまとまっています
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Reports/PMCNoiseBudget

4.
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=10071

5.
http://klog.icrr.u-tokyo.ac.jp/osl/?r=8614

**Comment by TTanakaTT** [comment]
injectionが弱すぎて、チャンネルとの相関が見えなかったので、gainをあげて明日再測定
また、中野さんより5 kHzまでinjectionしたいとのことだったが、現在のexcitationチャンネルではその音を出せないので、すぐに対処できなければ後日5 kHzまでのinjectionも別で行う

**Comment by TTanakaTT** [comment]
他の環境ノイズとカップリングがある場合、そのカップリングとの切り分けのためにその環境インジェクションを行わなければいけない。（シェイカーやコイルでのインジェクション）

**Comment by TTanakaTT** [comment]
なので音響インジェクションだけではこれ以上の解析をしても研究としてはそれほど意味を持たないため、このissueはここで終わりにしたい

**Comment by TTanakaTT** [comment]
また付随して必要とわかったPEM用の高周波までinjection可能なportの作成も達成した
K1:PEM-EXCITATION_SR3_RACK_1
K1:PEM-EXCITATION_SR3_RACK_2
K1:PEM-EXCITATION_SR3_RACK_3
K1:PEM-EXCITATION_SR3_RACK_4
K1:PEM-EXCITATION_SR3_RACK_5
K1:PEM-EXCITATION_SR3_RACK_6
K1:PEM-EXCITATION_SR3_RACK_7
K1:PEM-EXCITATION_SR3_RACK_8

**Comment by TTanakaTT** [comment]
injectionの波形はまずwhite noise、測定が難しいならノコギリ波(フーリエ級数展開すると、注入周波数のn倍の波の重ね合わせになることがわかる)、それでも難しいならsinとするのが良いとのこと
また、どのopticsがよくカップリングしているかなどの評価のために小さいinjection用のスピーカーの作成が効果的である

**Comment by yokozawa1985** [comment]
とりあえずinjection strategyが完成したのでclose
