### ISSUE TITLE
磁束計の常設

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#134]
とりあえず2台を常設して長期モニターしてみる。
4/8の週の宿題のreminder

**Comment by yokozawa1985** [comment]
とりあえず、EXCとBSの2箇所にインストールすることに決めた。

**Comment by yokozawa1985** [comment]
Xendは電源もしっかりと監視しており、C chamberのcharacterizationの雛形になることが予定されている。

**Comment by TatsukiWashimi** [comment]
EXCに設置した磁束計とマイクの場所・写真を[JGW-L1910051](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=10051)にまとめました。

**Comment by TatsukiWashimi** [comment]
BSに設置した磁束計の写真です。
今はとりあえず結束バンドで固定していますが、明日コメリで適当な固定具(プラスチック)を買ってきて改善します。
![20190412_153023350](https://user-images.githubusercontent.com/18456905/56043271-e2425480-5d77-11e9-97f6-6906568acdc8.jpg)

**Comment by yokozawa1985** [comment]
done

**Comment by TatsukiWashimi** [comment]
EXCの磁束計とマイクのトレンドデータ

![Screenshot from 2019-04-20 09-09-24](https://user-images.githubusercontent.com/18456905/56448677-363ad380-634c-11e9-9dfb-58ab3246884f.png)

**Comment by TatsukiWashimi** [comment]
BS磁束計

![Screenshot from 2019-04-20 09-19-53](https://user-images.githubusercontent.com/18456905/56449122-a9464900-6350-11e9-90af-3e67ac63b2f4.png)
![Screenshot from 2019-04-20 09-41-41](https://user-images.githubusercontent.com/18456905/56449126-b2cfb100-6350-11e9-92e3-370e25cee9d8.png)
