### ISSUE TITLE
PEM maintenance day (5/8)

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#139]
Virgoの人たちが来る前に、坑内でPEMセンサー類の較正値を見直す。
5/8(火)に行う予定

ここに、作業中のメモや確認すべき点などを忘備録としてメモしていきましょう

**Comment by TatsukiWashimi** [comment]
BSの磁束計のスペクトルにwhitening filterの構造が見られない。
![Screenshot from 2019-05-07 12-28-25](https://user-images.githubusercontent.com/18456905/57269762-a45cf580-70c3-11e9-9ce1-f4c2effbce0f.png)
sitemapで確認したら、dewhiteningがoffになっていた。

**Comment by TatsukiWashimi** [comment]
今日のメモ
[20190508_memo1.pdf](https://github.com/gw-pem/kagra-pem/files/3156441/20190508_memo1.pdf)

**Comment by TatsukiWashimi** [comment]
google spread sheet
https://docs.google.com/spreadsheets/d/1xISFWRnT9Y2N-bxVqAFHlwZMDI-AxOJUF_S3deEMjW8/edit?usp=sharing

**Comment by ckozakai** [comment]
昨日撮った写真を一旦ここにおきます。
https://www.dropbox.com/sh/wt2zcl82du34grm/AAC7ceIqLS-bRJJmGiSGlpmoa?dl=0

**Comment by TTanakaTT** [comment]
他の写真です

IYCのwether station
![IYC_WETHER](https://user-images.githubusercontent.com/44667886/57444093-5ba36900-728a-11e9-84c9-e93ca8892bdd.jpg)

IMC transのmicrophone
![IMCTRANS_MIC](https://user-images.githubusercontent.com/44667886/57444095-5ba36900-728a-11e9-820e-249d8fc844e6.jpg)

**Comment by MiyoKouseki** [comment]
スプレッドシート内の地震計と気象計の黄色い箇所ですが、
MCFとMCIの地震計のシリアルは月曜日に坑内に行って確認します。
気象計は、IXVとIYC以外は知りません。IYCも地震計と一緒に確認してきます。

**Comment by TatsukiWashimi** [comment]
> スプレッドシート内の地震計と気象計の黄色い箇所ですが、
> MCFとMCIの地震計のシリアルは月曜日に坑内に行って確認します。
> 気象計は、IXVとIYC以外は知りません。IYCも地震計と一緒に確認してきます。

ありがとうございます。よろしくお願いします。

**Comment by TatsukiWashimi** [comment]
私の撮った写真は↓にまとめました。
https://photos.app.goo.gl/1BjHKo9fAMNrgkNg6

**Comment by TatsukiWashimi** [comment]
LIGOのPEM MAPと同じ色・記号でKAGRA PEM MAPを作ってみました。(パワポ)
[KAGRA_PEM_Map.pdf](https://github.com/gw-pem/kagra-pem/files/3171955/KAGRA_PEM_Map.pdf)

PDFの注釈機能でchannel名を入れたので、マウスポインタを乗せるとポップアップされます。
![無題](https://user-images.githubusercontent.com/18456905/57608350-be0caa00-75a7-11e9-895f-506beb7ed777.png)

**Comment by yokozawa1985** [comment]
みなさま、ありがとうございます！
