### ISSUE TITLE
音場、磁場の追測定@センターエリア

### ISSUE THREAD

**Issue by KiichiKaihotsu** [gw-pem/kagra-pem#140]
6月のKIW6での発表に向けて、卒論(開発、森)で行った結果を元に追測定する。

まずは5/10にIXCもしくはIYCのチェンバー近くで測定。
冷風機や送風機、FFUのonとoffのときを測定し、どのような違いがあるかみる。
その他の再測定すべき場所についてはピックアップして追記していく。

**Comment by imyukino** [comment]
IXC,IYC付近以外で測定したい箇所
・SR2チェンバーとOMCチェンバー近くの送風機(タニヤマの誘引ファン:SF200-4F-0.03(4)RR)のON/OFF比較。
さらにOMC定盤上にあるセンサーとマイク・磁束計とのコヒーレンスをとり、送風機がどのくらいセンサーに影響しているかを調べる(ON/OFFでのコヒーレンス比較)。

**Comment by KiichiKaihotsu** [comment]
とりあえず思いつくものを卒論で書いた図に示した。

橙色の丸は以前も測定した場所。
- 4番は卒論で示したIMM,PRM,PR3チェンバー近くに影響を与えているだろうと思われる場所
- 13番,17番は冷風機、送風機の前。100 Hz以下のピークが目立っていたのでもう少し詳しく測定したい。(特に17番は干渉計の出力に影響しそう。)

ピンク色の丸は以前は測定していない場所。
- ここにも冷風機、送風機があるが測定できていない

<img width="697" alt="pem-map-1" src="https://user-images.githubusercontent.com/45889411/57301052-114bac00-7113-11e9-9487-ea9e2c8a05b1.png">

**Comment by yokozawa1985** [comment]
issueありがとうございます。
設置場所に関しましては、現在作業中のため、後ほどコメントします。
胸中に発表タイトル送ってください。
Investigation of the magnetic and acoustic field environments of the KAGRA detector.
とか？

**Comment by yokozawa1985** [comment]
CチェンバはIYCにしましょう。12月の測定のセットアップが使えます。
それに伴って、8は測定してみましょう。
当日クリーンエリアの中で2箇所の測定場所を決めましょう。
今回は、送風機の測定は一箇所にしましょう。13がいいと思います。
あと4番とかですかね？これで5箇所になります。
PSL roomはどうしますか？？

**Comment by KiichiKaihotsu** [comment]
横澤さん、ありがとうございます。
タイトルについては今日中にメールで送らせていただきます。

測定場所について
4番は空間的にも開けていて、測定時期による変化(いろいろな装置が起動している、していない)を比較するのは面白いかなと思います。

PSLroomは以前は測定していないのもあり、どこかのデータと比較するというのが難しいと思うので、優先度は低めかなと思いました。
時間に余裕があれば測定してみたいです。

**Comment by KiichiKaihotsu** [comment]
IYCクリーンルームの外でffuをon,offしたときの結果が上手く保存されていなかったです。(おそらくonのデータにoffのデータが上書きされているので同じデータが名前違いで２つある)

クリーンルーム内で測定したffuのon,offデータもあまり差が無いことがわかったので今回の発表では外でのffuの変化を紹介しない、もしくは改めて磁場を測定しに行けることになったらその際に測定しようと思います。

**Comment by KiichiKaihotsu** [comment]
5/10の測定データです。
![result-190510](https://user-images.githubusercontent.com/45889411/57565634-2454c980-73fc-11e9-8827-c4c75cebba6b.png)

測定場所などについてはまとめたら載せます。

**Comment by KiichiKaihotsu** [comment]
![測定場所](https://user-images.githubusercontent.com/45889411/57566295-c331f380-7405-11e9-9ab9-05afa98fe0e5.png)

<img width="886" alt="測定場所-図" src="https://user-images.githubusercontent.com/45889411/57566288-b01f2380-7405-11e9-8b87-2dc691e7989f.png">

**Comment by TatsukiWashimi** [comment]
K-K1_C-1241438400-32.gwf
![Screenshot from 2019-05-13 09-51-58](https://user-images.githubusercontent.com/18456905/57590160-c68fc100-7564-11e9-9a9c-d89905ded41a.png)
![Screenshot from 2019-05-13 09-52-26](https://user-images.githubusercontent.com/18456905/57590165-d4dddd00-7564-11e9-872a-445532dfea60.png)

**Comment by TatsukiWashimi** [comment]
K-K1_C-1241488768
![Screenshot from 2019-05-13 09-54-17](https://user-images.githubusercontent.com/18456905/57590206-28502b00-7565-11e9-9d36-770a9e6b9e0e.png)
![Screenshot from 2019-05-13 09-53-58](https://user-images.githubusercontent.com/18456905/57590207-2ab28500-7565-11e9-9444-f9beb810b1ed.png)

**Comment by TatsukiWashimi** [comment]
K-K1_C-1241485568-32.gwf
![Screenshot from 2019-05-13 10-01-29](https://user-images.githubusercontent.com/18456905/57590354-25a20580-7566-11e9-9bb5-00fe99fa4784.png)
![Screenshot from 2019-05-13 10-01-21](https://user-images.githubusercontent.com/18456905/57590355-276bc900-7566-11e9-8f89-67eb0c15e537.png)

**Comment by TatsukiWashimi** [comment]
K-K1_C-1241485472-32

![Screenshot from 2019-05-13 10-21-27](https://user-images.githubusercontent.com/18456905/57590767-e2956180-7568-11e9-9a45-54ee5dc98abc.png)
![Screenshot from 2019-05-13 10-21-15](https://user-images.githubusercontent.com/18456905/57590769-e6c17f00-7568-11e9-9712-b4582c3ab56d.png)

**Comment by TatsukiWashimi** [comment]
K-K1_C-1241495744-32.gwf

![Screenshot from 2019-05-13 10-23-23](https://user-images.githubusercontent.com/18456905/57590842-2e480b00-7569-11e9-8bac-99df87c3e9cb.png)
![Screenshot from 2019-05-13 10-23-10](https://user-images.githubusercontent.com/18456905/57590843-2f793800-7569-11e9-8713-ab0a102e0dce.png)

**Comment by TatsukiWashimi** [comment]
現在のデータを見てみると、diagguiだとピークがいないが、frame fileではいる
![Screenshot from 2019-05-13 10-53-20](https://user-images.githubusercontent.com/18456905/57591646-7406d280-756d-11e9-9035-f2a0c1b97024.png)

**Comment by TatsukiWashimi** [comment]
昨日、磁束計とマイクをDsub-15に変換している自作コネクタを確認したところ、断線箇所が見つかりました。
回収したので、本日の午前中に修復して午後にインストールします。

磁束計自身にも不具合がないかは、まだ確認できていません
![20190514_115415181](https://user-images.githubusercontent.com/18456905/57740095-0b486300-76f1-11e9-8ed8-0d49588f3b15.jpg)

**Comment by TatsukiWashimi** [comment]
変換ケーブルを作り直しました。
![20190515_140921535](https://user-images.githubusercontent.com/18456905/57757058-90526d00-772f-11e9-8067-606bc927621b.jpg)

**Comment by KiichiKaihotsu** [comment]
鷲見さん

ありがとうございます。
いろいろな事情がありまして、再び神岡に行って測定することができるかどうかわかりませんが、もし行けるようでしたら磁場の測定もしたいと思います。

ご迷惑おかけしました。

**Comment by yokozawa1985** [comment]
先日は、急に磁場測定が難しくなったりして申し訳ございませんでした。
今ある結果をまずはまとめてみましょう。

**Comment by KiichiKaihotsu** [comment]
ひとまず測定は終わったのでcloseします。
