### ISSUE TITLE
代用となる磁束計の検討

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#141]
現在使用している磁束計の故障問題およびメーカー対応の問題と、単価が高いことから、代用できる他製品を検討する。

クライオスタットの外部から内部へ侵入するAC磁場は小さくなるので、外でモニターする分にはスペックを下げても良いかもしれない。

また、injectionのときにポータブルに使用するものは、1軸でも十分かもしれない。

**Comment by TatsukiWashimi** [comment]
ネットで調べて出てきた商品

・株式会社エムティアイ「FGS3-1000　三軸磁気センサ」
http://mticorp.co.jp/product/dccurrentsensor/dccurrentsensor2/

・株式会社ANET「フラックスゲート型磁気探査装置　MAGSUS」
https://www.anetrt.net/service/instruments/introduction/index.html#magsus

・ARFジャパン株式会社「高感度 3 軸フラックスゲート磁気センサ 　FLC3-70」
https://www.arf-japan.com/smi/Flux.pdf

・Macintyre Electronic Design Associates, Inc. 「MGC-1 SINGLE AXIS AC MAGNETIC FIELD SENSOR」

**Comment by yokozawa1985** [comment]
ありがとうございます。
実は、ミニ磁束計、昨年度購入しています。
また相談しましょう。

**Comment by TatsukiWashimi** [comment]
了解です

**Comment by TatsukiWashimi** [comment]
Mag-13が無事に修理されて帰ってきたため、このissueはcloseします
