### ISSUE TITLE
TrilliumcompactをIMCから移動

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#144]
### 目的　（なぜそれをやりたいのか、）
いろいろな距離でのコヒーレンスを測りたい。詳細は省くけど、SPAC法というのを使えば地面を伝うレイリー波の位相速度がわかる。VirgoでもMerkBeker氏によって行われている。

Virgoと比較して、神岡の岩盤は硬いことが言えると面白い。位相速度は岩盤の硬さを表すので、硬ければ、長期線でもコヒーレンスは残り、地面振動の逆相（基線長伸縮）が幾分低減される。なので柔らかいVirgoの岩盤よりも神岡の地下のほうがこれだけ基線長伸縮小さいですよーといえる。そのために位相速度を測る。

いろいろな距離に配置したいので、TrilliumCompactをMCI、BS、IXAにおく。

なので、MCEをBS、端山研から戻ってきたのをIXAに置く。

### ToDo　(どうすればIssueをCloseできるか)
 - [x] 1. BSに地震計をおけるか確認
 - [ ] 2. IXAに地震計をおけるか確認
 - [ ] 完了。Klogに投稿

**Comment by MiyoKouseki** [comment]
IXAはまだ。
- [ ] Whiteningフィルターに繋ぐために、Dsub9ピンとDsub15ピンの変換コネクタが必要。
- [ ] 風防用のアクリルの箱が必要。IXCにあるか？なければ学生部屋の棚。

**Comment by yokozawa1985** [comment]
PEMで不必要となったDsub15->9pinがYendにあったので、IX0ラックにつけておきます。

**Comment by yokozawa1985** [comment]
IX0のwhitening filterは9pinのものでした。

**Comment by MiyoKouseki** [comment]
このIssueをみて思い出した。IXCの地震計は放置している。
そのうちホワイトニングにいれて、ADCにつないで、信号を見る。

**Comment by yokozawa1985** [comment]
チャンネルはすでに確保している。
来週はいった際に起動して、反長期的な測定の計画を立ててみる。
頻繁に設置ポイントを変えるのは、O3以降にして、とりあえず、IXC付近に半年ぐらい置いてみたい。

**Comment by yokozawa1985** [comment]
IXCの地震計を早急に復活する

**Comment by yokozawa1985** [comment]
とっくに復旧していた。。
