### ISSUE TITLE
気象計のデータ取得

### ISSUE THREAD

**Issue by shoichioshino** [gw-pem/kagra-pem#145]
### 目的　（なぜそれをやりたいのか、）
抗口に設置された気象計からデータを取得する

### ToDo　(どうすればIssueをCloseできるか)
 - [x] 1. 気象計とPCを接続
 - [x] 2. PCでデータを確認
 - [x] 3. Web上からデータを見れるようにする
 - [x] 4. EPICSにデータを入力できるようにする

**Comment by shoichioshino** [comment]
Mac にデータロガーをインストールして接続しようとしたが、ソフトウェアがMojaveには対応していなかったため接続できなかった。
Linuxからデータを取得できないか確認する。

**Comment by yokozawa1985** [comment]
Windows10PCとdebian8PCをプレハブに置きます。(debian8 PCは先週oshinoさんがもっていってくださった)

**Comment by shoichioshino** [comment]
CentOSにweewxをインストールした。
自動でweb画面を生成してくれるが、デフォルトだとシミュレーターの値を表示している。
Vantage Pro2からの値を取得するように変更した。
以下から確認できる。
http://172.16.33.39/weewx/index.html

**Comment by shoichioshino** [comment]
30分間隔でデータを取得していたのを1分間隔に変更した。

**Comment by TatsukiWashimi** [comment]
オンサイト限定ですが、PEM mapから飛べるようにしました。
[http://k1sum0/~controls/PEMmap/](http://k1sum0/~controls/PEMmap/l)

右下のHutの横にある天気マークをクリックしてみてください

**Comment by shoichioshino** [comment]
6/28の雨量計データとアメダスなどのデータを比較してみるとだいたい同じ時間変化をしている
http://www.cbr.mlit.go.jp/takayama/hidamichi/uryou/index.html
https://www.jma.go.jp/jp/amedas_h/today-52051.html?areaCode=000&groupCode=37

**Comment by shoichioshino** [comment]
話し合いの結果、以下のチャンネル名を使うことになった
K1:PEM-WEATHER_ATOTSU_FEILD_(DOF)

- 気温：TEMP_OUTSIDE
- 室温：TEMP_INSIDE
- 湿度：HUM
- 気圧：PRES
- 雨量：RAIN
- 風力：WIND
- 風向：WIND_DIRECTION
- 電波強度：SIGNAL_QUALITY

**Comment by shoichioshino** [comment]
風力をWIND_POWERに変更
電波強度がすぐには取得できないので外した
HEAT_INDEX, WIND_CHILL, DEWPOINTを追加
