### ISSUE TITLE
落雷モニターの検討

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#146]
### 目的　（なぜそれをやりたいのか、）
坑内に設置した磁束計で、落雷による強い磁場が観測されている。
[http://klog.icrr.u-tokyo.ac.jp/osl/?r=9197](http://klog.icrr.u-tokyo.ac.jp/osl/?r=9197)
今後、干渉計の雑音やロックロスの原因になりかねない。

坑口に設置した気象計には雷センサーがないので、何らかの別手段が必要。
磁束計で十分かもしれないが、雷由来以外の磁場との切り分けも必要になるかもしれない。

このissueは検討・情報収集用で、購入設置等の動きは別に立ちあげます。

### ToDo　(どうすればIssueをCloseできるか)
 - [x]  雷検知方法のお勉強
 - [x]  雷センサを購入設置する場合の物品選定
 - [x]  別の所(気象庁など)から情報だけ引っ張ってくる場合の検討
 - [x]  コミッショニング中の干渉計に雷由来の変なことが起きていないか調べる
 - [ ] 完了。Klogに投稿

### レビュー用まとめ　（ToDoが終わっているかどうか簡潔に示す）
1.
2.
3.
4.

**Comment by TatsukiWashimi** [comment]
気象庁の雷監視システム「LIDEN」
[https://www.jma.go.jp/jma/kishou/know/toppuu/thunder1-2.html](https://www.jma.go.jp/jma/kishou/know/toppuu/thunder1-2.html)

**Comment by TatsukiWashimi** [comment]
気象業務支援センター オンライン気象情報  電文形式データ
[http://www.jmbsc.or.jp/jp/online/n-online0.html](http://www.jmbsc.or.jp/jp/online/n-online0.html)

>  雷観測データ VFJP40 － バイナリ
(※)
雷監視システム（LIDEN）による雷観測データ（最大で5万件の放電
データ（雷光）が格納され、一つの放電データの内容には、放電時
刻（0.01秒単位）や標定位置を示す緯度経度の他、１放電あたりの
後続雷撃数を示す雷多重度、対地雷か雲放電かなどの放電種別など
を含む）
（毎正分毎に、前１分間分の雷観測データを配信）
※ 配信資料に関する技術情報 第438号 別紙を参照。

**Comment by TatsukiWashimi** [comment]
商用の雷検知器

バスタ技研　[サンダーメーター](http://www5a.biglobe.ne.jp/~vasta/frame.html)

音羽電機工業　[雷レーダー](https://www.otowadenki.co.jp/item/%e9%9b%b7%e3%83%ac%e3%83%bc%e3%83%80%e3%83%bc/)
音羽電機工業　[雷センサ](https://www.otowadenki.co.jp/item/%e9%9b%b7%e3%82%bb%e3%83%b3%e3%82%b5/)

**Comment by TatsukiWashimi** [comment]
Blitzortung.org
[http://en.blitzortung.org/live_lightning_maps.php?map=41](http://en.blitzortung.org/live_lightning_maps.php?map=41)

**Comment by TatsukiWashimi** [comment]
最近、落雷が頻発しているようなので、そろそろ真面目に購入を検討する。

Blitzortung.orgのsystem blueというのが良さそうに見えたが、フォーラムの掲示板を見ると数年待たされるケースもあるっぽい。
https://forum.blitzortung.org/showthread.php?tid=1656&page=22

**Comment by TatsukiWashimi** [comment]
似たようなことを商用でやっている[Vaisala](https://www.vaisala.com/ja/products/instruments-sensors-and-other-measurement-devices/weather-stations-and-sensors/tss928)にも見積もり請求しておいた。
お高そう

**Comment by TatsukiWashimi** [comment]
湘南工科大学電気電子工学科成田研究室の「[雷現象技術情報](http://www.5656jp.com/index.html)」というサイトに色々な情報が載っている。
Blitzortung.orgにも参加しているようで、このサイトによると電子パーツの購入費用は約3万円とのこと。

ここにコンタクトを取ってみるのが良さそう。

**Comment by yokozawa1985** [comment]
そうですね、そんなに遠くないところ(抗口と解析棟とか)複数置く可能性があるので、あまり他研究室に依存しないシステムの購入がいいですね。候補を見ていくと、結局は研究目的で開発した物を配っている感が強いですね。気象計もそうでしたが。

**Comment by TatsukiWashimi** [comment]
まあこの付近での落雷の位置情報精度を高めてもらうというのもそれはそれで重要だと思うので、
ここのシステムで収集されたデータは湘南で使ってもらい(場所と電源とネット回線だけ貸す感じ)、
analog outputをこちら側で別途ADCしてKAGRAデータとして扱う。
とできれば話が早いと思います。

**Comment by TatsukiWashimi** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=9951
に挙げたように、VIS channelも雷に反応している。

**Comment by TatsukiWashimi** [comment]
![Screenshot from 2019-08-14 14-29-13](https://user-images.githubusercontent.com/18456905/62996554-0c2f9300-bea0-11e9-9305-553eea957d19.png)

**Comment by TatsukiWashimi** [comment]
Blitzortung.orgのセンサーの導入について、ファン小屋のケーブルネットを使用すれば宇宙線研での手続き等はいらないとのこと。

**Comment by TatsukiWashimi** [comment]
9/13(金)に湘南工科大学の方々が訪問。
検討段階は終わったので、このissueはcloseします。
