### ISSUE TITLE
portable測定用のUSBマイク選定

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#149]
chromebookを使ったportable pem用のマイクを選定する。
現在使っている鷲見私物のマイクはeleciomの[HS-EP13USV](https://www.elecom.co.jp/products/HS-EP13USV.html)というもので、
周波数帯域が100Hz～10,000Hzとのこと。

PCの内蔵マイクや3.5mmピンジャックを使用すると、ノイズが大きく較正値がデバイスに依存するので、USBマイクがよろしい

**Comment by TatsukiWashimi** [comment]
[https://www.amazon.co.jp/dp/B073JMV316/ref=psdc_2152017051_t1_B077Y974JF](https://www.amazon.co.jp/dp/B073JMV316/ref=psdc_2152017051_t1_B077Y974JF)

製品仕様：
感度：-30dB±3dB
指向性：無指向性
インピーダンス：≤2.2KΩ
感度範囲：1Vで-3dB以内
電圧：5V
周波数：20Hz〜25KHz
信号/ノイズ比：84dB
ケーブル長：1.5m
コネクタ：標準USB

**Comment by TatsukiWashimi** [comment]
[https://www.amazon.co.jp/dp/B077Y974JF/ref=psdc_2152017051_t1_B073JMV316](https://www.amazon.co.jp/dp/B077Y974JF/ref=psdc_2152017051_t1_B073JMV316)

主な仕様
型番：K053
指向特性：単一指向性
正面感度：-38～41dB
インピーダンス：≤680Ω
周波数特性：50～16,000Hz
消費電流：≤0.5mA
S/N比：≥56dB

**Comment by TatsukiWashimi** [comment]
(3) 単一指向性マイク。単一指向のものは50Hz以上などのものが多いが、これは20Hzから取れる
[https://www.amazon.co.jp/FIFINE-%E3%83%95%E3%82%A1%E3%82%A4%E3%83%95%E3%82%A1%E3%82%A4%E3%83%B3-%E3%82%B3%E3%83%B3%E3%83%87%E3%83%B3%E3%82%B5%E3%83%BC%E3%83%9E%E3%82%A4%E3%82%AF-%E3%83%9E%E3%82%A4%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89%E4%BB%98%E5%B1%9E-K669/dp/B01N122H2L/ref=sr_1_1_sspa?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=USB%E3%83%9E%E3%82%A4%E3%82%AF+%E5%8D%98%E4%B8%80%E6%8C%87%E5%90%91%E6%80%A7&qid=1561597159&s=computers&sr=1-1-spons&psc=1](https://www.amazon.co.jp/FIFINE-%E3%83%95%E3%82%A1%E3%82%A4%E3%83%95%E3%82%A1%E3%82%A4%E3%83%B3-%E3%82%B3%E3%83%B3%E3%83%87%E3%83%B3%E3%82%B5%E3%83%BC%E3%83%9E%E3%82%A4%E3%82%AF-%E3%83%9E%E3%82%A4%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89%E4%BB%98%E5%B1%9E-K669/dp/B01N122H2L/ref=sr_1_1_sspa?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=USB%E3%83%9E%E3%82%A4%E3%82%AF+%E5%8D%98%E4%B8%80%E6%8C%87%E5%90%91%E6%80%A7&qid=1561597159&s=computers&sr=1-1-spons&psc=1)

【スペック】
指向性：単一指向性
周波数特性：20HZ-20KHZ
感度：-34dB±30%（1kHz内）
負荷インピーダンス：≧1000Ω
S/N比：78dB
電流：3mA

**Comment by TatsukiWashimi** [comment]
(4) 同じく、20Hzから取れる単一指向性マイク。(3)より高いが高スペック
[amazon](https://www.amazon.co.jp/%E3%82%B5%E3%83%B3%E3%83%AF%E3%83%80%E3%82%A4%E3%83%AC%E3%82%AF%E3%83%88-%E3%80%90MFi%E8%AA%8D%E8%A8%BC%E3%80%91-Lightning%E6%8E%A5%E7%B6%9A-USB%E6%8E%A5%E7%B6%9A%E5%AF%BE%E5%BF%9C-400-MC010/dp/B06ZZG8P2T/ref=sr_1_27?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=USB%E3%83%9E%E3%82%A4%E3%82%AF+%E5%8D%98%E4%B8%80%E6%8C%87%E5%90%91%E6%80%A7&qid=1561597159&s=computers&sr=1-27)

＜仕様＞
■マイクサイズ：W42×D42×H108mm
■重量：約184g
■形式：バックエレクトレット・コンデンサータイプ
■指向性：単一指向性
■周波数特性：20～20,000Hz
■インピーダンス：2.2KΩ
■サンプリング周波数：96kHzまで
■ビット数：24bit
■動作電圧：USB DC5V、Lightning DC3.3V
■インターフェース：micro-HDMI
■付属品：スタンド、Lightningケーブル（約1.5m）USBケーブル（約1.5m)

**Comment by TatsukiWashimi** [comment]
(5) 単一指向性で、見てくれが(1),(2)に似たもの。50Hz以上
[amazon](https://www.amazon.co.jp/FIFINE-%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%82%AB%E3%83%BC%E3%83%89%E4%BB%98%E3%81%8D-%E3%82%A4%E3%83%A4%E3%83%9B%E3%83%B3%E7%AB%AF%E5%AD%90%E4%BB%98%E3%81%8D-%E3%82%B3%E3%83%B3%E3%83%87%E3%83%B3%E3%82%B5%E3%83%BC%E3%83%9E%E3%82%A4%E3%82%AF-K053/dp/B077Y974JF/ref=sr_1_4?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=USB%E3%83%9E%E3%82%A4%E3%82%AF+%E5%8D%98%E4%B8%80%E6%8C%87%E5%90%91%E6%80%A7&qid=1561597159&s=computers&sr=1-4)

主な仕様
型番：K053
指向特性：単一指向性
正面感度：-38～41dB
インピーダンス：≤680Ω
周波数特性：50～16,000Hz
消費電流：≤0.5mA
S/N比：≥56dB

**Comment by TatsukiWashimi** [comment]
昨日(2),(4),(5)を1つづつ発注しました。
合計税込  6,774円 です。
月曜に納品されます。

**Comment by yokozawa1985** [comment]
なぜか(4)だけ届いていました。

**Comment by TatsukiWashimi** [comment]
全て届いたのでcloseします
