### ISSUE TITLE
IMCのノイズバジェットの作成

### ISSUE THREAD

**Issue by TTanakaTT** [gw-pem/kagra-pem#15]
## 目的／目標
IMCのノイズバジェットの作成
## ToDo
- [ ] IMCのブロック図を作る
- [ ] 主要チャンネルからターゲット信号への寄与をプロットしてノイズバジェットを作る
- [ ] ターゲット信号の大きさがkagraの要求値を満たしているか確認

**Comment by MiyoKouseki** [comment]
目的はどういうものですか。
どういうことをするために必要とか、そういう背景が書いてあるとコメントしやすいです。

**Comment by yokozawa1985** [comment]
まずは、もっと古いissueを片付けてから行う、か、そもそもIMCのノイズバジェットをPEMがやるのか？acoustic injectionをしてcoupling functionを求める程度までしかできないのではないか？
返答願います。T田中さん

**Comment by TTanakaTT** [comment]
IMCと外部環境との関係を調べるというためとPEMモニターの設置場所の評価のために、ノイズバジェットの作成を行おうと思っています。
ただし、そもそもノイズバジェットの作成がPEMにとって妥当な仕事なのか、具体的にどこまで妥当な結果を出しえるのかというのは考えていませんでした。
音響ノイズなどとのコヒーレンスから誤差を評価して、ターゲット信号への寄与を評価できればノイズバジェットが作れるのでは、ぐらいの軽い見通しでした。

**Comment by yokozawa1985** [comment]
ノイズバジェットというと、鏡の制御ノイズや、レーザーノイズ、地面振動やPDなど様々な物を総合的に調べてノイズバジョエットと言えます。
田中さんのはノイズカップリング調査ですね、そこはぜひやるべきでしょう！

**Comment by MiyoKouseki** [comment]
Openしてから1ヶ月以上経っていますが、具体的に進んでいないようなのでCloseします。
