### ISSUE TITLE
KEK地震計を用いた加速度計較正

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#151]
### 目的　（なぜそれをやりたいのか、）

PEMで使用しているそれぞれの加速度計の測定限界を、KEKの地震計(都丸さんが貸してくれた)を使って測定する。
また、絶対値の較正値についてもチェックする。

### ToDo　(どうすればIssueをCloseできるか)
 - [x] 1. KEK地震計の動かし方を教わる
 - [x] 2. TEAC710の較正
 - [x] 3. TEAC706の較正
 - [ ] 4. KISTLERの較正
 - [ ] 5. USB加速度計の較正
 - [ ] 完了。Klogに投稿

### レビュー用まとめ　（ToDoが終わっているかどうか簡潔に示す）
1. NS軸が壊れていた。V, EW軸は使えた。 
2. 
3. 
4. 
5.

**Comment by TatsukiWashimi** [comment]
KEK地震計(V軸)の信号をKAGRAのADCで測ったスペクトル
![KEKseis_test](https://user-images.githubusercontent.com/18456905/60794895-aa478380-a1a5-11e9-8943-a67f494c640b.png)

アンプなしでは1-20Hzあたりがノイズに埋もれているが、10倍と100倍にアンプしたものを比べるとちゃんと10倍されている。

**Comment by MiyoKouseki** [comment]
IXVの地震計とのコヒーレンスはどうですか？

**Comment by TatsukiWashimi** [comment]
@MiyoKouseki この時は見てなかったです。
明日、IXC振動測定の際に加速度計較正をしてみようと思うので、その時に見てみます。

**Comment by TatsukiWashimi** [comment]
本日、SR3の近くでKEK地震計とTEAC710, 706の同時測定を行った。

KEK地震計(CMG-3T) の較正値は、2000V/(m/s)で、さらにアンプで100倍増幅。
TEAC加速度計は、SA11に3桁の較正値を入れ、Lに設定(100倍アンプ)。

digital filterは以下
![Screenshot 2019-07-19 at 16 23 21](https://user-images.githubusercontent.com/18456905/61525608-b956ed00-aa53-11e9-8ace-f9a4c7bfb42a.png)
![Screenshot 2019-07-19 at 16 23 46](https://user-images.githubusercontent.com/18456905/61525613-bd830a80-aa53-11e9-838d-75069dcb7dfb.png)
![Screenshot 2019-07-19 at 16 23 53](https://user-images.githubusercontent.com/18456905/61525624-c1af2800-aa53-11e9-8438-d7448ca292e5.png)
![Screenshot 2019-07-19 at 16 23 59](https://user-images.githubusercontent.com/18456905/61525632-c5db4580-aa53-11e9-8eef-436d3a9e1a93.png)
![Screenshot 2019-07-19 at 16 24 30](https://user-images.githubusercontent.com/18456905/61525641-ca076300-aa53-11e9-9544-6b9449d237c1.png)
![Screenshot 2019-07-19 at 16 24 36](https://user-images.githubusercontent.com/18456905/61525649-cd9aea00-aa53-11e9-95ca-3e0f2a1ca117.png)

**Comment by TatsukiWashimi** [comment]
そのまま取ったデータ
![Screenshot 2019-07-19 at 18 49 47](https://user-images.githubusercontent.com/18456905/61526976-6468a600-aa56-11e9-95be-0594b318e91c.png)

- 左上：KEK地震計のスペクトル
- 左下：加速度計のスペクトル
- 右上：KEK地震計と、近くに常設されているBS地震計のcoherence
- 右下：KEK地震計のと加速度計、および加速度計同士のcoherence

**Comment by TatsukiWashimi** [comment]
大スピーカーでホワイトノイズを入れた結果
![Screenshot 2019-07-19 at 19 11 54](https://user-images.githubusercontent.com/18456905/61528215-2ae56a00-aa59-11e9-935e-0e6612db1975.png)

**Comment by TatsukiWashimi** [comment]
100Hzの音を入れた場合
![Screenshot 2019-07-19 at 19 06 01](https://user-images.githubusercontent.com/18456905/61528248-3df83a00-aa59-11e9-8637-0a3d9e2031c7.png)

**Comment by TatsukiWashimi** [comment]
近くで飛び跳ねた場合

![Screenshot 2019-07-19 at 19 10 30](https://user-images.githubusercontent.com/18456905/61528283-51a3a080-aa59-11e9-8c40-4c259d1fea03.png)

**Comment by TatsukiWashimi** [comment]
TEAC710 : 5.9e-4 m/s2/rtHz
TEAC706 : 1.5e-4 m/s2/rtHz

**Comment by TatsukiWashimi** [comment]
SA-11の説明書を読んで整理すると、
例えば較正値が 5.74mV/ms-2 だった場合、SA-11の設定を 
- 「574L」にしたとき 1m/s2 = 1V
- 「574M」にしたとき 1m/s2 = 0.1V , 10m/s2 = 1V 
- 「574H」にしたとき 1m/s2 = 0.01V, 100m/s2 = 1V 
となる。

これを参考にすると、
較正値が 10.2 mV/m/s^2 のとき、「102H」にすると 1m/s2 = 0.1V , 10m/s2 = 1V 
較正値が  311 mV/m/s^2 のとき、「311H」にすると 1m/s2 = 1V
 である。
すなわち、TEAC706ではアンプのゲインは10倍、TEAC710では1倍であった。

**Comment by TatsukiWashimi** [comment]
TEAC706
![TEAC_100Hz_GainMod](https://user-images.githubusercontent.com/18456905/61617723-45605300-aca6-11e9-85be-5c224ccba84e.png)
![TEAC_GainMod](https://user-images.githubusercontent.com/18456905/61617889-92442980-aca6-11e9-8007-62b45ed4c3d5.png)

**Comment by TatsukiWashimi** [comment]
地震計の100Hzピークの大きさは3.68e-6 m/s
これに2πf = 628を掛けて加速度にすると、2e-3 m/s2
TEAC加速度計のどちらともfactorだけ違っている。

**Comment by TatsukiWashimi** [comment]
KEK

![100HzPeak_withKEK](https://user-images.githubusercontent.com/18456905/61621586-2e256380-acae-11e9-984d-cbaa144b5ed1.png)

**Comment by TatsukiWashimi** [comment]
100Hzピークの高さが地震計と一致するように、TEACのスペクトルを定数倍する。

- TEAC710 :  1.99e-3/5.91e-4 = 3.37倍
- TEAC706 :  1.99e-3/1.46e-3 = 1.36倍

**Comment by TatsukiWashimi** [comment]
KEK地震計(CMG-3T)の仕様書を見ると、感度帯域は50Hz以下とのことなので、40Hz injectionデータを見てみた。
特にnormalizeせず、スペックシートの較正値を信じてそのままplotした結果が以下。
![Screenshot from 2019-07-23 10-36-03](https://user-images.githubusercontent.com/18456905/61676202-0d085580-ad36-11e9-901d-a5d879b145c8.png)
![Screenshot from 2019-07-23 10-41-11](https://user-images.githubusercontent.com/18456905/61676324-6ff9ec80-ad36-11e9-9511-d84d81057fb2.png)

TEAC710 : 5.95e-6
地震計 : 5.86e-6
かなりよく一致している

TEAC706はセンサーノイズに埋もれてしまっている様子。

**Comment by TatsukiWashimi** [comment]
以上より、地震計を信じた場合の絶対値較正は、
- TEAC710 : なし (1倍)
- TEAC706 : 0.41倍
となる。

**Comment by TatsukiWashimi** [comment]
injectionなしの、TEAC710と地震計の比較(zoom)
![Screenshot from 2019-07-23 15-39-08](https://user-images.githubusercontent.com/18456905/61688495-232b0b80-ad60-11e9-97a2-b2aae13b73e7.png)

**Comment by TatsukiWashimi** [comment]
この測定では音をinjectionしたため、本当に振動のキャリブレーションができたのか怪しい。
特にTEAC710と706の比など。

後日shakerでもやろう

**Comment by yokozawa1985** [comment]
早い段階で、完了して、IYC付近に置いてみる？それとももう返してしまった？

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 temporaryな用途としてはいつでも好きに使っていいけど、常設用にはしないでくれとのことでした

**Comment by yokozawa1985** [comment]
了解しました。加振実験を別issueで議論しましょう。
