### ISSUE TITLE
PEM list, JGWdocのMICの情報が間違ってるっぽい

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#153]
**問題について** 何が問題か書いてください
PEM listで、IXC, IYX EXC, portable のMICのキャリブレーション値が同じ値になっている。
![Screenshot 2019-07-13 at 20 45 00](https://user-images.githubusercontent.com/18456905/61171214-73aba780-a5af-11e9-9bac-58511b84e3c9.png)

JGWdocでS1809321とS1809322が両方ともIXCにあることになっている。

**正しい状態** どうなっているべきか書いてください

現実に即した情報にする

完了したら、Klogに投稿！

**Comment by TatsukiWashimi** [comment]
現物確認

IYCマイク：S1809322
![20190719_103511648](https://user-images.githubusercontent.com/18456905/61503039-3745d480-aa11-11e9-93bf-88a9f66449a6.jpg)

**Comment by TatsukiWashimi** [comment]
IYCマイク：S1809321
![20190719_103902701](https://user-images.githubusercontent.com/18456905/61503188-cbb03700-aa11-11e9-8932-8b9c774f77cb.jpg)

**Comment by TatsukiWashimi** [comment]
S1809322のDB infoを IXC->IYC と修正しました。
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9322

**Comment by yokozawa1985** [comment]
ありがとうございます。
