### ISSUE TITLE
chromebook+全方位マイクのコンビでの周波数

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#157]
**問題について** 何が問題か書いてください
chromebook+全方位マイクのコンビネーションで周波数の表示が怪しかったので調べてみた。
youtube音源とchromebookに入っているファンクションジェネレータで確認した。
300Hz->307Hz
600Hz->612Hz
900Hz->919Hz
1800Hz->1837Hz
3000Hz->3063Hz
見事に~2%高くなっている。

**正しい状態** どうなっているべきか書いてください
chromebookと他のマイク
chromebookの他のspectral analyzer
chromebookを用いない測定
を行うことでoffset源を把握しておく。
把握できなかったら2%を考慮に入れて調べる。
(そういえば、450Hzのバキュープポンプも高めの周波数で出てたな。)

完了したら、Klogに投稿！

**Comment by yokozawa1985** [comment]
chromebookの内蔵マイクだとそのようなことが生じないため、
おそらくUSBマイクの問題。
DACのclockに誤差が大きいのかもしれない。

**Comment by yokozawa1985** [comment]
しかも、全方向マイクのみらしい。
指向性マイクではそのような問題は観測されなかった。
鷲見さんが追加購入したマイクのチェックも行っていただきたい。
(youtube or chromebook sound generatorで十分。)

**Comment by TatsukiWashimi** [comment]
この安物全方位マイク(磁束計に使っているもの)の基板を見ると、裏側にチップがあり、
「AKM AK5371AVQ」と書かれています。
旭化成エレクトロニクス株式会社のADCだそうです。
http://www.hkchipsource.com/chips/akm-semiconductor/AK5371AVQ.html

**Comment by TatsukiWashimi** [comment]
基板だけでスペクトルを見ると、
1020Hz, 2039Hz, 3070Hz, 4078Hz, ...といったピークが見えます。
![20190808_162137827](https://user-images.githubusercontent.com/18456905/62684760-57f3bf80-b9fc-11e9-842d-ca441db37a72.jpg)

signalとgroundを短絡するとこれらのピークは小さくなり、1kHzのみが見えるようになります。

**Comment by yokozawa1985** [comment]
あとで、発信器の周波数調べてみましょう。

**Comment by yokozawa1985** [comment]
ありがとうございます。
とりあえず、周波数に気をつけるということでcloseしておきます。
