### ISSUE TITLE
Virgo訪問計画

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#158]
### 目的　（なぜそれをやりたいのか、）
10月のcommissioning breakにVirgoに行き、Noise huntingの練習(鷲見)および地面振動測定(三代)を行う。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 作業内容を決める
 - [x] 2. 航空券の予約
 - [x] 3. 宿の予約
 - [ ] 4. その他、先方とのやり取り
 - [ ] 5. 荷造り

### レビュー用まとめ　（ToDoが終わっているかどうか簡潔に示す）
1. 
2. 
3. 
4. 
5.

**Comment by TatsukiWashimi** [comment]
10/1~10/14のプランの周辺で航空券代を調べた。条件は
 - 東京 <--> ピサ
 - 乗り継ぎ1回まで、6時間以下
 - 18万円以下
![Screenshot 2019-07-24 at 09 04 35](https://user-images.githubusercontent.com/18456905/61755550-1b687700-adf3-11e9-84ca-9eb7c74b777f.png)
![Screenshot 2019-07-24 at 09 05 01](https://user-images.githubusercontent.com/18456905/61755553-1f949480-adf3-11e9-9bd4-d379ad181f34.png)
![Screenshot 2019-07-24 at 09 07 13](https://user-images.githubusercontent.com/18456905/61755583-4b177f00-adf3-11e9-9f58-e012ef562ebf.png)

**Comment by TatsukiWashimi** [comment]
Federicoさんから返信があった。要約すると、

- Virgo側では、10月の間は1ヶ月間いつでも受け入れ対応可能。こちらの自由に日程を決めて良い。
- コミッショニング作業の予定はまだ決まっておらず、したがってPEM作業の予定も決まっていない。
- 国際免許を取っておくのがオススメ
- Virgoの最寄りの宿泊施設 : https://goo.gl/maps/meFd2F2164Cr56sQ9
- この宿泊施設は多くの人が使うので、日程を決めたら相談する。
- 空港は近い順に、ピサ、フィレンツェ、ローマ

**Comment by TatsukiWashimi** [comment]
おすすめされたホテル(Agriturismo La Regina)を調べてみると、1泊9000円弱
![無題](https://user-images.githubusercontent.com/18456905/62182333-386fed80-b391-11e9-8c60-b0f70e6d85b6.png)

**Comment by yokozawa1985** [comment]
僕が2月に泊まったホテルは以下です。
ホテルラパーチェ Hotel La Pace

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 Virgoからはちょっと離れてますね。観光には良さそうです
![Screenshot 2019-08-01 at 11 21 05](https://user-images.githubusercontent.com/18456905/62260894-8eef3180-b44e-11e9-95a9-0b5234fb549c.png)

**Comment by TatsukiWashimi** [comment]
10/1の朝から作業を開始したいので、
- 入国とホテルチェックイン
- Virgoで動くための手続き
- デジタルシステム・ソフトウェアの使い方を教わる
などは9/30に済ませたい。
9/29に到着するスケジュールが良いか

**Comment by TatsukiWashimi** [comment]
![FireShotCapture001](https://user-images.githubusercontent.com/18456905/62269771-1187e900-b46f-11e9-805e-0456f86f82de.png)

**Comment by TatsukiWashimi** [comment]
運転に関しては、ハーツレンタカーを使うのが良さそう
https://kohey55.com/international_drivinglicense/

**Comment by TatsukiWashimi** [comment]
![ハーツレンタカー](https://user-images.githubusercontent.com/18456905/62272644-801c7500-b476-11e9-9c12-89eacb0e7cd2.png)

698.95 ユーロ は 84,252.48 円
8月1日 7:03 UTC

**Comment by TatsukiWashimi** [comment]
ざっくり、
- 航空券 14万円
 - ホテル 11万円
- 車 8.5万円

**Comment by TatsukiWashimi** [comment]
付近のスーパーマーケット
![Screenshot 2019-08-01 at 17 18 57](https://user-images.githubusercontent.com/18456905/62277146-7ef04580-b480-11e9-9f7f-d583e716464f.png)

レストランは遠い
![Screenshot 2019-08-01 at 17 20 21](https://user-images.githubusercontent.com/18456905/62277233-b0691100-b480-11e9-9827-bd0263e2a56f.png)

**Comment by TatsukiWashimi** [comment]
Federicoさんとのメールの要約

1. 9/29に到着、9/30にinstructionを受け、10/1から作業開始 の予定でOKか？
   - "it is perfect."
   - 「10/20くらいまでいてもいいよ」とのこと
2. 次のVK PEM meeting (8/20)に、commissioning break でやろうとしているPEMの仕事をざっくりリストしてもらえることになった。
3. レンタカーについて
   - フライト疲れもあるだろうから、到着日はタクシーでホテルに行き、翌日から車を借りるのがオススメ。
   - もしかしたら、Virgoの公用車を無料で貸してもらえるかもしれない。確認してくれる。
   - レンタカーを借りるときは、保険付きのオプションをつけるのを勧める。
4.

**Comment by TatsukiWashimi** [comment]
Virgoの公用車は全てマニュアル車らしく、私は運転できない。
レンタカーを借りる

**Comment by TatsukiWashimi** [comment]
"tourist" SIM card を買うと便利らしい。TIMというのがオススメとのこと。

https://www.tim.it/tim-tourist-en
- 30 Euros (~ 3600円)で1ヶ月使用可能 
- 15GB
- 200分の通話

**Comment by TatsukiWashimi** [comment]
8/20のmeeting page
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Meeting/190820/Agenda

**Comment by TatsukiWashimi** [comment]
杉本くん参加

**Comment by TatsukiWashimi** [comment]
杉本くんの飛行機
<img width="831" alt="スクリーンショット_ 2019-08-31 15 42 36" src="https://user-images.githubusercontent.com/18456905/64098886-f2001b00-cda2-11e9-90ea-1cf9810522d2.png">

**Comment by TatsukiWashimi** [comment]
宿はHotel Galileiを予約した。
https://www.hotelgalileipisa.it/en/

**Comment by yokozawa1985** [comment]
計画自体は完了したと思いますので、close。
具体的な作業計画は別issueにて。
