### ISSUE TITLE
seismonのインストール

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#16]
## 目的
Coughlin氏のseismonをインストールして遠地地震の速報をkagraサイトに送る。
これは5分毎にUSGSの地震速報をみて、サイトにどれぐらいの大きさでいつ届くかを予想するためのシステム。

## ToDo
- [x] とりあえずMacbookにインストールしてみる。
- [x] Ctr計算機にseismonをインストールして到達時刻の計算をできるようにする
- [ ] Epicsチャンネルを作る
- [ ] 到来時間の計算が物理的に正しいか確認。
- [ ] guardianを作る
- [ ] 完了

**Comment by MiyoKouseki** [comment]
そういえばwatchdogの閾値ってそろそろ決めてもいい気がする。その値に応じて、制御を切るかどうかのフラグをseismonのguardianに出してもらうのがgoodだと思う。

そこらへんを整理したい。

**Comment by yokozawa1985** [comment]
k1sum0に入れるのはなんで？

**Comment by MiyoKouseki** [comment]
http://gwclio.icrr.u-tokyo.ac.jp/lcgtsubgroup/detectorcharacterization/2018/11/seismon-installation-1.html

の苔山さんのworkに基づいてます。

たしかgwpy依存だったからなきがします。

sum0の負担を増やしたくないのでほかのマシンでやるのがいいかもしれません。
k1script？

**Comment by neouniverse** [comment]
bcstからデータを受け取る事は現状DMTを導入することと同義なので慎重に検討する必要があると思う
あと計算機室は狭いのでラックマウント型だけにしたい。
時間が取れなくてやってないけどk1ctr13もいずれはラックマウントか
スペック気にしないならNUCとかにするつもり。

今はk1scriptが1台しかないけどこれを複数台にする計画は一応ある。
LIGOはl1scriptが4台くらいあったと思う。
たぶん各サブシステムが好き勝手に計算機を用意してCDS内に入れ始めると収集つかなくなるので
出来るだけ汎用計算機という形でIPをアサインしたい。

sum0も既にスペック不足が露呈し始めていてたぶんもうちょっといい計算機が必要。
なのでsum0も現状は色々LVツールを試す汎用機(テスト機)という使い方でいいと思う。

もちろんseismonがそれなりの計算機を占有しないと処理しきれないとかなら
1台専用機を作る事を止めたりはしませんが、まだ様子見段階だと思うので
とりあえずどこでもいいから一度動かしてみるでいいのでは？

**Comment by MiyoKouseki** [comment]
すでにMacbookにはインストールして、到来時刻の計算等はできます。

SeismonのWebページ出力であるTerramonで表示すると、こんな感じです。
http://www.icrr.u-tokyo.ac.jp/~miyo/seismon/html_pages/earthquakes.html

**Comment by MiyoKouseki** [comment]
物理的に合っているかどうかはこれから確かめないといけないです。

まだK1はありませんが、K1の座標をいれたら到来時刻は求まります。
しかし肝心の「どれぐらい揺れるか」という評価は、過去の地震とサイトの地震計に基づいた教師データが必要な感じです。

一応「動かす」という意味では、LHOのデータがあるので、それを仮に使えば上述のサイトのように計算できます。

自分としてはKAGRAの実際のデータをつかって評価したいところです。これは違うIssueにしておきます。

**Comment by MiyoKouseki** [comment]
> 1台専用機を作る事を止めたりはしませんが、まだ様子見段階だと思うので
> とりあえずどこでもいいから一度動かしてみるでいいのでは？

@neouniverse 
k1ctr7でいいですか？

**Comment by kokeyama** [comment]
計算機、２台発注ちゅうです。１月中旬到着予定、3.6G, 6 core です。(k1sum0程度？) 1台は、ligo DV web に使う予定だけど専用機っていうわけじゃないです。もう一台は用途未定（募集中）です。

あとSeismonはsuspensionというより、メイン干渉計のロック中、ノイズハンティング中、観測中に役に立つイメージです（地震が来てまずい制御の設定とかあれば変更するとか）

**Comment by yokozawa1985** [comment]
すみません、k1bcstに関しては知識不足でした。無視してください。

**Comment by MiyoKouseki** [comment]
Debian9のk1ctrZZにSeismonをいれました。
それにともなってPython3でGwpyが動く環境をつくりました。
一応いくつかの基本的なGwpyのスクリプトが動くことが確認されています。 （Issue : #90 ）

インストールメモはこちらになります。
ディレクトリはMacbook用なので，読み替えが必要になります。
あとでちゃんとしたインストール手順を載せます。
https://www.evernote.com/shard/s36/sh/736ea947-6b43-4567-a048-61e467e1baad/fbf84520a73c2f3d9ad702e8828f3c42

**Comment by yokozawa1985** [comment]
ありがとうございます。
seismonのインストールは完了したということで一旦closeにしておいて、next stepは新たなissueでお願いします。
