### ISSUE TITLE
ネットワークスイッチ・電源ノイズ測定

### ISSUE THREAD

**Issue by shoichioshino** [gw-pem/kagra-pem#160]
鷲見さんにChrome bookを借りてネットワークスイッチとDC電源のノイズ測定を行った。

- DC電源
![DC_power_supply](https://user-images.githubusercontent.com/23567378/62109320-fee2a800-b2e6-11e9-906f-c4ba915cbc4c.png)

- ネットワークスイッチ（未対策）
1. 電源付近
![switch_power](https://user-images.githubusercontent.com/23567378/62109390-29346580-b2e7-11e9-9be5-8741188a08b2.png)
1. LANポート付近
![switch_port](https://user-images.githubusercontent.com/23567378/62109414-36e9eb00-b2e7-11e9-8faf-95cd002374a5.png)

- ネットワークスイッチ（ノイズ対策）
1. 電源付近
![improve_switch_power](https://user-images.githubusercontent.com/23567378/62109476-597c0400-b2e7-11e9-932b-d44e41cba81a.png)
1. LANポート付近
![improve_switch_port](https://user-images.githubusercontent.com/23567378/62109496-6567c600-b2e7-11e9-9077-9ebb3c0196e0.png)

霜出さんがノイズ対策したスイッチはLANポート周りのノイズが減少しているように見える。
ただし通信や周りの環境は揃えていない。
今後、霜出さんが電源周りの対策も行うそうなので、その後再度測定する。

**Comment by TatsukiWashimi** [comment]
@shoichioshino これですか？
http://gwclio.icrr.u-tokyo.ac.jp/lcgtsubgroup/electronics/LAN_hub_noise_prevention_method.pdf

**Comment by shoichioshino** [comment]
はい、そうです。

**Comment by shoichioshino** [comment]
このissueはcloseとする。
