### ISSUE TITLE
センサーの較正値をonline model上で実装する

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#161]
**改善案**
どのように改善してほしいか書いてください。

現状、全てのPEMセンサーの較正値 (count -> Volt, Volt -> physical unit, amp, ...) をfilter bankで入れているが、ほとんど(WFを使っている磁束計以外)は単なる定数倍だし、常設センサーは固定されているので、online model上で較正してしまった方が良いのではないかという説がある。
そうすることで、データサイズも節約できるらしい。

また、portable channelは全て最初からVoltになっていた方が、余計な手間・混乱を避けられる。
(Dsub-BNC converterで1/2倍するところとか) 
その上で、filter bankに各センサーの典型的な較正値 (300mV/(m/s2) for TEAC710 など)を登録しておけば、使い勝手も良くなるのでは。

どこかのタイミングで一斉にやりたい。

**Comment by yokozawa1985** [comment]
少なくともO3までは固定で、calibration値をいじらないところはモデルに組み込んでもいいと思います。
ただ、本来もっとちゃんとresponse functionを入れたほうがいいPEM(TEAC710の高周波とかACO micの低周波とか)は実在するのが事実です。

**Comment by TatsukiWashimi** [comment]
オンラインモニター上でどこまでやる必要があるか要検討ですね。
解析するときに考慮すればいいという見方もある反面、PEM以外の人達に使いやすいように補正しておくべきとも考えられます。

あとは、単位換算のようなtrivialなことはモデル上でやってしまって、伝達関数だけfilter bankで対処するというのもすっきりするかと

**Comment by imyukino** [comment]
今日確認したPEM-PortableChannnelのメモです。
![190809-portablech](https://user-images.githubusercontent.com/45890168/62774911-2e609400-bae1-11e9-82b0-66cc51a89297.jpg)

**Comment by TatsukiWashimi** [comment]
森さんのメモをもとに、GSSにまとめました。
https://docs.google.com/spreadsheets/d/17zcVqZKSC7GaK5Y1_Y0xoedsXjhBfbqMfxlXC_gJ4dY/edit?usp=sharing
![無題](https://user-images.githubusercontent.com/18456905/62993925-70e4f080-be94-11e9-92fd-b7e7fa54fc62.png)

channel nameは現状のものではなく、変更案です。
このように、抜き差しするポートの場所と番号を付けるのが良いかと思います。

**Comment by TatsukiWashimi** [comment]
あとは両エンドの確認。
それができたら、portable channel nameのre-asignと、count -> V換算をmodel上で実装したい。

**Comment by TatsukiWashimi** [comment]
endの確認結果を載せ忘れていた。
![Screenshot 2019-08-28 at 08 45 51](https://user-images.githubusercontent.com/18456905/63815672-810ace80-c970-11e9-80fb-4cc7e408d353.png)

**Comment by TatsukiWashimi** [comment]
#179 より、場合によってはローパスフィルターを入れる必要があるかも

**Comment by yokozawa1985** [comment]
こちら、とりあえずO3までは、filter bank体制でいきたい。

**Comment by yokozawa1985** [comment]
とりあえずclose
