### ISSUE TITLE
PCal Rx PDノイズハンティング@2nd Aug

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#164]
Xendのcryocoolerが止まったのでXendで色々したい。

**Comment by TatsukiWashimi** [comment]
森さんが撮ってくれた写真と測定場所まとめをgoogle photoにアップしました。
データは後日まとめます。
https://photos.app.goo.gl/Qc1aNx5pAxRYK3r1A

**Comment by TatsukiWashimi** [comment]
遅くなりましたが、結果をまとめました
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=10549

**Comment by yokozawa1985** [comment]
CAL Groupの指示を待った後、shakerとimpact hummerを持ってXendに再度いきましょう。
