### ISSUE TITLE
F2F-Poster

### ISSUE THREAD

**Issue by imyukino** [gw-pem/kagra-pem#168]
### 目的　
F2Fのポスター作成をここで議論しながら進めたいと思います。
### ToDo　
 - [x] 1. 仮題名決め
 - [x] 2. 日本語で大枠作成
 - [x] 3. 日本語で内容を細かく詰める
 - [x] 4. 英語になおす
 - [ ] 5. 印刷,完成

**Comment by imyukino** [comment]
題名は
・Proposal of noise search method for PEM
などどうでしょうか?

内容は主にchrome bookについて書こうと思っています。
1,centerエリア全体の音場測定をした。
2,そのなかで300Hzのノイズがあった。
3,chrome book(USB mic)を使って、ノイズ源(FFU)を見つけた。
4,chrome bookでできること、有用性について。
5,USBセンサーの紹介
6,chroom book(USB ACC)で測定したデータとADCを通してdiagguiで測定したデータの比較(差があまりないことを示す)
を書こうと考えています。

**Comment by yokozawa1985** [comment]
内容はそれでいきましょう。

タイトルは、ちなみに日本語で書くとしたらどういうタイトルになりますか？

**Comment by imyukino** [comment]
日本語だと、
PEMによるノイズハンティング方法の提供
です。
どうでしょうか?

**Comment by yokozawa1985** [comment]
それでしたら、
New noise search method by portable PEMs
でいきましょう。

**Comment by imyukino** [comment]
分かりました。
ありがとうございます。

**Comment by TatsukiWashimi** [comment]
@imyukino 
> 内容は主にchrome bookについて書こうと思っています。
1,centerエリア全体の音場測定をした。
2,そのなかで300Hzのノイズがあった。
3,chrome book(USB mic)を使って、ノイズ源(FFU)を見つけた。
4,chrome bookでできること、有用性について。
5,USBセンサーの紹介
6,chroom book(USB ACC)で測定したデータとADCを通してdiagguiで測定したデータの比較(差があまりないことを示す)
を書こうと考えています。

KIWのときに開発くんにも言いましたが、やったことの時系列で発表するのはあまりよくありません。
発表経験が少ないうちはやりがちですが、ロジカルな順番になるよう心がけましょう。
今回の場合は、

1. chrome bookでできること、有用性について。
2. USBセンサーの紹介
3. chrome book PEMの成果1 : 300Hzのノイズ源(FFU)を見つけた -> 卒論, KIWをrefer
4. chrome book PEMの成果2 : ER2(MICH)で見られた312.5Hzノイズ源の調査(真空ポンプ)
5. まとめと展望
6 . Appendix : chroom book(USB ACC)で測定したデータとADCを通してdiagguiで測定したデータの比較

という流れにするのが良いかと思います。

**Comment by imyukino** [comment]
鷲見さん、ご指摘ありがとうございます。
ざっくりですが大枠を作成しました。

<img src="https://user-images.githubusercontent.com/45890168/62926611-d59a3f80-bdef-11e9-95bd-b394bf545fd2.jpeg" width="500">

**Comment by TatsukiWashimi** [comment]
@imyukino
1と2は一緒にできると思います。
あと、それぞれのBoxの大きさと配置も、今の時点で実際のポスターを想定して配置していくのがいいでしょう。
写真やグラフも、暫定的でよいのでペタペタ貼っていくと完成形のイメージがつきます。

**Comment by TatsukiWashimi** [comment]
私のトークでは、
1. chamber/ductの振動測定
2. Chromebook PEM -> 詳細は森ポスター参照
3. Reverberation time測定
4. 雷

という流れにしようと思います。

**Comment by yokozawa1985** [comment]
コメントです。
1,2は鷲見さんのコメントの通り合わせていいと思います。
ADCやBNC-Dsub converter->USBでパソコンに入る前にADCがあります。
KAGRAのデータ取得系を使わなくても良い
バッテリー駆動により近くに電源がなくても使用出来る
コンパクトで複数箇所の測定が非常に容易

**Comment by yokozawa1985** [comment]
Washimiさん
Xend PCal RxPDの測定も追加しておいてください。

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 1.の振動測定の一部に入れるつもりです。

**Comment by yokozawa1985** [comment]
OKです。

**Comment by imyukino** [comment]
横澤さん、鷲見さん
ご指摘ありがとうございます。
ポスター日本語で作成しました。
画像やグラフはまだ追加や訂正すると思いますが、このような感じで作成したいと思います。
再度ご確認、ご指摘お願いします。
遅くなりすみません。
<img src="https://user-images.githubusercontent.com/45890168/63212153-20db8780-c13b-11e9-849c-572f809e1c87.jpeg" width="500">

**Comment by TatsukiWashimi** [comment]
@imyukino 概ね良いと思います。
5. の「ピークやノイズフロアの形がほぼ一致しており、ゲインのオーダーも一致した」という結論ですが、これは言いすぎです。
目盛りがよく見えないですが、高周波での構造なんかは合っていません。(センサーもADCの帯域も違うので当然といえば当然)
縦軸についても、androidアプリの方はおそらくマイクを想定した音圧レベル (20uPaを基準にしたdB)で、ちゃんと加速度計に対するキャリブレーション値が入っているわけではないので、絶対値に意味はありません。(合っていたとしても偶然)
あくまで、ピークサーチと、場所ごとの相対的な比較ができるということに留めるべきです。

**Comment by TatsukiWashimi** [comment]
@imyukino 
ポスター会場にChromebookとUSBセンサーを置いて、測定のデモンストレーションを行うというのはどうでしょうか。
ポスターやスライドでは実感として伝わりにくい便利さも感じてもらえるので

**Comment by imyukino** [comment]
鷲見さんご指摘ありがとうございます。
5について訂正を加え、英語にしました。
会場にChromebookとUSBセンサーを置くのは賛成です。
持ってきていただけると嬉しいです。
![F2F-poster](https://user-images.githubusercontent.com/45890168/63222094-e2e36f80-c1dd-11e9-9184-f151c597558a.jpeg)

**Comment by imyukino** [comment]
1min talkに使用するスライドを鷲見さんのスライドを参考に作成しました。
発表時の文章は、

I will introduce a simple noise search method recently used by PEM.
It is a chrome book.
Chromebook is light and convenient to carry.
In addition, it is possible to measure anywhere environmental noise for wiring work is not required.
Chromebook measures environmental noise using USB port sensors such as microphones, accelerometers, and magnetometers.
This poster summarizes noise hunting using a chrome book.

でどうでしょうか？
もっとポスター内容について触れたほうが良いでしょうか？

@TatsukiWashimi ラックの前でUSB磁束計を使用している写真が欲しいです。

![1min-talk 001](https://user-images.githubusercontent.com/45890168/63222561-9d767080-c1e4-11e9-8c3f-ad3d3986f815.jpeg)

**Comment by TatsukiWashimi** [comment]
@imyukino 
chromebookとセンサー一式を持っていくので、机の調達をお願いします。
あと、適当なノイズ源(サーキュレーターかなんか)もあると良いです。

1 min talkは短くてインパクトがあるほうが良いので、むしろもっとコンパクトにしてもいいくらいだと思います。
四の五の言わず、実際にデモンストレーションしてるから是非来てねというメッセージをガツンと伝えるのがいいかな。

**Comment by TatsukiWashimi** [comment]
@imyukino 
磁束計を使ってる写真
![20190710_101141552](https://user-images.githubusercontent.com/18456905/63222777-1b3b7b80-c1e7-11e9-96e7-d4387ce19ec3.jpg)
![20190710_103131894](https://user-images.githubusercontent.com/18456905/63222785-2f7f7880-c1e7-11e9-82d6-c26cdc268b49.jpg)

他の良さげな写真
![20190802_104350801](https://user-images.githubusercontent.com/18456905/63222789-3ad2a400-c1e7-11e9-9a19-33d6353ab024.jpg)
![20190702_160710130](https://user-images.githubusercontent.com/18456905/63222794-3dcd9480-c1e7-11e9-9285-7c956866f42c.jpg)
![20190628_110413562](https://user-images.githubusercontent.com/18456905/63222811-6bb2d900-c1e7-11e9-8695-5ccef1dd3738.jpg)

**Comment by TatsukiWashimi** [comment]
![_MG_0914_2](https://user-images.githubusercontent.com/18456905/63222836-b6ccec00-c1e7-11e9-8799-f8f4f609d870.jpg)

**Comment by imyukino** [comment]
鷲見さん
机は準備できそうです!  サキュレーターはぱっとないので探してみます。
なかったら扇風機を家から持って来ようと思います。

頂いた写真をポスターに追加し、1min talkもシンプルに改善しました。
1min talkの原稿は、

I will introduce a simple noise search method recently used by PEM.
It is a chrome book.
Chromebook is light and convenient to carry.
In addition, it is possible to measure anywhere environmental noise.
Chromebook measures environmental noise using USB port sensors such as microphones, accelerometers, and magnetometers.
This poster summarizes noise hunting using a chrome book.
I bring a chrome book today,please come to test the chrome book in front of the poster!

でどうですか?


[F2F-poster.pdf](https://github.com/gw-pem/kagra-pem/files/3514050/F2F-poster.pdf)
[1min-talk.pdf](https://github.com/gw-pem/kagra-pem/files/3514049/1min-talk.pdf)

**Comment by yokozawa1985** [comment]
すみません、コメント遅くなりました。
今からコメント書きます。

**Comment by yokozawa1985** [comment]
添付します。
こういうポスターは文章で説明しようとするよりも、箇条書きの方が楽だし周りの方に読んでもらいやすいですよ。あと、強調したいところに色を使うのがいいでしょう。

**Comment by yokozawa1985** [comment]
[F2F-poster_TYcheck.pdf](https://github.com/gw-pem/kagra-pem/files/3515044/F2F-poster_TYcheck.pdf)

**Comment by imyukino** [comment]
横澤さん
ご指摘ありがとうございます。訂正しました。
文章が多いのが気になるのでもっと簡潔化したほうがいいですか?

[F2F-poster-2.pdf](https://github.com/gw-pem/kagra-pem/files/3518444/F2F-poster-2.pdf)

**Comment by yokozawa1985** [comment]
めっちゃ良くなったじゃん！

**Comment by imyukino** [comment]
これを最終盤として明日印刷しようと思います。

・f2fポスター
[F2F-poster.pdf](https://github.com/gw-pem/kagra-pem/files/3519673/F2F-poster.pdf)

・1min-talkスライド
[1min-talk.pdf](https://github.com/gw-pem/kagra-pem/files/3519672/1min-talk.pdf)

**Comment by TatsukiWashimi** [comment]
内容はいいと思います。
ポスターとしてのレイアウト(文字や写真の場所、大きさ、空白)にまだまだ改善の余地があると思うので、余裕があったらもう少し頑張ってみてください

**Comment by imyukino** [comment]
がんばります!

**Comment by imyukino** [comment]
鷲見さん、横澤さん
ポスター完成しました!
アドバイス、ご指摘ありがとうございました!
横澤さんにOK頂いたので印刷します!

[F2F-poster.pdf](https://github.com/gw-pem/kagra-pem/files/3524427/F2F-poster.pdf)

**Comment by yokozawa1985** [comment]
お疲れ様です。反響大きくて嬉しいです。
closeします。

**Comment by yokozawa1985** [comment]
ポスター賞、おめでとうございます！

**Comment by imyukino** [comment]
ありがとうございます!!

**Comment by TatsukiWashimi** [comment]
@imyukino JGWdocにアップしましょう

**Comment by imyukino** [comment]
アップ済みです!

**Comment by TatsukiWashimi** [comment]
F2FのwikiとPEM wikiにもリンクを貼っておきました

**Comment by imyukino** [comment]
あ！すみません、ありがとうございます。
以後気をつけます
