### ISSUE TITLE
PSL 44Hz 振動

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#170]
PSL光学定盤が44Hzで振動している。それと関連があるかわからないが、ALSノイズに44Hzがある。その原因を調査し、ノイズハンティングを行う。

**Comment by yokozawa1985** [comment]
![](http://klog.icrr.u-tokyo.ac.jp/osl/uploads/10002_20190816060255_20190815150727585.jpg)

**Comment by TatsukiWashimi** [comment]
本日、中野さんと24V電源をPSLの外から引っ張ってくるようにしました。
44Hz lineは消えました。
![Screenshot 2019-08-27 at 16 03 08](https://user-images.githubusercontent.com/18456905/63752666-9fc78180-c8ec-11e9-8c7b-f9b382479f65.png)

portable accは上段の緑レーザーに移しました

**Comment by yokozawa1985** [comment]
goodjob!
