### ISSUE TITLE
落雷モニターの設置と読み出し

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#176]
### 目的　
#146 の続き
湘南工科大( http://www.5656jp.com/index.html )のサポートで落雷検知器を設置し、データ取得をする。
この装置には、アンプからのアナログ出力(磁場3軸、電場1軸)と512kHz samplingのデジタルデータおよび50ns制度のGPS時刻があるが、後者は直接ローカルに落とせず、湘南大のサーバーからもらう必要がある。
アナログ出力をこちらのADCで読み出す必要があるが、おそらく16kHzでも遅いので、
まずは湘南からデータをもらって解析してみて、要求されるスペックを見積もる方針にする。
このissueでは以下の1~4までをやる。

### ToDo　
 - [x] 1. 設置場所の現地調査 (9/12)
 - [x] 2. 機器の設置
 - [x] 3. ネットワーク接続
 - [ ] 4. 湘南サーバーのデータにアクセスする
 - [ ] 完了。Klogに投稿

**Comment by TatsukiWashimi** [comment]
雷のスペクトルを調べると、約5kHzをピークとする1/fスペクトルらしい

![frequency1](https://user-images.githubusercontent.com/18456905/63843311-28175680-c9c1-11e9-87a5-b8fd0bdef04c.gif)
Uman.M.A.,1987 The Lightning Discharge,Academic Press, New York

![a-The-mean-spectrum-of-lightning-pulses](https://user-images.githubusercontent.com/18456905/63843394-4da46000-c9c1-11e9-9622-462181a4eae3.png)
DOI: 10.1023/A:1017033320782

![Lightning-frequency-domain-electromagnetic-spectrum](https://user-images.githubusercontent.com/18456905/63843554-817f8580-c9c1-11e9-8623-0d95fc109034.png)
DOI: 10.4401/ag-4425

**Comment by TatsukiWashimi** [comment]
Blitzortung.orgのアンプの周波数特性
![frequency tif](https://user-images.githubusercontent.com/18456905/63843741-d8855a80-c9c1-11e9-9e60-8068926693b6.jpg)

**Comment by yokozawa1985** [comment]
雷の検出器への影響を、論文・会議で発表できるレベルにきちんと解析するのでしたら、雷の方の波形解析は湘南工科大に協力を要請して、きちんとコラボレーションするのがいいと思います。僕の中では雷フラグを提供するぐらいに思っていたので、検知できてframeに収めれればいいと思ってました。

**Comment by TatsukiWashimi** [comment]
個人的にはO3ではフラグだけで、深刻そうな感じならO4以降にちゃんと波形解析するようにすればよいと思います。

磁束計とOpLevの関係を見ていると、どうも明確な正の相関が見えないので、今の2kHzサンプリングだと大きさの評価もできていない感じです

**Comment by yokozawa1985** [comment]
雷解析の研究のための高サンプリング化を本日朝提案してみます。

**Comment by TatsukiWashimi** [comment]
まだBlitzortungのwebサーバーにアクセスして標定データ(.jsonファイル、10分ごと)を読み込み、KAGRAからの距離のヒストグラムを作るpythonコードを書きました。
(idとpassが含まれるので、コードはここには貼りません)
![lite_hist_sample](https://user-images.githubusercontent.com/18456905/65000241-d742b000-d925-11e9-9e3e-c947e48ce777.png)

自動化やSummary pageに盛り込むなどはまだですが、このissueでやりたいことは終わったのでcloseします。
