### ISSUE TITLE
LIGO daily summary pageのPEMページが半分以上機能していない

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#178]
**問題について** 
LIGO daily summary pageのPEMページが半分以上機能していない

- [x] おんどとりがRackしか表示されない ([6/7あたり](http://k1sum0/~controls/summary/day/20190607/pem/booth/)から)
- [x] OMC, PSL, SR 以外の加速度計、マイクが表示されない (BS, IMCは6/7まではある。他は最初からない)
- [x] 地震計が表示されない ([6/7あたり](http://k1sum0/~controls/summary/day/20190607/pem/ixv/)から)
- [ ] 今年設置した加速度計、マイクがない
- [x] 磁束計がない
- [ ] 気象計がない ([専用web](http://172.16.33.39/weewx/)があるが、瞬間雨量などはわからない)

完了したら、Klogに投稿！

**Comment by yokozawa1985** [comment]
今、LIGOの方々と修正をして行っています。
ただ、新たなPEMの表示は手が進んでいませんでした。。

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 どこかのタイミングで弄り方をlectureしてもらえますか？

**Comment by yokozawa1985** [comment]
金曜日3時にLIGO groupからのlectureを開催します。
その後でいじってみましょう。

**Comment by TatsukiWashimi** [comment]
@MiyoKouseki 
今の k1pem.ini ではMCE->BS の地震計の変更が反映されていないようです。

**Comment by TatsukiWashimi** [comment]
自分のディレクトリで磁束計のチャンネルを追加し、test.sh をやってpassしたので
~/etc/summary/configurations/k1/
にアップしました。

地震計のMCE channel関係はコメントアウトしときました

**Comment by TatsukiWashimi** [comment]
磁束計を追加しただけだが、何故かおんどとり・BS&IMC・地震計　も復活した

**Comment by yokozawa1985** [comment]
ありがとうございます。
今日、手が空いたら他に新たに追加したチャンネルや地震計のメンテナンスをしてみます。９時までに。。

**Comment by yokozawa1985** [comment]
mission completed!
