### ISSUE TITLE
Brucoすべき主要チャンネルのリストはどこ

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#18]
https://github.com/gw-pem/bruco
で、特定のチャンネルだけのコヒーレンスを計算するようにできるようにコードを書き直すので、それが終われば、主要チャンネルとPEMチャンネル同士のBrucoを計算できるようにしたい。
(ちなみにもともとのBrucoはstrainと全てに対して計算するのがデフォルトなので関係ないチャンネルをexcludeするオプションしかなかった。特定のチャンネルってオプションがない。)

なのでどれをBrucoすべきチャンネルが欲しい。

少なくともこのリポジトリでも、SVNでもいいからファイルにして管理しておきたい。

**Comment by yokozawa1985** [comment]
主要ちゃんねるのまとめサイトとして、僕はYuzu summary pageを押しております。
https://www.icrr.u-tokyo.ac.jp/~yuzu/bKAGRA_summary/html/2018-12-15_PEM.html
なんのチャンネルが重要なのかはは、
(少なくとも)IOO, VIS(牛場さん), PEMは日々更新しています。
主要ちゃんねるの単純な情報(特にtime seriesとspectrogram)が見れるのが素晴らしいです。

**Comment by MiyoKouseki** [comment]
このリポジトリにtxtファイルで管理しておきます

**Comment by MiyoKouseki** [comment]
PEMのしごとではないので、Close

**Comment by MiyoKouseki** [comment]
Yuzu SammaryのLatest channel listをみたら、現在の主要チャンネルがわかる。
https://www.icrr.u-tokyo.ac.jp/~yuzu/bKAGRA_summary/html/

**Comment by MiyoKouseki** [comment]
とりあえず「ImportantChannelList」という項目をつくり、YuzuSummaryPageのリンクを貼りました。
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/ImportantChannelList

ただし、前回2018/12/18のPEMミーティングで紹介されていたときはchannel_list_2018-12-18.txtというのがありましたが、さっき確認したら日付が2018/12/22に変わっていて、かつファイルが存在していませんでした。

どれを引用するのが正しいでしょうか？
@yuzuri

**Comment by yuzuri** [comment]
@MiyoKouseki 
返信遅くなってすいません、気づいてませんでした

> ただし、前回2018/12/18のPEMミーティングで紹介されていたときはchannel_list_2018-12-18.txtというのがありましたが、さっき確認したら日付が2018/12/22に変わっていて、かつファイルが存在していませんでした。
新しい機能を追加したばっかりだったので、少し不具合がありました
現在は解消されてると思います

あとwikiのページはこのリプライを見る前に偶然発見したので、少しだけ修正しておきました
↓は12/18のchannel listへの直リンです
https://www.icrr.u-tokyo.ac.jp/~yuzu/bKAGRA_summary/channel/channel_list_2018-12-18.txt
↓のページは最新のchannel listへのリンクが貼ってます。PEMのchannel名のルールが変更されるかもしれないので、こちらを参照していただけますか
https://www.icrr.u-tokyo.ac.jp/~yuzu/bKAGRA_summary/html/list_of_channel.html

**Comment by yokozawa1985** [comment]
とりあえずreview待ちに移行して、また主要チャンネルが増えたら(コミッショニングが進んだら)議論再開します。
