### ISSUE TITLE
落雷検知器の波形読み出し

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#182]
### 目的　
#176 で設置した落雷検知器について、標定データにアクセスすることはできているが、
時系列波形の読み取りは別途ADCが必要。

参考：Blitzortungの機器で使われているボード
http://www.5656jp.com/result6.html

### ToDo　
 - [ ] 1. い
 - [ ] 2. ろ
 - [ ] 3. は
 - [ ] 4. に
 - [ ] 完了。Klogに投稿

**Comment by TatsukiWashimi** [comment]
Blitzortungのリアルタイムマップから受信機をクリックすると、最も新しいイベントの時系列波形とスペクトルが見れる。
https://map.blitzortung.org/signal.php?station=2454&unit_width=2&mode=FFT&unit_height=128
![signal](https://user-images.githubusercontent.com/18456905/65151051-49b7ab00-da60-11e9-8725-409e777f6582.png)

これを見ると、最低でも200kHzくらいのサンプリングレートは欲しい。
一応、ハイレゾオーディオの規格で192kHzというものがある。

**Comment by TatsukiWashimi** [comment]
ラズパイ + ハイレゾ録音なども色々調べてみたが、
結局Blitzortungのシステムと同じ[STMディスカバリーボード](http://akizukidenshi.com/catalog/g/gM-05313/)を使うのが性能・コスパ両面で最適そう

**Comment by TatsukiWashimi** [comment]
Virgoの帰りに秋葉で買ってみようと思います

**Comment by yokozawa1985** [comment]
買っときましょうか？

**Comment by TatsukiWashimi** [comment]
ありがとうございます！

**Comment by yokozawa1985** [comment]
ぽちりました。

**Comment by TatsukiWashimi** [comment]
とどきました
![20190924_142751885](https://user-images.githubusercontent.com/18456905/65484586-5d3c9900-deda-11e9-9dbb-01d9d5c45482.jpg)

**Comment by TatsukiWashimi** [comment]
STMは高難易度なので、データロガーでやることにします

**Comment by yokozawa1985** [comment]
OK

**Comment by yokozawa1985** [comment]
OK

**Comment by TatsukiWashimi** [comment]
[png2pdf.pdf](https://github.com/gw-pem/kagra-pem/files/5205496/png2pdf.pdf)

**Comment by TatsukiWashimi** [comment]
#213 でデータロガーのバイナリファイルを読むコードを修正したので、雷データも見直した。
全然見えてないと思われていたMIインピーダンス素子の方もちゃんと見れている。
![200917-002945_REP4_Mag-HF](https://user-images.githubusercontent.com/18456905/95183677-43c67080-0801-11eb-89d9-7f908d59e819.png)
![200917-002945_REP4_Mag-LF](https://user-images.githubusercontent.com/18456905/95183684-45903400-0801-11eb-8e78-bb0c0adc5040.png)

これにてestablish
