### ISSUE TITLE
PEM情報の公開

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#187]
**改善案**
9/23 の KSC-all teleconで議論されたように、環境データはLVKコラボレーター外にも公開してよいと明記された。
気象計や落雷などの情報はスマホ等で簡単に見れるようできたら便利だと思う。

**Comment by TatsukiWashimi** [comment]
雷モニターは移してみました
https://www.icrr.u-tokyo.ac.jp/~washimi/KAGRA/PEM/KamioKaminari/

 - 埋め込み表示がうまくいっていない
 - archive plotがうまくいっていない

**Comment by TatsukiWashimi** [comment]
落雷位置のplotもk1sum0ではなく柏サーバーで作るようにした。
今までのコードをそのまま走らせると、距離の計算に使っている pyproj がないと怒られる。
勝手にpip install できないので、virtualenv 上で入れてみたが、今度はrootが使えない。

しょうがないので、代わりに astropy の SkyCoord で代用。
(参考：柚子様 & https://codeday.me/jp/qa/20190709/1209282.html)
pyprojより時間がかかるが、走ってはいる

**Comment by TatsukiWashimi** [comment]
ほぼ同じplotができたのでよしとする。
上：pyproj
下 : SkyCoord
![Screenshot from 2019-11-07 17-05-21](https://user-images.githubusercontent.com/18456905/68370968-fff66180-0180-11ea-88f0-a87652bc750d.png)

**Comment by yokozawa1985** [comment]
ありがとうございます！
作成した図をscpするではダメなのはなんででしたっけ？

**Comment by TatsukiWashimi** [comment]
本当は共同利用計算機で走らせてそのままpublic_htmlを更新するようにしたかったのでやってみたんですけど、同じ問題でダメだったので、柏サーバーの方でもやってみたのです。
(共同利用計算機の方はasrtopyすら入ってないようで、同じように解決することはできませんでした。)

坑内磁束計の解析も入れたいので、m31の方でいいと思います

**Comment by TatsukiWashimi** [comment]
icrhomeのpublic_htmlでBlitzortungのリアルタイムモニターを埋め込み表示できない問題について色々試した。
最初、html5に対応していないのかと思ったが、google mapの埋め込みはできる。
おそらく、[X-Frame-Options](https://webllica.com/deny-iframe-access-by-htaccess/)によってiframeタグに制限がかけられている。
.htaccesを自分で作って許可すると、Internal Server Errorになる。

**Comment by TatsukiWashimi** [comment]
iframeの代わりにobjectタグでも試したが、ダメ

**Comment by TatsukiWashimi** [comment]
結局どうにもできなかったので、代わりに別ウィンドウでリンクを開くようにした。
ついでに最新eventを自動で更新するようにした。

**Comment by TatsukiWashimi** [comment]
PEM mapで、前日のyuzu summary plotを表示できるようにしてみました。
(まだPSLだけ)
https://www.icrr.u-tokyo.ac.jp/~washimi/KAGRA/PEM/PEMmap/
![Screenshot 2019-11-10 at 19 07 02](https://user-images.githubusercontent.com/18456905/68542217-9cbd3700-03ed-11ea-9127-0957f00760e5.png)

**Comment by yokozawa1985** [comment]
計算量をdetcharに相談して、daily summary pageでも(少なくともspectrum、できれば)spectrogramを計算できたら嬉しいですね。

**Comment by TatsukiWashimi** [comment]
そうですね

**Comment by TatsukiWashimi** [comment]
今朝、KamioKaminariの自動plot更新と、yuzu summary plotのPEM mapへの自動コピーが動いていることが確認できました。

**Comment by TatsukiWashimi** [comment]
PEM MAPでのyuzu summary plot表示ページをIMC, BS, Xemd, Yendのものも作りました。 

現在の常設PEMでplot生成がされていないものは

- [ ] K1:PEM-MIC_BS_TABLE_POP_Z_OUT_DQ
- [ ] K1:PEM-MAG_BS_BOOTH_BS_Y_OUT_DQ (時系列だけおかしい)
- [ ] K1:PEM-MAG_BS_BOOTH_BS_Z_OUT_DQ 
- [ ] K1:PEM-ACC_EXA_TABLE_TX_Z_OUT_DQ
- [ ] K1:PEM-ACC_EXA_TABLE_RX_Z_OUT_DQ
- [ ] K1:PEM-MIC_EXC_BOOTH_EXC_Z_OUT_DQ
- [ ] K1:PEM-MIC_TMSX_BOOTH_TMSX_Z_OUT_DQ
- [ ] K1:PEM-MIC_EXA_BOOTH_EXA_Z_OUT_DQ
- [ ] K1:PEM-MAG_EXC_BOOTH_EXC_X_OUT_DQ
- [ ] K1:PEM-MAG_EXC_BOOTH_EXC_Y_OUT_DQ
- [ ] K1:PEM-MAG_EXC_BOOTH_EXC_Z_OUT_DQ
- [ ] K1:PEM-ACC_TMSY_TABLE_TMS_Z_OUT_DQ
- [ ] K1:PEM-ACC_EYA_TABLE_TX_Z_OUT_DQ
- [ ] K1:PEM-ACC_EYA_TABLE_RX_Z_OUT_DQ
- [ ] K1:PEM-MIC_EYC_BOOTH_EYC_Z_OUT_DQ
- [ ] K1:PEM-MIC_TMSY_BOOTH_TMSY_Z_OUT_DQ
- [ ] K1:PEM-MIC_EYA_BOOTH_EYA_Z_OUT_DQ
- [ ] K1:PEM-MAG_EYC_BOOTH_EYC_X_OUT_DQ
- [ ] K1:PEM-MAG_EYC_BOOTH_EYC_Y_OUT_DQ
- [ ] K1:PEM-MAG_EYC_BOOTH_EYC_Z_OUT_DQ

**Comment by TatsukiWashimi** [comment]
雷もYuzusama in PEM mapもできたのでclose
