### ISSUE TITLE
temporary channelの常時DQ

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#188]
干渉計信号とtemporary PEMのコヒーレンスを見ながらノイズハンティングをしていくうえで、いちいちモデルを編集更新するのは面倒だと思う。
コヒーレンス探索で調べる環境ノイズは100Hz以下のものが多いので、全てのtemporary chを512Hzくらいで常時DQしてしまうのはどうか

**Comment by yokozawa1985** [comment]
実行済み？
