### ISSUE TITLE
LLOから譲り受けたとされるPEMの解析コードをこのリポジトリに入れる

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#19]
その場合、公開しない方がいいですか？

**Comment by neouniverse** [comment]
本家が公開していないものを勝手に公開するのはまずいと思う。
ac.jpのメールアドレスがあればGitHub educationに切り替えて
private repoが無料で作れたはずなのでそちらに移行しても良いかも。

**Comment by yokozawa1985** [comment]
LIGOでは、使用頻度が高い解析コードはGitlabで公開している。
公開しているものはわざわざここに置く必要がないし、公開していないものは
山Tさんがおっしゃっているとおりおいてはいけないと思います。
例　
https://git.ligo.org/philippe.nguyen/pemcoupling
KAGRAアカウントでログインしてみれます。

**Comment by MiyoKouseki** [comment]
了解です。プライベートリポジトリを作っておきます。

ちなみにこのgw-pemはligoとVirgoもここにこれるよう名付けました。
将来的には一緒に開発が出来たらいいですねぇ。

**Comment by MiyoKouseki** [comment]
確かにそうですね。このgw-pemはkagraで閉じる方針で。

**Comment by yokozawa1985** [comment]
move to close
