### ISSUE TITLE
PEM MAPの更新 for O3

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#195]
### 目的　
O3 に向けての、最終状態のPEM MAPを作る。
このバージョンは論文とかでも使えると思われるので、保存しておく。

### ToDo　
 - [ ] 1. い
 - [ ] 2. ろ
 - [ ] 3. は
 - [ ] 4. に
 - [ ] 完了。Klogに投稿

**Comment by yokozawa1985** [comment]
2019/11/08verを最新版として、明日は確認作業にあてましょうか？

**Comment by yokozawa1985** [comment]
今日でした。

**Comment by TatsukiWashimi** [comment]
まだ変動がある(電源モニターとか)可能性があるので、もうちょい先でもいいと思います

**Comment by yokozawa1985** [comment]
了解しました。

**Comment by TatsukiWashimi** [comment]
変更するものリスト

新規追加
- volt meter 全部 (PSL, AS, REFL)
- 真空計
- おんどとり何個か？

取り除いたもの
 - IYC気象計

ch名変更、写真変更
 - PSL加速度計(Z -> X,X,Y)
 - IXCマイク (FIELD -> BOOTH)

写真変更
 - POP, POS, REFL, AS の加速度計・マイク

**Comment by TatsukiWashimi** [comment]
この前、杉本君がPSLに入ったときに加速度計の写真を撮ってもらった。
ACC_table1のケーブルが抜けているのがわかる
![12264](https://user-images.githubusercontent.com/18456905/70516322-22154200-1b7a-11ea-9fbc-dd07888bd0ea.jpg)

**Comment by TatsukiWashimi** [comment]
PSL加速度計のチャンネル名の軸が間違えている。ケーブルが抜けているやつがTABLE1で、Y方向

誤
 - TABLE1_X
 - TABLE2_X
 - TABLE3_**Y**
正
 - TABLE1_**Y**
 - TABLE2_X
 - TABLE3_X
![Screenshot 2019-12-11 at 13 14 30](https://user-images.githubusercontent.com/18456905/70591120-5dfee480-1c18-11ea-92c5-bab7438ff7a1.png)

**Comment by TatsukiWashimi** [comment]
TABLE3はZ軸方向でもいいかも

**Comment by yokozawa1985** [comment]
明日、Zにして、最終にして、calibration factorいれます。

**Comment by yokozawa1985** [comment]
明日、Zにして、最終にして、calibration factorいれます。

**Comment by TatsukiWashimi** [comment]
日曜にREFL taableに追加した加速度計の写真はありますか？
あとチャンネル名も教えてください

**Comment by yokozawa1985** [comment]
返信遅くなりました。

**Comment by yokozawa1985** [comment]
/Users/yokozawa/Library/Containers/com.apple.mail/Data/Library/Mail Downloads/C64579AE-0EBB-467B-B052-706ECCB5D867/IMG_0588.jpeg

**Comment by yokozawa1985** [comment]
IMG_0588.jpeg
