### ISSUE TITLE
光学定盤の電位モニター@CS

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#198]
### 目的　
本日、AS定盤に試験的に電位モニターを設置した([http://klog.icrr.u-tokyo.ac.jp/osl/?r=11701](http://klog.icrr.u-tokyo.ac.jp/osl/?r=11701))が、同様のものを他の定盤にも設置したい。

- PSL
- IMCREFL
- REFL
- IMMT1
- POP
- AS
の6個とすると、SR3ラックのBNCが8chあるので足りる。
(ASに付けたのもIYCから移したほうが揃うので良いか)

**Comment by TatsukiWashimi** [comment]
PSL定盤に設置完了。(ケーブリングはまだ)

**Comment by yokozawa1985** [comment]
お疲れ様です。
ASのもSR3付近からの配線が良いかと思います。

**Comment by TatsukiWashimi** [comment]
今日ケーブリングして接続してきました。
AS定盤のもSR3 BNCにしてきました。
 - BNC8 : PSL table
 - BNC9 : PSL reference
 - BNC10 : AS table
です。

**Comment by TatsukiWashimi** [comment]
![PSL1](https://user-images.githubusercontent.com/18456905/69860716-2ae45900-12da-11ea-9fcc-d4fbac8269ec.png)
![PSL2](https://user-images.githubusercontent.com/18456905/69860730-2f107680-12da-11ea-9bdf-a62d46e0a47f.png)
![AS](https://user-images.githubusercontent.com/18456905/69860737-320b6700-12da-11ea-9bab-5f473774de1b.png)

**Comment by TatsukiWashimi** [comment]
中野さんに聞いたところ、REFL tableにも欲しいとのこと
IMCREFL、POPの優先度は低く、あるに越したことはないけど無くてもいいらしい。

**Comment by TatsukiWashimi** [comment]
REFL tableにも付けました。

**Comment by TatsukiWashimi** [comment]
ch名は以下で良いか

K1:PEM-VOLT_PSL_TABLE
K1:PEM-VOLT_PSL_FLOAT
K1:PEM-VOLT_AS_TABLE
K1:PEM-VOLT_OMC_CHAMBER
K1:PEM-VOLT_REFL_TABLE

**Comment by TatsukiWashimi** [comment]
OMCチェンバー用のも近くまでケーブリング完了。
どこにつけるかは要検討

**Comment by TatsukiWashimi** [comment]
ch名アサイン & DQ までできたのでclose
http://klog.icrr.u-tokyo.ac.jp/osl/?r=12013
