### ISSUE TITLE
地震計のチャンネルにおかしなものが

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#199]
**問題について** 

**IXV**
Y/Z方向 の BLRMS_10_30 に BLRMS_1_3 の値が入っている。(Xは正しそう)
modelを見たところ、それぞれ正しい名前のフィルターが入っていたので、フィルターバンクのパラメタが間違ってる？
![K1-ALL_E9619F_TIMESERIES-1260903618-7680](https://user-images.githubusercontent.com/18456905/71511035-42603300-28d4-11ea-9100-77bd65ece1cd.png)
![K1-ALL_52F2EB_TIMESERIES-1260903618-7680](https://user-images.githubusercontent.com/18456905/71511048-5146e580-28d4-11ea-901d-9def12d2a79b.png)
![K1-ALL_79F9A2_TIMESERIES-1260903618-7680](https://user-images.githubusercontent.com/18456905/71511049-53a93f80-28d4-11ea-9023-dcc660d4917c.png)

**IXC**
鉛直成分の信号がおかしい。
DC値が大きな負の値。地震のタイミングで何も検知できていない。
![K1-ALL_9B0CB9_TIMESERIES-1260903618-7680](https://user-images.githubusercontent.com/18456905/71511165-b13d8c00-28d4-11ea-9eef-e1c8870314c0.png)

**Comment by TatsukiWashimi** [comment]
IXCのケーブルのコネクタを作り直しました。
明日入れてきます

**Comment by yokozawa1985** [comment]
宜しくお願いします。

**Comment by TatsukiWashimi** [comment]
チャンネルがひとつづつズレていて、検出器の状態を表す信号がUD channekに入っていました。
http://klog.icrr.u-tokyo.ac.jp/osl/?r=12437

modelは修正したので、頃合を見てrestartします。
![2020-01-09 (3)](https://user-images.githubusercontent.com/18456905/72038505-fefac100-32e4-11ea-990a-3c49a910577f.png)

**Comment by TatsukiWashimi** [comment]
明日の朝礼の時にアナウンスしてrestartします

**Comment by TatsukiWashimi** [comment]
完了しました。
http://klog.icrr.u-tokyo.ac.jp/osl/?r=12457
