### ISSUE TITLE
低周波音インジェクション

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#200]
http://www.kobayasi-riken.or.jp/news/No125/125_2.htm
http://www.kobayasi-riken.or.jp/home_page_top/Frame3_sisetu.htm

**Comment by yokozawa1985** [comment]
(-_-)!

**Comment by TatsukiWashimi** [comment]
[この本](https://www.coronasha.co.jp/np/isbn/9784339013368/)ぽちりました。今週中に届くようなので勉強します。
![image](https://user-images.githubusercontent.com/18456905/71940782-f8901a80-31fa-11ea-8913-e1364217de77.png)

**Comment by yokozawa1985** [comment]
僕も読みたい！

**Comment by TatsukiWashimi** [comment]
自作スピーカー講座
http://kanon5d.web.fc2.com/2015_6/kouza_2015.html

**Comment by TatsukiWashimi** [comment]
超低周波音再生用スピーカシステムの開発
http://www.oyama-ct.ac.jp/tosyo/kiyou/kiyou37/37kobayshi.pdf

**Comment by TatsukiWashimi** [comment]
速報：ファーウェイが高級スマートスピーカーSound X発表。40Hz低音と144W出力をデビアレ社コラボで
https://japanese.engadget.com/jp-2020-03-26-sound-x-40hz-144w.html

![image](https://user-images.githubusercontent.com/18456905/77711661-f167f400-7014-11ea-93f7-87064f35bf53.png)

HUAWEI Sound Xファーウェイの新製品発表会では、高級スマートスピーカー（ファーウェイ側は「AIスピーカー」と呼称します）となる『HUAWEI Sound X』も公開されました。アップルのHomePod的な円筒形ベースの本体に、高級オーディオ並みの仕様を詰め込んだモデルです。

発売日は現状では非公開。価格も発表会では非公開でしたが、先行して販売されている地域では、320から350ドル前後となっています。HUAWEI Sound X

![image](https://user-images.githubusercontent.com/18456905/77711684-f88f0200-7014-11ea-82ad-8b96af63a45e.png)

特徴は、スピーカーとしての基本性能が高い点。公称での低音側周波数特性は40Hzからと優秀で、最大出力は144W、最大音圧は93dBとこちらも高級オーディオ並み。高音側は公称で40kHzの再生に対応し、ハイレゾオーディオ認定ロゴも掲げます。

これらは高級アクティブスピーカーで注目される、フランスのメーカー『DEVIALET』（デビアレ）とのコラボによって実現されたものです。

スピーカーユニットは、中高音用が底面側に円周配置された6個のフルレンジタイプ、低音用が2個のウーファー（低音再生用）という構成。この配置も「全周囲に音場を放つ」タイプであり、HomePodに近い狙いと呼べそうです（もちろん、スマートスピーカーにはこのタイプが多いのですが）。

とくにポイントとなるのがウーファーで、2基のユニットを外向きに配置し、配置は互いに背を向けた「Push-Push方式」を採用。これはデビアレが自社製の高級スピーカーに採用している配置です。

さらにアンプとの特性マッチングにも、デビアレが得意とする「スピーカー・アクティブ・マッチング」（SAM）技術を導入。いわゆるインピーダンス特性の暴れやタイムアライメントの不整合といった音質を劣化させる要素、さらには外装の余分な振動も配慮に入れたスピーカー駆動の実現を謳います。

![image](https://user-images.githubusercontent.com/18456905/77711704-047ac400-7015-11ea-8fa1-74f81ea56a8f.png)

ユニット自体も"デビアレ社スピーカー直系"の仕様。大出力を受け止めるため、ユニットのストロークは20mmと破格。合わせてボイスコイルの振幅側幅は21mm、重要なマグネットもネオジウム（Nd-Fe-B）タイプと、いい意味でスマートスピーカーで出てくるような仕様とは思えない、破格のスペックが並びます。

本体サイズは直径165mm×高さ203mmで、重量は約3.5kg。これだけの（本格的スピーカーとしては小型の）サイズで、上述のような高級オーディオ並の特性を備える点が白眉です。

**Comment by TatsukiWashimi** [comment]
JBL PROFESSIONALのシネマサブウーハ
https://proaudiosales.hibino.co.jp/jblpro/610.html

コロナ社の教科書で紹介されていたのは4642Aで、40万円弱
![image](https://user-images.githubusercontent.com/18456905/77713518-e6fc2900-7019-11ea-8105-d2725e7643e9.png)

**Comment by TatsukiWashimi** [comment]
FOSTEXウーファーは、論文に載っていた FW108Nはおそらく生産終了品。
おそらく相当する現行機はFW108HSで、1個2万円程度。
論文にあるような16個のアレイを作るとウーハだけで30万円以上かかる。

制作や試験の手間も考えると、JBLのシネマサブウーハを買ってしまった方がいいかも

**Comment by TatsukiWashimi** [comment]
Olasonic IA-BT7というBluetoothスピーカー (ただし電源は有線)が、低周波側20Hzまでいけるらしい。
https://www.olasonic.jp/product/?id=1526269723-648034

評判によると、「低音が出すぎて問題になる」レベルとのこと。
https://note.com/roy_note/n/n1de9538ef262

**Comment by yokozawa1985** [comment]
Olasonic、4月になった瞬間に買いましょう。
(個人で欲しいレベル)

**Comment by TatsukiWashimi** [comment]
シネマ・サブウーハ用の防振台車候補 (荷重100kg以上)

エポックトランスフォーム社　防振平台車　約10万円
http://www.epoch-transport.jp/flatcart.html

デンソー　防振台車　価格不明
https://www.kk-denso.co.jp/products/boushin-truck.php

ミナト アルミ台車 MAC-100N　1万4000円
[amazon.com](https://www.amazon.co.jp/MAC-100N-%E3%83%8E%E3%83%BC%E3%83%91%E3%83%B3%E3%82%AF%E3%82%BF%E3%82%A4%E3%83%A4-%E3%82%A2%E3%83%AB%E3%83%9F%E6%9D%BF%E5%BC%B5%E3%82%8A%E4%BB%95%E6%A7%98-%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A4%E5%80%8B%E7%94%A8-%E8%8D%B7%E9%87%8D100kg/dp/B00LE365QA/ref=asc_df_B00LE365QA/?tag=jpgo-22&linkCode=df0&hvadid=280316679309&hvpos=&hvnetw=g&hvrand=5115528642630283917&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1009365&hvtargid=pla-525833842996&th=1)
防振性能が謎だが、タイヤは大きい

**Comment by yokozawa1985** [comment]
届いたよ。30Hzも検出されました。

**Comment by TatsukiWashimi** [comment]
orasonicが使えたので一旦closeします。
パワーが足りなかったらシネマウーハーを検討
