### ISSUE TITLE
wikiの更新

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#21]

**Comment by yokozawa1985** [comment]
横澤のためのメモ

- [ ] PEM channelsの更新

- [ ] PEM instrumentの更新

- [ ] PEM placementの更新

**Comment by yokozawa1985** [comment]
general informationに関しては、全て埋めた。
ついでにmedm screenも必要なものを揃えた。

**Comment by MiyoKouseki** [comment]
ありがとうございます。
medmスクリーンというのはどこのことですか？
