### ISSUE TITLE
PEM websiteの作成

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#22]

**Comment by yokozawa1985** [comment]
LIGOのPEM website 
http://pem.ligo.org/channelinfo/index.php
の作り方を教えていただいた。
これから情報を載せていきます。

**Comment by yokozawa1985** [comment]
inkscape
を使って、クリックで各PEMに飛べるようになっている。
source codeは、webブラウザから見れるはず。
困ったらTerraが相談に乗ってくれる。
inkscapeはKKさんがすでにk1ctrにインストールしてくれている模様。

**Comment by TatsukiWashimi** [comment]
神岡オフィス専用
http://k1sum0/~controls/PEMmap/

柏サーバー
https://www.icrr.u-tokyo.ac.jp/~washimi/KAGRA/PEM/PEMmap/
(現状パスワードがかけれていないので、plotと写真は載せていないです)

**Comment by yokozawa1985** [comment]
鷲見様、ありがとうございます。
どんどん告知していきましょう。closeします。
