### ISSUE TITLE
GWpy install

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#23]
GWpyをもっといろいろなclient PCで使用できるようにするのが大事だと思う。
有用性を示して、k1ctr0-4には少なくとも入れたい。

**Comment by MiyoKouseki** [comment]
では自分が入れときます。
python3にしますか？
python2にしますか？

**Comment by yokozawa1985** [comment]
自分が使いやすい方でいいと思います。
どのみち、O3終了後にLIGOで大幅なソフトウェアアップデート
(すくなくとも、debian9, python3に対応)
が行われるときにテコ入れが再発すると思いますので。

**Comment by MiyoKouseki** [comment]
PEMのしごとではないので、Close
