### ISSUE TITLE
このkagra-pemリポジトリを公開のままにしておくか田舎

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#27]
各人の名前とかが晒されているのでインターネット上で公開するのは良くない気がする。
とはいえteamで使っているgw-pem をプライベートリポジトリにするには課金が必要。

非公開にすれば後悔しづらいコードも管理できる。

んーどうしましょう。

**Comment by MiyoKouseki** [comment]
‘’’
Get unlimited private repositories for teams
Starting at $25 / month which includes your first 5 users, $9 / month for each additional user
‘’’
とあります。

**Comment by yokozawa1985** [comment]
KAGRAに問いかけてみましょう。このようなプロジェクト管理を開始しているサブシステムは他にもあるはずです。

**Comment by kokeyama** [comment]
阿久津さんが非公開レポジトリを持っていて、教育機関はタダって言ってた気がする。

**Comment by yokozawa1985** [comment]
阿久津さんに聞いて見ます。

**Comment by yokozawa1985** [comment]
https://yotalabo.org/github-education/
で、大学機関にいると保証されている人は最大2年間無料だそうです。
風邪が治ったら対応いたしますので、皆さんは、.ac.jpのGitHub accountを作成しておいてください。
新たなissueを立ち上げておきます。

**Comment by MiyoKouseki** [comment]
#54で具体的に話が進んでいるのでCloseした。
