### ISSUE TITLE
IOOインプット側主要チャンネルがまとまっていない

### ISSUE THREAD

**Issue by TTanakaTT** [gw-pem/kagra-pem#3]
## 目的／目標
IOOインプット側主要チャンネルをリストアップする
## ToDo
- [x] リストアップする
- [ ] Wikiにページをつくって、載せる。

## 完了報告
K1:IMC-MCL_SERVO
K1:IMC-SERVO_MIXER_DAQ
K1:IMC-SERVO_FAST_DAQ
K1:IMC-SERVO_SLOW_DAQ
K1:IMC-MCE_TRANS_QPDA1
K1:IMC-MCE_TRANS_QPDA2
K1:IMC-CAV_ERR
K1:IMC-CAV_REFL
K1:IMC-CAV_TRANS

**Comment by MiyoKouseki** [comment]
どうしてそのチャンネルが主要なのか、理由が書けるといいと思います。

**Comment by MiyoKouseki** [comment]
PEM Wikiに描いてあるリストに上記のチャンネルが無いものがあります。
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/ImportantChannelList

@TTanakaTT 
どちらが正しいのでしょうか？
#18 でも議論されています。

**Comment by yokozawa1985** [comment]
T田中さん、他の作業もお願いしているところですが、並行してIMC理解も進めましょう。
->まずは重要チャンネルとそのチャンネルの役割の理解です。
あとは、optical tableの配置図を確認して、本当にマイクの位置と加速度計の位置が
適切かの判断をしてみましょう。

**Comment by TTanakaTT** [comment]
重要チャンネルの理解がまだなので、早く理解し前にも三代さんがコメントを下さったように重要な理由を書き下したいと思います。

**Comment by yokozawa1985** [comment]
大雑把には中野さんのD論
https://gwdoc.icrr.u-tokyo.ac.jp/DocDB/0075/G1707575/002/main.pdf
に書いてありますが、検出器のことは現地でやるのが効率がいいので
次回訪問時に腰を据えて行いましょう。

**Comment by MiyoKouseki** [comment]
このIssueはOpenしてから1ヶ月が経っているので、Closeします。
Wikiに載せるまではしなくてもいいということで。
