### ISSUE TITLE
これは正しいコヒーレンス？

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#33]
2018/12/17の20時のBrucoの結果をみてみた。
PEMのMICとACCが、IMCのSERVOとコヒーレンスがありそう。

このページに画像がすべてある。
https://www.icrr.u-tokyo.ac.jp/~yamat/KAGRA/bruco/2018/12/17/20/IMC/

こんな感じの画像。マイク。
![image](https://user-images.githubusercontent.com/24282734/50084944-f6e46500-023b-11e9-8971-9229025c1826.png)

これは正しいコヒーレンスですか？
@TTanakaTT 

そもそも何処のマイク？？？

**Comment by yokozawa1985** [comment]
KOACH filter on/offのチェックをBrucoありでやってみたいですね。

**Comment by TTanakaTT** [comment]
PMCの方にもコヒーレンスが出ているので、その辺りの制御系を勉強してから考えてみます

**Comment by MiyoKouseki** [comment]
@TTanakaTT とりあえずCloseします。
別に進めてください。
