### ISSUE TITLE
気象計のキャリブレーションチェック

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#37]
### 目的
気象計を2台つくった。その信号をチェックするために、IY0ラックの中に2台を隣接しておいて、信号を取得し、比較してみる。

### ToDo
 - [x] 1. IY0ラックに置いて一晩計測
 - [ ] 2. 温度、湿度、気圧の値を時系列で比較
 - [ ] 3. 温度、湿度、気圧スペクトルで比較
完了

### レビュー用まとめ
1. http://klog.icrr.u-tokyo.ac.jp/osl/?r=7118
2.
3.

**Comment by yokozawa1985** [comment]
現在も2台ありますか？？

**Comment by MiyoKouseki** [comment]
もう何も覚えていない。
