### ISSUE TITLE
気象計を各所に設置（IYCとIXV）

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#38]
### 目的
（なぜそれをやりたいのか、）
まずすぐ設置できそうなところに気象計をおいて長期間のデータをとりたい。

### ToDo
(どうすればIssueをCloseできるか)
 - [x] 1. IYC、IXVに設置
 - [ ] 3. 1週間のデータを比較
完了

### レビュー用まとめ
（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1. http://klog.icrr.u-tokyo.ac.jp/osl/?r=7149
2.
3.

**Comment by yokozawa1985** [comment]
気象計関係は一旦closeします。
