### ISSUE TITLE
まだIOOの主要チャンネルとマイクでBrucoしていない

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#4]
## 目的
IOOの主要チャンネルがわかった(#3 )ので、Brucoするためにマイクを置く。

## ToDo
- [ ] マイクを置く。
- [ ] Brucoする。
- [ ] 完了！

## 参考

**Comment by yokozawa1985** [comment]
これも議論を再開させましょう!

**Comment by MiyoKouseki** [comment]
このIssueはOpenされてから1ヶ月が経ちました。
田中くんの反応がないのでCloseします。
