### ISSUE TITLE
地震計に関係したモデルのSDFを整備

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#40]
### 目的
（なぜそれをやりたいのか、）
DAQしているチャンネルは、フィルター直後のOUTだけにしているので、フィルターのONOFFがあとから追えるようにしないと、解析するときに不便なので、SDFを整備する

### ToDo
(どうすればIssueをCloseできるか)
 - [x] 1. observe.snap をつくる
 - [x] 2. SDFで管理
完了

### レビュー用まとめ
（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1. http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Channels#SDF
2. http://klog.icrr.u-tokyo.ac.jp/osl/?r=7249

**Comment by MiyoKouseki** [comment]
Done.
Wait for review.

**Comment by yokozawa1985** [comment]
このissueはclose
