### ISSUE TITLE
地震計と気象計のチャンネル名を整理

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#41]
### 目的
（なぜそれをやりたいのか、）
これまでの名前だとわかりづらい。EW，NSだと分かりづらいし、SEIS_SENSINFだと意味不明。

### ToDo
(どうすればIssueをCloseできるか)
 - [x] 1. チャンネルを変える。
 - [x] 2. Wikiの更新
完了

### レビュー用まとめ
（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1. http://klog.icrr.u-tokyo.ac.jp/osl/?r=7186
2.http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Channels#Seismometer

**Comment by MiyoKouseki** [comment]
Done.
Waitting review.

**Comment by MiyoKouseki** [comment]
#48 で地震計のチャンネル名を見直しているので、その結果しだいでもう一度名前を変更する。

**Comment by yokozawa1985** [comment]
別issue次第なのでclse
