### ISSUE TITLE
地震計のケーブル等が水対策していない

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#42]
**問題について** 
以前戸村さんと上泉さんから、言われていた。

**正しい状態** 
ケースに入れてあるか、台において浸水しても大丈夫な状態にしておくべき

**問題の箇所** 
袋には入っているが、密封されておらず地面に直置き。

**Comment by MiyoKouseki** [comment]
IXVは対策した
http://klog.icrr.u-tokyo.ac.jp/osl/?r=7015

**Comment by MiyoKouseki** [comment]
## ToDo
- [ ] EXVの対策
- [ ] EYVの対策

**Comment by yokozawa1985** [comment]
いつ頃EYVに戻しましょうか？
21日に週の後半からY arm commissioningが始まるのでそれまでにという感じがいいかもしれません。

**Comment by MiyoKouseki** [comment]
明日やる。

**Comment by MiyoKouseki** [comment]
もうやった気がする。
