### ISSUE TITLE
MCEの地震計がノイジー

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#43]
**問題について** 何が問題か書いてください
#35 にあるように、MCIはOKそうだけどMCEが明らかにノイジー。

**正しい状態** どうなっているべきか書いてください
ノイズがさがってMCIとコヒーレンスをもつべき。

**Comment by MiyoKouseki** [comment]
明日やる

**Comment by yokozawa1985** [comment]
何が原因でノイジーな状態が作られていたのでしょうか？

**Comment by MiyoKouseki** [comment]
@yokozawa1985 温度変化で地震計のマスの位置が傾き、地震計の共振周波数が変わって、地面応答が悪くなったのが原因だと思います。Mark Beker氏のD論でも同じようなことが指摘されています[1]。

[1] p. 81, https://inspirehep.net/record/1239032/files/Thesis-2013-Beker.pdf
