### ISSUE TITLE
KAGRAのSeismon用に教師データをつくる

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#44]
### 目的　（なぜそれをやりたいのか、）
#16 にあるように、KAGRAサイトでの地面揺れを評価するために、地震とその時の地震計の揺れを集めた教師データが必要。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 震源の情報をCSVにまとめる
 - [ ] 2. 到達時刻を計算
 - [ ] 3. 到達時の地面振動の最大RMSを計算
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.

**Comment by MiyoKouseki** [comment]
@yokozawa1985 SeismonをKAGRAでも使えるようにするためです。Seismonは遠方の地震がどれ位サイトを揺らすか、過去のデータから学んで予測しています。このIssueはその学習用データづくりです。

**Comment by MiyoKouseki** [comment]
/remind me this things  in 10 minutes

**Comment by yokozawa1985** [comment]
どうですか？？？

**Comment by MiyoKouseki** [comment]
とりあえず現状についてまとめる。

**Comment by MiyoKouseki** [comment]
放置することにする。O3後かな。
