### ISSUE TITLE
PSLのRFノイズ探索

### ISSUE THREAD

**Issue by TTanakaTT** [gw-pem/kagra-pem#45]
## 目的／目標
RFノイズ源の特定
## ToDo 
- [ ] RFモニターを使って何HzにRFノイズがあるかリストアップ
- [ ] 各周波数毎にノイズ源の予想
- [ ] スイッチの切り替えなどで同定

## 候補
EoM
f1 : 16.88 MHz | PM and AM
f2 : 45.02 MHz | PM
f3 : 56.27 MHz | AM

**Comment by MiyoKouseki** [comment]
ラベル、プロジェクト などをつけてもらえますか？

**Comment by yokozawa1985** [comment]
今週、長野さんのところへ行って、来週1日使って測定を計画。

**Comment by yokozawa1985** [comment]
wikiに結果が乗ったので、解析方針はあらたなissueを立ち上げるとしてcloseします。
