### ISSUE TITLE
PSLに気象計を置く

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#46]
### 目的　（なぜそれをやりたいのか、）
レーザーがあるので、温度をモニターしたい。
が、オンドトリがあるし急ぎでもない気がする。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. アンプ回路boxの完成
 - [ ] 2. チャンネル作成
 - [ ] 3. 設置場所の決定
 - [ ] 4. 設置
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
空気の短時間の動きを察知できることが証明されたら導入を提案してもいいと思います。

**Comment by neouniverse** [comment]
そこそこ体積のある空間だし仮におんどとりで取れない時間スケールでの温度変化が見れたとしても
それは温度計付近の局所的なものであって必ずしもレーザー付近も同様とは言えないと思う。

やるとしたらレーザーのすぐそばとか、筐体の排熱口・吸気口(あるのか？)前に置いてみるとか
局所的な温度変化を追いかけてレーザー様にとっての体感温度を見てみるとかかなぁ。
そう言えばレーザー自身に内蔵された温度モニタとかあったりしないんだろうか？

因みに特別モチベーションがある訳じゃないというか、おんどとりの主目的が
大局的な温度を見る事なので1分間隔にしてるけど実はおんどとりで1秒間隔が出来ない訳じゃない。

**Comment by MiyoKouseki** [comment]
コメントありがとうございます。

とりあえずオンドトリがあるので、PSLに気象計を置くのは当面パスということで。

個人的には気象計は気圧を測りたいのが主な理由なので、温度湿度のみであればオンドトリで十分だと思っています。

「PSLに気象計はないの？」という質問が上がればこのissueを参考にしてもらうようにします。

close
