### ISSUE TITLE
センサーの場所が分からない

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#47]
**問題について** 何が問題か書いてください
センサーの名前をみてもどこに設置されているかわからない。
pem mapに載せてありますか？

**正しい状態** どうなっているべきか書いてください
まずチャンネル名をわかりやすく命名して(#32 )、pem mapもしくはpem web pageで「一覧」できるようにする。(#22 )

まずはPEMMAP上にリンクを貼ることから。

- [ ] 常設するセンサーのチャンネルリスト。加速度計、マイク、磁束計。
- [ ] PEM MAPにFilterBankへのリンクを貼り付け
完了

**Comment by MiyoKouseki** [comment]
まずはPEMMAP上にリンクを貼る。

- [ ] 常設するセンサーのチャンネルリスト。加速度計、マイク、磁束計。
- [ ] PEM MAPにFilterBankへのリンクを貼り付け
完了

**Comment by MiyoKouseki** [comment]
@TTanakaTT pem MAPに反映してもらえませんか？

**Comment by yokozawa1985** [comment]
PEM mapの繁栄というissueを立ち上げます。
