### ISSUE TITLE
pemのチャンネル名案

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#48]
**改善案** どのように改善してほしいか書いてください。

前も議論した気がするけど、明文化されていない。

合意してWikiに命名規則を書いておきたい。

現状チャンネル名がカオスなので(#32 )

**Comment by MiyoKouseki** [comment]
地震計と気象計は
K1:PEM-エリア名_設置場所名_センサー名_自由度_OUT_DQ
で命名しています。

例 K1:PEM-IXV_GND_TR120Q_X_OUT_DQ
例 K1:PEM-IXV_WEATHER_TEMP_OUT_DQ

**Comment by kokeyama** [comment]
おんどとりは
K1:PEM-HUMIDITY_BOOTH_PSL
のように
K1:PEM-(センサ)_(場所１)_(場所２)
になってます。

チャンネル名は、大きなくくり→小さなくくり　なので
個人的には
K1:PEM-(センサ)_(場所１)_(場所２)
であるべきだと思う

一方、K1:PEM-(場所)_...
のほうが良いという意見もある（同じ１箇所のいろいろなセンサのチャンネル名をdvなどで指定しやすい）

あとモデル名はラックの場所がついている気がする

**Comment by yokozawa1985** [comment]
僕が中心となって設置したPEMは
K1:PEM-(場所)_(センサ)_(場所2)という命名法を使用しています。
これはkokeyamaさんの中にある通り、PEMを見たいときには、加速度計を見たい!というよりはこの場所の異常を見たい!というmotivationが強いというenomoto, miyo案を採用してこうしています。
変えるならば今年がラストチャンスだと思いますのでじっくり議論して変えたいです。

**Comment by kokeyama** [comment]
利便性だけでチャンネル名規則をいちいち変えていたらめちゃくちゃになってしまうので、ルールどおりにするべきだと思います

a. 便利だがルールにのっとっていないチャンネル名　→　使っている人に便利で効率もいいが使ったことがない人には見つけるのが難しい
b. 多少不便だけどルール通りのチャンネル名　→　しょっちゅう使う人には不便だがはじめて使う人にもやさしい

PEMは比較的見つけやすいので、a.のデメリット部分は少ないかもしれませんが、それでも全体のことを考えると、プロジェクト全体でcoherentであるべきだと思います

**Comment by MiyoKouseki** [comment]
利便性よりもルールを守るほうが良いと思います。


センサー名についてですが例えば
違う型番でも地震計全てに「SEIS」とつけるようにしますか？

型番が違うとキャリブレーション値をチェックする場合、Wikiなどのテーブルを参照する手間がかかります。

ですが、ユーザーからしてみたら型番は気にしないので、SEISだけの方がわかりやすい。

今は自分が管理しやすいように、_SEIS_だけだったのを_tr120q_と_tr120c_というふうに区別し直しました。

SEISだけにするというのがルールであれば、それに従います。

**Comment by neouniverse** [comment]
エンドユーザー的にはK1:PEM-SEIS_*、K1:PEM-MIC_*、みたいなのがわかりやすくていいと思う。
チャンネル名長くなっていいなら型番"も"入れてもいいと思うけど
"tr120q"をgoogle先生に聞いても地震計にたどり着けなかったので
型番だけだと知らない人は本当に分からないと思う。

あと個人的には今のdvとかdiagguiでPEMをクリックすると2-30個場所がずらっと並ぶのは
操作性の悪さとも相まって利便性も一概に良くなっているとは言えないと思ってます。

**Comment by yokozawa1985** [comment]
1. K1:PEM-(センサ)_(場所)_・・・(ondotori方式)
2. K1:PEM-(CS/EX/EY)_(センサ)_(場所)・・・(LIGO方式)
3. K1:PEM-(場所)_(センサ)_・・・(yokozawa方式)
のどれかに絞られていますね。
僕の場合は、dvの利便性を考えて(POPはPOPで固まっている等)そうしたのですが、現在の冗長さがネックとなってしまう可能性も高いというわけですね。。

**Comment by MiyoKouseki** [comment]
4. K1:PEM-(エリア)_(設置場所)_(センサー名)_(DOF)  (VISを参考にしたMiyo方式)

VISは、K1:VIS-(鏡名)_(ステージ名)_(センサー名)_(DOF)

**Comment by MiyoKouseki** [comment]
個人的には、全てのpemのセンサーはfeed forward用のwitnessセンサーになるのが理想なので、どのエリアのどの場所のどういう方向の外乱を測定しているかという、VISのような制御目線な命名が好きです。

**Comment by yokozawa1985** [comment]
Miyoさん、抜けておりました。。申し訳ございません。

**Comment by yokozawa1985** [comment]
明日、PEMとgokagraのメーリスに投げてみます。
引き続きご意見お待ちしております。

**Comment by koji-n** [comment]
個人的に、これは最適解というのはない気がします。
自分が使う場合を考えても、センサー毎に見たい時もあれば、場所ごとに見たい時もありますし。
つまり、時と場合により、「大きなくくり」と「小さなくくり」が変わってしまうということです。
というわけで、もうそのように考えるのはやめて、プロジェクト全体でcoherentであるようにつけたいわけですが、既にオンドトリ方式とVIS方式が違うので、これもなかなか、といった感じです。
とはいえ、私はcoherenceを重視し、オンドトリ方式とVIS方式(の改変型)のいずれかがよいと思います。

私が特に推すのは、VIS方式の以下のような改変型です。
- K1:PEM-(エリア)_(場所1)_(場所2)_(センサー名)_(DOF)
  - エリア: CS/EX/EY
  - 場所1: 定盤名 (PSL/IMCREFL/IMCTRANS/IFIREFL/POP/POS/TRX/TRY/etc (orこれらの短縮名)) か チャンバー名(それぞれ)
  - 場所2: 設置箇所 (TABLE/GND/PERISCOPE/PEDESTAL/CHAMBER/VACUUMPUMP/PORTABLE/etc (orこれらの短縮名))
  - センサー名: MAG/MIC/ACC/SEIS/etc
  - DOF: X/Y/Z/無指向的な単語(分かりませんでした!)

理由/コメント
1. 基本的にはVISとのcoherenceを重視。(コミッショニングでは、サスペンションとの関係を見ることが多いかな、位の理由。Miyoくんの「全てのpemのセンサーはfeed forward用のwitnessセンサーになるのが理想」とまでは思っていない。)
1. (エリア)を付けるのは、dvでPEMをクリックしたときに最初に出る数を減らすため。それでもCSは多いけど。(CSを細かく分ける用語があればよいが。一応実験室Aとかいうのがある?)
1. (センサー)を後ろに持ってくるのは、(DOF)との関係が強いから。(DOF)は後ろに来るのが素直。
1. 型番は入れなくて良いと思う。それを入れ始めるとアンプは入れないのかなどの疑問が出てくる。チャンネル名はセンサー名で十分だと思います。
1. LIGO方式は、場所(=CSとか)-センサー-場所 となっているので、個人的には気持ち悪いです。

代替案
- K1:PEM-(場所1)_(場所2)_(センサー名)_(DOF) : エリアは本質ではない。
- K1:PEM-(センサー名)_(場所1)_(場所2)_(DOF) : オンドトリ方式。これならエリアはいらない。

以上が私の意見ですが、どんな形にせよ、オンドトリ方式とVIS方式(の改変型)のいずれかにすべきだと思います。

**Comment by koji-n** [comment]
あと、全体に意見を聞くのはよいですが、それぞれの長所と短所をこちらでまとめておかないと、判断基準がなく「なんとなく」という意見が集まり、判断に困ることになるんじゃないかと思います。

**Comment by neouniverse** [comment]
VISの場合あれは場所の名前と言うよりは
IPだけでもTMだけでもダメなのです。的な感じで全段揃って初めて意味をなす
一つの装置(サブサブシステム)の名前なんじゃないかと思う。
少なくとも私はVISに関してあれを場所だと認識したことは無かった。

おんどとりもPEMサブシステム内の坑内温度をモニタするサブサブシステムであり、
湿度をモニタするサブサブシステムであるという思想で名付けられているのだと思う。
(サブサブシステムと言ってしまうと防振装置名の前にTYPEAとかTYPEBが入ったり
TEMPERATUER, HUMIDITYの前にONDOTORI的なのは入れないのという気もするが...)

なのでPEMの思想として地面振動・磁場・音響・温度・湿度・気圧をなどを全て引っくるめて
ある場所(PSLとかEXVなど)を多角的にモニタするのが一つのサブサブシステムなんだと定義するなら
K1:PEM-PSL, K1:-PEM-EXVでも良いと思う。

ただし本当にそう言う思想で動くなら今みたいに地震計担当、磁束計担当みたいに人を充てるのではなく
PSL担当、EXV担当みたいなコンタクトパーソンがあって然るべきだと思う。
少なくともVISならVIS-BSは誰に、VIS-ETMXは誰に聞けば
現場レベルの擦り合わせができるかみんなが知っている。

どことは言わないけどコンタクトパーソンが機能しなかったり
誰だか良く分からないサブシステムやサブサブシステムは
システム外の人に迷惑や不便を強いることになる。

今そういう人の宛て方になっていないのは結局のところ多くの人が坑内全域の
地面の揺れをモニタするサブサブシステムが地震計であり、
音響雑音をモニタするのサブサブシステムがマイクだ
という認識だからじゃないかなぁ。

**Comment by koji-n** [comment]
なるほどー。
センサー毎に担当者を決めている現状に合うようにチャンネル名を付けるべきという考え方もありますね。
(個人的には、地震計以外はそのようにはっきり決まっているような気はしませんが。
コンタクトパーソンをはっきりさせるべきというのは同意です。)

ただ、チャンネル名とコンタクトパーソンをリンクさせることがそこまで必要かと言われると、個人的には微妙です。
例えば、私はこれまでチャンネル名からコンタクトパーソンを連想したことはあまりない気がします。
それよりもやはり、思想が重要なのだと思います。
これは個人的なものだと思うので上では書きませんでしたが、思想という意味では、やはりPEMは「ある場所を多角的にモニターする」ものなように思います。
それはPEMの利用方法(の一つ)が、コミッショニングの際に、ある場所(PSLやEYC、EYV等)の環境雑音となにかの信号(例えばh(t)。それまでのステップではMZMやETMYのローカルセンサー等も)のカップルを見つけてその場所(PSL等)の調査をするというものな感じがするからです。
ようやくその兆候が見えてきたところだと思います。

その上で、なぜ現状はセンサー毎に担当者を決めている(傾向にある)かというと、それが上のような思想を実現するために効率が良いからだと思います。
効率の問題でそうなっているものを、チャンネル名に反映する必要はないんじゃないかなー、というのが私の意見です。
(逆に、チャンネル名をエリアから始めたからといって、現状のタスクアサインの方法を変える必要もないと思っています。どこにあろうと、あるセンサーについてすり合わせをしたければ、その担当者に話をすればOKなはず。)

いずれにせよ、やはりこれはオープンクエスチョンでしょう。
あれこれと議論するのは、いろいろな人の意見が聞けて個人的には楽しいですが、それよりもある程度議論した段階で、(パーフェクトではないにせよ)バシッと決めてしまって、実務に移るべきだと思います。
私は、オンドトリ方式とVIS方式(の改変型)のいずれかであれば問題ないと思いますが、できれば場所は、上で書いたように大きいくくりと小さいくくりの2つあった方がよいと思ってはいます。

**Comment by yokozawa1985** [comment]
open questionにしました。
僕のメールに返信いただく形でコメント追加してください。

**Comment by kokeyama** [comment]
- VIS_XXX_TM...  の XXX  は場所ではないに同意です
- 意見をつのるはいいけど、よくわかってない人を集めて多数決するのはやめたい

**Comment by koji-n** [comment]
@kokeyama さん、皆様、

> * VIS_XXX_TM...  の XXX  は場所ではないに同意です

なるほど。
まあ、後出し気味で申し訳ないですが、自分の案の(場所1)は(サブサブシステム)だと理解して頂いても良いです。
というのも、サブサブシステムという単語が自分の中になかったので「場所」と書きましたが、気持ち的にはサブサブシステムという意識があった気がします。
「(場所1) := AROUND(サブサブシステム) 」で、AROUNDが省略されているという理解でもよいかもしれません。

しかし、だとすると、自分は以下の kokeyama さんの案を誤解していたようです。

> 個人的には
> K1:PEM-(センサ)_(場所１)_(場所２)
> であるべきだと思う

kokeyama さん的には、上記の(場所1)(場所2)には、具体的にはどういうものが入るのでしょうか。

> * 意見をつのるはいいけど、よくわかってない人を集めて多数決するのはやめたい

同意です。

**Comment by kokeyama** [comment]
おんどとりの場合は、
場所１として、
- BOOTH（クリーンブース内
- FIELD（トンネル内だがブースの外）
- RACK（DGSラック）
- MOZUMI (CTRLルーム横サーバー室)
 の4種類があります。

場所２は、さらにピンポイントです。以下のような分け方です
BOOTH_PSL
BOOTH_PR2
BOOTH_EXV   (tunnel 2F)
BOOTH_EXC1F  (exc booth 2F)
BOOTH_EXC2F  (exc booth 1F)
BOOTH_EXA
...
FIELD_CENTER
FIELD_MCF
...
RACK_IOO
RACK_IX
....

といった具合です。たとえばPR2といっても、ラックと、ブースと２箇所あるので、(場所1)で設置箇所の性質を指定しその後ピンポイントしているということです。

これは日本語と英語の住所をあらわすときに例えられますね。日本語は、国→県→市→区→番地といきますが、英語だと真逆です。おんどとりは、K1:PEM-(センサ)_(日本語住所方式)ですね。

**Comment by kokeyama** [comment]
ps. (場所2)  はVIS名ではなくて、チャンバー名 (または場所の名前があれば場所、center  など) です。

**Comment by koji-n** [comment]
ありがとうございます。
よく分かりました。
私は、BOOTHなどが番地(違う市にも同じ名前がある。本町とか。)で、PSLとかが県名(同じ名前はない)だと思っていたので、そこに勘違いがありました。
とすると、やはり、同じ "K1:PEM-(センサー名)\_(場所1)\_(場所2)\_(DOF)" でもkokeyama案(オンドトリ形式)とkoji-n代替案2は違うものですね。
koji-n代替案2は、オンドトリ形式に沿うという意図で書いたのですが、そこが違うと分かったので取り下げます。
このissueの最終目標である、Wikiに命名規則を書くときには、ある程度具体例も書いておかないと誤解を生むということが分かりました。

**Comment by koji-n** [comment]
どうでもよいですが、本町は番地じゃなくて町ですね。多分。気持ち的には大字くらいですが。
区にして、例を中区にした方が分かりやすかったかもしれません。
いずれにせよどうでも良い。

**Comment by kokeyama** [comment]
たしかに、一般の場合にBOOTHとPR2どっちがおおきいくくりかといわれると、どっちとも取れるような気がしますね。おんどとりの場合は、温度測定点は場所にのみ依存しているので、物理的に住所として広い領域のほうを(場所1)にとったんだと思います。　（例：MOZUMI_SERVER）

> TEMPERATUER, HUMIDITYの前にONDOTORI的なのは入れないのという気もするが...
の点ですが、確かにそうで、
K1:PEM-ONDTR(?)_BOOTH_PR2_TEMPERATURE
のほうがよかっただろうかと思うことはあります。
この場合、TEMPERATUER/HUMIDITY  が DOF  扱いですね。

**Comment by kokeyama** [comment]
あ、上、>  以降ぜんぶ引用になっちゃった。

**Comment by yokozawa1985** [comment]
まだ意見がまとまっていないかもしれませんが、
K1:PEM-(sensor)_(場所1)_(場所2)_(DOF)
をルールとして話を進めていきます。
ルール決めの場をkagra wikiへと移動いたします。

特に問題ないようでしたら、closeして、チャンネル名を変えるissueの立ち上げ。

**Comment by yokozawa1985** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/CHName

**Comment by kokeyama** [comment]
いいと思います。

**Comment by MiyoKouseki** [comment]
このルールでいいと思います。

**Comment by koji-n** [comment]
基本的には良いと思いますが、いくつか質問/コメントがあります。

1. 「ルール決めの場をkagra wikiへと移動する」とのことですが、もうこれで決定というわけではないのでしょうか。
まだここにはいなかった人の意見を聞く期間を設けるということでしょうか。
2. wikiの(場所1)ですが、ちぐはぐな気がします。チャンバー名なのかサブサブシステム名なのか等が統一されていないように思えます。EXCなどはチャンバー名ですが、IMCはサブサブシステム名です。どちらかに統一する方向にしたほうが良いと思います。特にPRやIMCなどは、チャンバー/ブースが離れていたりするので、PEMのチャンネル名としては微妙な気がします。
3. 最終的にルールを決めた後、簡単でもよいのでドキュメントを残したほうが良いと思います。今回、明確に結論を出せなかったように、この問題はオープンクエスチョンなので、ルール決定後に異議を唱える人がいるかもしれません。そのような権利はあってしかるべきですが、それにいちいち付き合っていたら時間がもったいないので、そんな人には、意思決定の過程 (どのような案を検討して、どのようなトレードオフスタディをして、最終的に誰が責任を持って決めたのかなど) が明確に書かれているドキュメントを提示するのが楽だど思います。

**Comment by koji-n** [comment]
ちなみに、KAGRAのOutput tableの名前は以下のように決まっているはずです。
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/IOO/OutputTables

**Comment by koji-n** [comment]
> 大筋では決定だと思いますが、微調整が必要な部分があると思ったので、議論の場をwikiに移したという表現をしました。

なるほど。

> 場所1はチェンバー名でもサブシステム名でもなく、場所として認識しております。

場所だとして、やはり私にはこれらのものが選定された理由がよく分かりませんでした。
IMCとEXCが同列な気はあまりしませんし、IX0とRACKはどちらもデジタルラックなのではないでしょうか。
また、上でも書きましたが、PRやIMCなどは、チャンバー/ブースが離れているので、場所としては微妙だと思います。

> ここの場での議論を含めて、documentに残しておきます。

よろしくお願いします。

**Comment by MiyoKouseki** [comment]
横澤さんが作ったWikiページの内容を元にして、チャンネル名リストの下部に加筆しました。
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Channels#Channel_Name_Definition

名前だけではなく、それが意味するものを横に書いたので、おかしいところはここでコメント下さい。

**Comment by yokozawa1985** [comment]
長野さんのご指摘の通り、EXCとかはおかしい気がしたので、
総称して、IX, IY, EX, EYとするのが自然だと思いました。
IX0, IXC -> IX
IY0, IYC -> IY
place1 mapをすぐに作成いたします。

**Comment by yokozawa1985** [comment]
Miyoさん、書き換えてみました。確認お願いします。

**Comment by yokozawa1985** [comment]
place1のマップを作成しました。

http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/CHName?action=AttachFile&do=view&target=PEM_channel_name_place1.pdf

**Comment by yokozawa1985** [comment]
僕個人的にはおんどとりはそのままのチャンネルネームでいいと思っております。

**Comment by kokeyama** [comment]
了解しました。

もし変えたほうがいいという意見ありましたら再考するのでおしらせください。

**Comment by MiyoKouseki** [comment]
> k1:PEM-ONDTR(?)_RACK_PX1_TEMPERATURE
(センサー名がおんどとり、DOFがTEMPERATURE)

がいいです。

ONDTRとWEATHERになれば、オンドトリとGIFの気象計が区別しやすいので、このルールがいいです。

その場合、DOFは
TEMPERATURE
HUMIDITY
PRESSURE
で良いでしょうか？
今はTEMP、HUMD、PRESという略記になってます。

**Comment by koji-n** [comment]
私もMiyoくんに賛成です。
今後、気象計を入れていくのなら、何のセンサーで取っている温湿度なのかを区別する必要があるはずです。
DOFは、統一されていればどちらでもよいと思いますが、略記の方でも分かる気がするので、どちらかといえばチャンネル名が短くなる略記のほうが良さそうです。

**Comment by MiyoKouseki** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Channels#Channel_Name_Definition
wo kakikae masi ta.

**Comment by kokeyama** [comment]
了解です。チャンネル数が多いので、時間がかかりそうなので、年が明けてからどっかのタイミングで変更します。

**Comment by koji-n** [comment]
@MiyoKouseki くん、
arigatou gozaimasu. Totemo miyasui desu!

皆様、
ところで、Place1ですが、I[E]X(Y)は個人的にはしっくりしません。
特に、エンドは、チャンネル名だけ見ると、広すぎてよく分からなくなる気がします。
例えば、ACC_EX_CHAMBER だとEXCなのかEXAなのかEXVなのかEXTなのか、不明です。
なので、やはりEXC/IXC等はあった方がよいと思います。
IX0等のラックに置く場合は、RACKを使えばよいのだと思います。
EXは、EXCとEXAの間のどこかのダクトに加速度計を置くなどの、限定的な用法しか思いつきません。
同様に、EXAではなくPCALXが使われているのもしっくり来ません。
例えば、EXAまわりのブースにオンドトリを置くとして、それは別にPCALだけでなく、NAB等のモニターでもあると思います。
どう思われますか？

**Comment by kokeyama** [comment]
おんどとりの場合は、
ブース内だと BOOTH_EXA,
ブース外だと FIELD_EXA (このセンサーは、ないですが、もしつけるとしたらそういう命名）
ラックだと RACK_EX0
とかに現状なっています。

（そういえばエンドには BOOTH, RACK 以外に FIELD にはおんどとりは設置してない）

**Comment by kokeyama** [comment]
あ、逆だった。BOOTH_EXA　がないです。
FIELD_EXAがあります。

でもこれEXAのブース内だから大変更するときにBOOTH_EXAに変更します。

**Comment by yokozawa1985** [comment]
optical tableがある場所は特別な名前、あとは場所という風にしています。
ですのでPCalやTMSがあって、EYCやEYAがないのはそのためです。
EX_EXC_CHAMBER_Z
などになります。
(EXC_CHSMBER)がplace2に対応していています。
KAGRAは他の検出器と違ってチェンバーが多いので、place1にチェンバー名を加え始めたら
発散します。
定盤は僕の中では特別なので場所と混同しております。

**Comment by yuzuri** [comment]
@yokozawa1985 さんの作ってくれたPEM_channel_name_place1.pdfはとても見やすくわかりやすいです
daily summaryからリンクも貼りたいので、JGWdocの方にもアップロードしていただけないでしょうか

あと @MiyoKouseki くんが作ってくれたwikiページもわかりやすく助かっております

**Comment by yokozawa1985** [comment]
FIELDとBOOTHがPlace1とPlace2に存在して、被っていますが、重複は許容しますか？
"基本的には"おんどとりとマイクのルールです。Place1もPlace2もFIELDになることはないです。
  Place2 にある、ONTABLE とTABLEの違いは何でしょうか？特に無いなら一つにまとめて良いでしょうか？
同じです。TABLEで統一することにいたします。
  SENSOR、PLACE1、PLACE2、DOFのなかに、「AAA_BBB」という名前は許容しますか？
あると思います。EX_EXC_CHAMBER_Zとか、EY_EYA_BEAMTUBE_Zとかがあり得ると思います。
  今の自分の認識ですが、Place1はArea名(横澤MAPの名前)で、Place2はLocation(設置場所)というのは合っていますか？Place1、Place2という呼び名は議論がボンヤリするので、名前を決めたいです。
Area名、location名という名前で呼んでいただいていいと思います。

**Comment by yokozawa1985** [comment]
IFI/IMMT/PRの線引き
OMC->OMMT/OFI/OMC/ASにするのか
POX,POY
は議論課題として残しておきます。今年度はこれ以上PEMが増えないと思いますが、
来年度以降は重要度を考慮して足していきますので。

**Comment by yokozawa1985** [comment]
yuzuさん
JGWDocのせました。
チャンネル名変わったら、Daily summary pageの更新をお願いします。

**Comment by MiyoKouseki** [comment]
大きな命名ルールは
K1:PEM-(SENSOR)_(AREA)_(LOCATION)_(DOF)
に決まったので、
今議論されている、小さな命名ルールは、
既に「各サブシステムで定義されたもの」に従うのはいかがでしょうか？



以下にまとめます。

SENSOR
- [ ] PEMが管理しているセンサーの種類がここに該当する。

AREA
- [ ] エリア名が該当する。三代木さんが定義。[here](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=1110)

LOCATION
- [ ] センサーが設置されている構造物の名前が該当する。
クリーンブースは三代木さんが定義。[here](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=1662)
光学定盤はIOOグループが定義。[here](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/IOO/OutputTables)

DOF
- [ ] 複数個の出力信号を持つ場合、それぞれの名前が該当する。

**Comment by MiyoKouseki** [comment]
LOCATIONにラック名が抜けていました。
ラック名の定義はどこを引用すればいいでしょうか？@neouniverse

**Comment by MiyoKouseki** [comment]
このIssueが長くなって、まとまりにくくなってきたので、そろそろCloseしたいです。

とりあえず上記の方法で命名してみて、
一意にきまらない場合や、例外が生じたら、
それらをIssueに切り分けるのはいかがでしょうか。

**Comment by koji-n** [comment]
@MiyoKouseki 案はルールっぽくて良いですね。
「プロジェクト全体でコヒーレント」な感もありますし、リファレンスがあるのが好きです。
(このFCLの資料は初めて見ました。)
ただ、Area名について、FCLの定義(Word/Acronumの列)をそのまま使うと流石に分からなくなるので、それっぽいものに置き換えるのはどうでしょう。
LLAB -> PSL 等です。
見た感じ、よく使いそうなものはすぐに置き換えられそうです。
「プロジェクト全体でコヒーレント」という観点からすると、LLAB等単語はほとんど使われていない気がします。
あと、こうすると現状のものを結構大きく変えなくてはならないので、きちんと周知しないと混乱を生みそうでそこが怖いです。

> このIssueが長くなって、まとまりにくくなってきたので、そろそろCloseしたいです。

賛成です。

> とりあえず上記の方法で命名するということに決定してCloseし、
> もし一意にきまらない場合や、例外が生じたら、
> それらを新しいIssueにするのはいかがでしょうか。

これも賛成です。

**Comment by MiyoKouseki** [comment]
>ただ、Area名について、FCLの定義(Word/Acronumの列)をそのまま使うと流石に分からなくなるので、それっぽいものに置き換えるのはどうでしょう。
LLAB -> PSL 等です。
見た感じ、よく使いそうなものはすぐに置き換えられそうです。

ぱっと使いそうな場所に関してPEM名前をつけてみました。
横澤さんのドキュメントをVer2にしてUploadしました。
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9553

LOCATIONに関してはまだ手を付けていません。

**Comment by neouniverse** [comment]
> ラック名の定義はどこを引用すればいいでしょうか？

ちゃんと定義されたものは無いのが現状です。
基本的には入っているIO chassisが繋がっているRTFE名(からk1を取り除いたもの)が
呼称としてはもっとも広まっていると思います。

ただし、
- 当初の予定とラック構成(台数)が変わってしまったり(IOO, PR0)
- フィールドにも計算機ラックを置く必要があったり(フロント2F前室・エンド2F前室)
- 回路のみのラックが必要になったり(Type-A防振室、両エンド1Fなど)
- 一点物なのでラック名末尾0をが省略されていたり(IMC, LSC, OMCなど)

呼称に揺れがあります。

以下各ラックのユーザーと話していて最も通じると感じている呼称です。

LSC (k1lsc0)
ASC0 (k1asc0)
ASC1 (k1asc1) ラック自体未設置、IO chassisが必要か回路だけになるか未定
ALS0 (k1als0)
ALS1 (k1als1) 今はIO chassis無しで回路のみインストール
IOO (k1ioo) 各所で不具合がありバージョンあげるたびに大変なので将来的にはk1ioo0に変えたい by DGS
IOO1 (k1ioo1) さらに回路のみのIOO2を作ってIOO, IOO1の密度を下げたい by AEL
PR3 (k1pr3)
PR2 (k1pr0) 当初は計算機1台でPR2, PRMを制御予定だったが状況が変わったのでk1pr2にしたい by DGS
PRM (k1prm)
BS (k1bs)
SR2 (k1sr2)
SR3 (k1sr3)
SRM (k1srm)
OMC (k1omc0)

IX0 (k1ix0) Xフロント1F
IY0 (k1iy0) Yフロント1F

ICV? (計算機ラック) フロント2F前室。なんて呼んで良いかわからない。
IX1 (k1ix1) Xフロント2F防振室。IXV1と呼ばれる事も
IX2 (回路のみ) Xフロント2F防振室。IXV2と呼ばれる事も
IY1 (k1iy1) Yフロント2F防振室。IYV1と呼ばれる事も
IY2 (回路のみ) Yフロント2F防振室。IYV2と呼ばれる事も

PX1 (k1px1) X-arm 500m地点。1500mはPX2, 2500m?はPX3の予定

EX0 (k1ex0) Xエンド1F
TMSX (回路のみ) 既にEY0-3までナンバリングされた後だったのでこう呼んでいる

EX1 (計算機ラック) Xエンド2F前室
EX2 (k1ex1) Xエンド2F防振室。EXV1と呼ばれる事も
EX3 (回路のみ) Xエンド2F防振室。EXV2と呼ばれる事も

EY0 (k1ey0) Yエンド1F
TMSY (回路のみ) 既にEY0-3までナンバリングされた後だったのでこう呼んでいる

EY1 (計算機ラック) Yエンド2F前室
EY2 (k1ey1) Yエンド2F防振室。EYV1と呼ばれる事も
EY3 (回路のみ) Yエンド2F防振室。EYV2と呼ばれる事も

**Comment by MiyoKouseki** [comment]
Ver2に、Locationに該当するチャンバー・テーブル・DGSラックを追加しました。ver3です。

@neouniverse
ラックの位置と名前を書き加えてもらえないでしょうか？(1カロリーメイトで)

https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9553

**Comment by koji-n** [comment]
@MiyoKouseki 
すばらしい資料ですね！
よりすばらしくするために少しだけ。
- p10の定義をp6-9に直接書き込むのはどうでしょう。
  - (ちなみに、私は、DLABはOMCで良いと思います。)
- まだ場所が決まっていない(?)からかもしれませんが、p14にPOYがないですね。(もし決まっていないので書いていないなら、テーブルの場所はまだ完全には決まっていないとかって書いておけば良いんじゃないでしょうか。)
- p16の意味は?
- pdfの方が最新版ではなさそうです。

**Comment by neouniverse** [comment]
なるほどpdfしか見てなかったからどこに書けと言われているのか全くわからなかった
Thanks -> @koji-n 


> (1カロリーメイトで)

そんな通貨単位は存在しない

**Comment by MiyoKouseki** [comment]
@neouniverse PEMMAPと同じ向きに扉があるので多分正しいと思います。

整理しました。Ver5です。
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9553

これまでの内容と合わせてWikiにまとめました。
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Channels#Channel_Name_Definition


例えば、存在するかわかりませんが、PR2のチャンバーの加速度計は、K1:PEM-ACC_BS_CHAMBER_PR2_Zになります。
「！？」ってなりますが、ルールではそうなります。

**Comment by yokozawa1985** [comment]
みなさま、ありがとうございます。
おそらく違和感があるのは、PR2とSR2チェンバーに関するPEMのみだと思います。
これを元に1/5-6に大幅アップデートを計画して見ます。

**Comment by neouniverse** [comment]
> これを元に1/5-6に大幅アップデートを計画して見ます。

dataviewer, diagguiなどNDS経由のツールから過去データ一切見れなくなるので
年末年始に坑内温度とかモニタしてた人たちに変えて良いか要確認です。

あと卒論間近な人とかも自力で読み出せる形式で先にデータを落としておくことをお勧めします。

**Comment by yokozawa1985** [comment]
> dataviewer, diagguiなどNDS経由のツールから過去データ一切見れなくなるので
> 年末年始に坑内温度とかモニタしてた人たちに変えて良いか要確認です。

ありがとうございます。確かにそうです。
chief meetingで議論いただいた後の方がいいかもしれませんね。

**Comment by MiyoKouseki** [comment]
新しいチャンネル名を決めるためにスプレッドシートを用意しました。
https://docs.google.com/spreadsheets/d/1EIZCBXdf2wDwFqenr5S71jXwEpNRyjVgdeh0v0K3mBU/edit?usp=sharing

SENSOR、AREA、LOCATION、DOF、Suffix、らを
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9553
を見ながらご記入ください。

黒塗りは昔に作られたゾンビチャンネルです。
もう使わないよ、というチャンネルは黒く塗ってください。

とりあえず地震計とかオンドトリをかわかる範囲で埋めました。
他のセンサーは設置場所などがよく知らないので、ご存知の方のご協力お願いします。

上記のスプレッドシートに書かれている現在のOldチャンネルはchans/daqのiniファイルと、target/k1rack/dbから抜き出しました。抜けがあれば教えてください。

**Comment by yokozawa1985** [comment]
<img width="1945" alt="2019-01-04 15 58 49" src="https://user-images.githubusercontent.com/6629732/50677586-fe7a7b00-103d-11e9-9365-8232422cfddd.png">

**Comment by yokozawa1985** [comment]
<img width="1024" alt="2019-01-04 16 28 33" src="https://user-images.githubusercontent.com/6629732/50677599-14883b80-103e-11e9-9015-92a043da11af.png">

**Comment by MiyoKouseki** [comment]
とりあえずここのIssueはCloseします。
続きは　#77 で
