### ISSUE TITLE
PEMの今後

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#49]
**改善案** どのように改善してほしいか書いてください。

PEMのWikiによれば、センサーのインストールとメンテナンスがpemのタスクなので、現状維持をすることになっています。

pem injectionをするのでしょうか。そうなれば、いつするのでしょうか。

今後PEMが何をするかよくわかりません。

**Comment by kokeyama** [comment]
長期的にはDetcharと統合されていくんだと思います。O3にむけては、PEM/detcharに要求される情報は data quality flag です。風、地面、温度、グリッチ、ライン（広い意味での干渉計のノイズレベル）の情報を統合して deta quality 情報をデータ解析側へ提供する必要があります。具体的にflagの判断基準、どのように情報を提供するかはまだはっきりしていません。LIGOはDMTを使ってその情報をlow-latencyで発行していますがKAGRAでDMTを使って同様にするかは要検討です。

**Comment by yokozawa1985** [comment]
実は、wikiのscopeを掲げたのは去年の6月くらいで、そこからKAGRAの状況は変わっています(いや正しい言葉で言うとまったくかわっていません。)SEO(主にO橋先生)との議論が必要ですが、少なくともdata quality flagとPEM injectionを用いたノイズハンティングまでは広げていけたらと思っております。

**Comment by yokozawa1985** [comment]
closed
