### ISSUE TITLE
Armにどんなpemがいついるか？

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#5]
内山さんからsuggestion
水滴などの影響をモニターするためのArm PEMがなく、
取り付けることができるかの相談を受けた。

**Comment by yokozawa1985** [comment]
2018/12の段階では、optical tableのPEM設置が完了したところ。
その後chamber, CSダクトの後になると考えられる。

また、ラックがいつどこに設置されるかも問題となる。
散乱光ノイズが現れてくる頃に再度議論立ち上げ。

**Comment by MiyoKouseki** [comment]
あとで議論するのでとりあえず、Close。
その時が来たら新しいIssueができるでしょう。
