### ISSUE TITLE
BAKファイルもSVNで管理されてしまっている

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#51]
**問題について** 何が問題か書いてください
Who made these files?
> $ userapps
$ cd pem
$ svn status
?       k1/medm/K1PEMIX0_OVERVIEW.adl
?       k1/medm/K1PEMIX0_OVERVIEW_BAK.adl
?       k1/medm/K1PEMIY0_OVERVIEW.adl
?       k1/medm/K1PEMIY0_OVERVIEW_BAK.adl
?       k1/medm/newDisplay.adl

**正しい状態** どうなっているべきか書いてください
Please commit to SVN.

**Comment by MiyoKouseki** [comment]
とりあえず、実際に使っているファイルだけをAddしてCommitしました。revision 2369です。
>[controls@k1ctr7 pem]$ svn status 
?       k1/medm/K1PEMIX0_OVERVIEW.adl
?       k1/medm/K1PEMIX0_OVERVIEW_BAK.adl
?       k1/medm/K1PEMIY0_OVERVIEW.adl
?       k1/medm/K1PEMIY0_OVERVIEW_BAK.adl
?       k1/medm/newDisplay.adl
[controls@k1ctr7 pem]$ svn add k1/medm/K1PEMIX0_OVERVIEW.adl 
[controls@k1ctr7 pem]$ svn add k1/medm/K1PEMIY0_OVERVIEW.adl 
[controls@k1ctr7 pem]$ svn commit -m 'Add ix0,iy0 overview'

残りは、バックアップファイルと謎のファイルなので、確認したのち消しておいてもらえますか？
> [controls@k1ctr7 pem]$ svn status 
?       k1/medm/K1PEMIX0_OVERVIEW_BAK.adl
?       k1/medm/K1PEMIY0_OVERVIEW_BAK.adl
?       k1/medm/newDisplay.adl

**Comment by yokozawa1985** [comment]
三代様

すみません、お手数をおかけいたしました。

横澤　孝章

**Comment by yokozawa1985** [comment]
消しました。review待ち

**Comment by neouniverse** [comment]
*_BAK.adlはMEDMで編集すると自動生成されてしまうし(作られないようにする方法は知らない)
newDisplay.adlは新規ファイル作りかけて変な閉じかたすると残ることがあるので
編集ユーザーが増えてくるとちゃんと消すのを徹底するのは難しいと思う

ignoreリストに追加してしまえばどうでしょう？

**Comment by MiyoKouseki** [comment]
いいですね。楽です。

それはSVN全体に反映しますか？

**Comment by neouniverse** [comment]
確認してみたらVISとかCRYとかが既に個別に設定してたので
userapps/release/pem以下のみ設定する方が良さそう。

**Comment by MiyoKouseki** [comment]
pem以下で*BAK.adlを無視するように設定しました。

### MEMO
無視したいディレクトリに行って、カレントディレクトリの*BAK.adlを無視する。
>svn propset svn:ignore *BAK.adl .

設定の確認
> $ pwd
/opt/rtcds/userapps/release/pem
$ svn propget -R svn:ignore .
common/medm - *BAK.adl
k1/medm - *BAK.adl

**Comment by MiyoKouseki** [comment]
Close
