### ISSUE TITLE
Github educationの導入

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#54]
**問題について** 何が問題か書いてください
#27 このGitHubが公開になっている。

**正しい状態** どうなっているべきか書いてください
Github educationを使って、最大2年間非公開にする。

.ac.jpでのGitHub accountが必要。

これに移行しても良いかのご意見をお願いします。
また、ご面倒をおかけいたしますが、.ac.jp以外のメールアドレスでGitHub accountを
作成している人は、対応をお願いします。
宇宙線研究所計算機のアカウントを持っている方は、icrrメールが使用できます。

**Comment by yokozawa1985** [comment]
https://yotalabo.org/github-education/

**Comment by yuzuri** [comment]
非公開にしないといけない理由はなんでしょうか？
各人の名前が公開されてるっていうのはそこまでまずい気もしないような・・・
コードが公開されてまずいなら、githubで管理するのはそもそも変な話な気もします

非公開にしてしまうと、第三者にチェックしてもうらうときやなんかコメントをもらうときにその人にもアカウントを作ってログインしてもらわないといけなくなります
それが少し障壁になるかなと気になっています
(個人的には.ac.jpのアカウントを作って今のアカウントと使い分けるのが大変かなと思ってます)

**Comment by MiyoKouseki** [comment]
> 各人の名前が公開されてるっていうのはそこまでまずい気もしないような・・・

自分は大丈夫です。ただ、全世界に発信するのはまずかな？と思いました。個人名やKAGRA坑内の様子等。

> コードが公開されてまずいなら、githubで管理するのはそもそも変な話な気もします 
> (個人的には.ac.jpのアカウントを作って今のアカウントと使い分けるのが大変かなと思ってます)

確かにそうです。個人的には、公開することで得られるメリットのほうが大きいと思ってるので、同意です。


@yokozawa1985 どうするか決めてもらえませんか？

**Comment by yokozawa1985** [comment]
今週末まで皆さんの意見をもう少し募ってそのままcloseにするのか、移行に向けて新しいissueを作るのかを決めます。引き続きご意見お願いします。
KAGRAの状況はklogでも詳細に報告されていますし、よりデリケートな議題が増えてきたらissueを立ち上げ直すがいいと思っております。

**Comment by koji-n** [comment]
私も個人的には、別に非公開にする必要はないのではないかと思います。
このリポジトリーのREADMEによると「タスク管理用リポジトリ」とあるので、どのようなタスクがあるかを隠す必要ない気がします。
たとえばKAGRA wikiも基本的には公開されています。
また、名前についてもアカウント名は公開情報なのでそれを使えば問題ないと思います。
もし、なにかシークレットな議論を行うのであれば別の場所でやるというのは如何でしょうか。

ちなみに、プライベートリポジトリに参加するのは普通のアカウントでできるはずです。

**Comment by neouniverse** [comment]
用途をタスク管理とかオープンな情報だけの共有に限定しているのなら問題ないと思う。

公開なままでやるべきでないこと
- LIGO, Virgoが公開していないツールをもらって来てここで管理やKAGRA用のアップデートをする
- 公開はされているけどライセンス的に改変・再配布が許可されてないツールをここで扱う
- OpenになってないKAGRA他のデータを使ったPEM解析結果をここで共有・議論する

今の所klogも結果乗せ放題の無法地帯なんで微妙なところですがalogとか見てると
詳細だったり本当に重要なところはパスワードのかかるldasサーバーへのリンクにするとか
ちゃんと使い分けてるっぽいのでデータ共有始まる頃にはここら辺もう少し厳しくなる気がする。

**Comment by yokozawa1985** [comment]
タスクリストの公開に大きな反対意見が無いようですのでしばらくはそのまま運用いたします。
closed

**Comment by MiyoKouseki** [comment]
#82 で作業風景が写っている。
状況や写っているものに依るが，広報に通すべきものが今後出てくるかもしれないので，ちょっとガイドライン的なものを用意したほうがいいかもしれない。

**Comment by koji-n** [comment]
「広報に通す」というのが何を指しているのかよく分かりませんが、「CPCに通す」という意味ですか。
そこまでする必要はないでしょう。
Publication policyにおいても、ログについては規定されていません。

もしその上でも、ガイドラインが必要と言われるのであれば、まずklogについてコラボレーション全体(or KSC)で議論すべきだと思うので、しかるべきところ(KSC board等)に提案した方がよいと思います。
(そうすればワーキンググループが作られると思います。)
上でも言われていますが、現在はklogについてもそのようなものはありません。
その他の場所(こことか)は、klogのルールに従うべきでしょう。
もちろん、それまでも検出等については載せないなどの最低限の自主規制はあるべきだと思いますが、それ以上のものを、少なくともここで議論することではないと思います。

ちなみに、すでに上がっているものについては、現在ルールがない以上、法の不遡及の原則を考えると問題がない見込みが大きいのではないでしょうか。

**Comment by yokozawa1985** [comment]
ただ、おんどとりだけならばともかく、作業風景や解析結果を世界中の人がみれるKAGRA unofficialな場で見せるのはどうかと思いますので、写真や図をそのまま載せるのではなく、リンクを貼るという方針にしていきたいと思っております。

**Comment by yokozawa1985** [comment]
しばらく導入しないということでcloseします。
