### ISSUE TITLE
EXVの気象計がインストールされているみたいだが、ADされた値がおかしい。

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#55]
IXVが正しやつだが、EXVはそれと違う。

![image](https://user-images.githubusercontent.com/24282734/50274695-30f27880-0481-11e9-9fd8-9b02d1f6eefb.png)

- [ ] 予備のWeatherStationと交換。
- [ ] フィルターを設定。
- [ ] SDFで値を保存。
完了

**Comment by yokozawa1985** [comment]
すぐに回収してきます。

**Comment by MiyoKouseki** [comment]
スペアの気象計をつくってそれを持っていくので、それまで待ってもらえませんか？

**Comment by MiyoKouseki** [comment]
解析棟に持って帰った。
修理して再び設置する予定。

**Comment by yokozawa1985** [comment]
ありがとうございます。
おんどとりを設置したので、別の場所に使用しましょう。
