### ISSUE TITLE
Ondotoriの追加インストール。

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#57]
Rackやfieldが増えたことによるOndotoriの追加インストール。
LLOから帰ってきてやろうと計画をしていたが、今思い出しました。

**Comment by yokozawa1985** [comment]
- [ ] 在庫のondotoriの把握

- [ ] 設置プラン(必要ならば親機も？)

- [ ] インストール

- [ ] windows PCによる設定

- [ ] epics, medmに追加

**Comment by neouniverse** [comment]
在庫はwikiに乗ってます。少人数管理なので多分正しい

**Comment by neouniverse** [comment]
と思います。(Emacsとキーバインドが違うせいで途中で送信してしまった。。。)

親機がいるとしたらあとはXエンド2Fくらい。防振室側に中継器もおいた方が良いかもです。
他は子機だけでいけるはず。

**Comment by kokeyama** [comment]
ありがとうございます、その通りです。

・在庫リスト
・マニュアル（ウインドウズでの親機子機設定、親機子機の追加、エピックスへの追加。ないのはmedmへの追加だがこれは手作業）
・電池交換履歴
はwikiにまとまっています。すべてup-to-dateな情報です。
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/DGS/Projects/Rem

今後
・Xエンド２階に親機と子機いくつかを増設する
・増やしたいところに子機を増やすだけ（いくつかおんどとりが入ってないラックがあるかも）
・親機含め在庫が十分にあるので購入必要は当面ない

**Comment by kokeyama** [comment]
電池交換履歴は英語でお願いします。交換は基本ユーザーに頼んでいます。(VIS chamber 近くのものなら該当VISチームに頼む、という具合）

**Comment by yokozawa1985** [comment]
今週末が終わるまでにはインストールプラン完了を目指す。

**Comment by kokeyama** [comment]
今週末新親機インストールするなら（時間帯にもよるけど）手伝えると思うので、日時を決めたらおしえてください。

**Comment by yokozawa1985** [comment]
今週末って、3連休ですか？？？

**Comment by kokeyama** [comment]
X end 2F の wifi はもう available でしたか？ > YamaT

**Comment by neouniverse** [comment]
Wifiは設置済みです。

**Comment by yokozawa1985** [comment]
すみません、少し勘違いしていました。
3連休は、坑内には入らず、外できることをいくつか進める予定です。インストールプランまでは完了させたいですが、実際のインストールは火曜以降に行えたらと思います。

**Comment by kokeyama** [comment]
了解です。現場に行く必要があります。

**Comment by yokozawa1985** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/ItemList
追加したラック(まだemptyのものを除く)
TMS clean area
EXV clean area
を律儀に置いていくと21子機が必要となりそうです。
回路が少ないと予想されるラック(ix0, iy0, asc0)をとりあえず削るのが横澤案です。
(もしくは、TMS clean areaはweather stationが設けられる予定なので必要ないかも)

**Comment by yokozawa1985** [comment]
| eyc2f | 52C61A1E | Yend clean booth 2F | 3 |
は、cryo clean boothの2Fということでしたね、失礼いたしました。
追加しておきます。

**Comment by yokozawa1985** [comment]
ありがとうございます。追加いたしました。(現在24個)
まずは、優先度を考慮して18個にしてみます。

**Comment by yokozawa1985** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/ItemList
16個を選択しました。
これで問題ないようでしたら、木金の空いている時間に設置したいと思います。

**Comment by kokeyama** [comment]
Tableがなんか変です

**Comment by kokeyama** [comment]
チャンネル名と関係ないですが、テントにおんどとりが２個あるのが変という意見をどっかで見たのですが、２つのテントそれぞれに１台ずつ置いていて、これでいいかと思っています。

**Comment by neouniverse** [comment]
2つのテントにそれぞれ1台という意味ではなく、
一方に1個(CRYDR)、もう一方に2個(CRYDR2と謎の1個)の計3個ありました。

謎の1個はどこの親機・中継器に属しているかわかりませんが、
液晶に温湿度は表示されていたので少なくとも稼働はしていました。
(よく考えたらシリアル番号見ればwikiに記載あるかもですね。入る機会があったら見ておきます。)

**Comment by kokeyama** [comment]
あ、それはiKAGRA後にどっかから持って帰ってきたやつだと思います。そういうやつが計算機室かどっかにもう一個あったような気もしますが、定かでないです。。

見つけたら回収してwikiを更新し本体にメモかなんかをはって在庫ボックスに戻しましょう。

**Comment by neouniverse** [comment]
テント内の1つを回収しました。

シリアル確認したらItemListページの末尾に書かれている昔使っていたもので
記載自体はBack in Storageになってました。
単に返却された場所が箱の中ではなく棚に直置きされていたというだけだったようです。

箱の中に戻してメモも貼っておきました。

**Comment by kokeyama** [comment]
ありがとうございます。

**Comment by yokozawa1985** [comment]
バードウォッチングと並行して始めました。
まずは、絶対に必要となるcenter areaに新たに追加されたrackの子機追加を開始しました。
明日、centerは完了してどちらかのエンドに行く予定です。

**Comment by yokozawa1985** [comment]
追加ラック、三代木さんからの依頼の部分は完了。
10個追加購入をしている。
epicsへのデータ入力を進める。

**Comment by yokozawa1985** [comment]
Centerの追加が完了。DAQ restartの際に今回インストールしたすべてのものを追加。
10この温度計が届いたらさらに追加。

**Comment by yokozawa1985** [comment]
おんどとりの10個は届いたが、ソフトウェアのバグとり待ち。

**Comment by yokozawa1985** [comment]
長年の時を経て完了!!
