### ISSUE TITLE
TMSエリアのPEM

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#58]
TMSエリアのPEM

現在、
optical table上に加速度計
weather station(温湿度計・気圧計)
マイク(c chamber areaと共同でいいか否か？)

のインストールで計画中。
(Xの一部は試験的に導入中)

これは欲しい、これはいらない等ありましたらコメントください。

**Comment by kokeyama** [comment]
TMSチェンバーにもおんどとりがあると良さそう

**Comment by yokozawa1985** [comment]
優先度高めでつけることを検討したいですね。

**Comment by AkutsuTomo** [comment]
検討ありがとうございます。あと、これはPEMなのかわからないのですが、真空槽についている圧力計をリモートでモニターできるようになるととても助かります。いま、直近ではEXTについているものがモニターできないので、、、昨日から真空を引き始めたのですが、いま圧力がどのくらいかとか、圧力の低下トレンドがどのくらいかとかをモニターしたいところでした。

**Comment by yokozawa1985** [comment]
それはVAC(来年度以降に本格的にテコ入れ)、もしくは井上さんマターですね。。

**Comment by neouniverse** [comment]
僕も前から少し気になっていたのですがそもそも圧力計周りのデータ取得って今どういう状況なんでしょう？

最終形はPLCに突っ込んでEPICS化するんでしょうけど
既にsshなりtelnetなりネットワーク経由で値が取ってこれる状態で
PLCが整うまで待てないので、取り敢えずモニタ・DAQできればOK的な感じなら
ジェバンニが一晩でやってくれるかもしれません。
(テンポラリなものを人に頼むとWebとかでモニタはできてもKAGRA DAQに流す所までは
やってくれない事が多く後からdataviewerとかで見れないんですよね。。。)

それともアナログ信号を取り込んでという所から始めないとダメな感じなんでしょうか？

**Comment by AkutsuTomo** [comment]
なるほど、とはいえ、必要なものなので、なんとかする方法を考えるか、、、

**Comment by AkutsuTomo** [comment]
ジェバンニに1けやき

**Comment by yokozawa1985** [comment]
ラズパイで、圧力計から数値を呼んでくるプログラムを用意しておいて、ssh経由で実行し、値を行き来しているので、まずは、圧力計から信号を読むPC(cryoconみたいなもの)が必要ですね。アナログは経由していないと思います。資料あるか見て見ます。

**Comment by yokozawa1985** [comment]
なるほどです。cc-10のIOに対応するコードを作成して、デジタル読み部 (a+0.1*b)**cのa,b,cをラズパイで読み込んで流みたいですね、そこまで行ければジェバンニの出番かと思います。。。

**Comment by neouniverse** [comment]
アームの話と勘違いしてました。エンドならさっさとPLCに突っ込む相談をした方が良い気もする。

センター・エンドならラズパイで構築してもとりあえずは大丈夫かもしれないけど、
密閉ケースに入れると数時間で熱暴走する困ったちゃんなので(最近のはマシになったんだろうか？)
テンポラリがどのくらい短期なのかにもよるけどもうちょっと堅牢なシステムを考えた方がいい気がする。

**Comment by yokozawa1985** [comment]
テンポラリは今年度までです。来年度は、VACの予算を用いてちゃんとしたシステムを構築すると、SaitoさんUchiyamaさんがおっしゃっておりました。

**Comment by yokozawa1985** [comment]
Review待ちへ移行

**Comment by yokozawa1985** [comment]
closed
