### ISSUE TITLE
インパルスハンマーによる振動テストの解析コードを書く

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#59]
### 目的　（なぜそれをやりたいのか、）
これまで、インパルス応答の解析コードを書いてなかった。
参考URL: https://www.onosokki.co.jp/HP-WK/c_support/faq/pdf/ds3000_impact_analysis.pdf

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 設計
 - [ ] 2. 書く
 - [ ] 3. テスト
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
このissueは、PEM characterizationが終わって、PEM injectionのphaseが始まった際に改めて議論。
とりあえずcloseしておきます。
