### ISSUE TITLE
スピーカ用アンプの電源確保

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#61]
### 目的　（なぜそれをやりたいのか、）
スピーカ用アンプ(QSC RMX5050a)が大電流を食う可能性があるので、配電盤から電源を取る。
その手配を木村さんと粟井さんにお願いする。
その際、もともとのアンプの電源ケーブルを麻生さんが理由があって切っていたので、新しいケーブルを買う必要がある。
例えば、以下。
http://www.ibsjapan.co.jp/products/4856.html
phase1時に設置したが、エンドのものが撤去されたので再設置が必要。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 何時までにいくつ必要か検討する
 - [ ] 2. 依頼する
 - [ ] 3. 設置後テスト
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
今は、粟井さん->吉村さんですね、電気屋さんのエキスパートです。

**Comment by yokozawa1985** [comment]
こちらはPEM characterizationからPEM injectionのprojectが開始されるまで凍結しておきます。
4月頃から開始を計画。
