### ISSUE TITLE
Mag13の回路システムの改良

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#62]
### 目的　（なぜそれをやりたいのか、）
現状のMag13の回路システムは無駄が多い。
それを改善する。
参考: http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Meeting/180723?action=AttachFile&do=view&target=MagSystem_refine.pdf

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 設計
 - [ ] 2. 発注
 - [ ] 3. テスト
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
これは、whitening filter回路を用いたものに変更すれば新たなものを作成する必要がないように思える。whitening filterはこのようなセンサーのために増産している。
[MAG13_whitening.pdf](https://github.com/gw-pem/kagra-pem/files/2705748/MAG13_whitening.pdf)

**Comment by yokozawa1985** [comment]
4年生の磁場測定に使用した。今後問題点が出てこない限り自分達で作らないでwhitening filter回路を使わせていただくことを検討。closed
