### ISSUE TITLE
電源モニターの整備

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#63]
### 目的　（なぜそれをやりたいのか、）
KAGRAは電源のクオリティが悪いと言われている。
DC電源とAC電源の安定度、雑音レベルともにモニターしたい。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 場所の選定
 - [ ] 2. 測定システムの設計
 - [ ] 3. 作成
 - [ ] 4. テスト
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
最近やっと色々なサブシステムが力を入れ始めてきましたので、それに乗っかる形でrestart。

**Comment by yokozawa1985** [comment]
#11 で議論が進んでいるので、続きは、そちらでclose
