### ISSUE TITLE
電波環境調査の準備

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#64]
### 目的　（なぜそれをやりたいのか、）
干渉計を制御するためにはRFサンドバンドを用いた変調・復調が用いられる。そのため、サイドバンド周波数に近い周波数に大きな環境RF雑音があると、それが復調されることで干渉計の雑音になる。従って、サイドバンド周波数付近(10 MHz -- 100MHz)の雑音レベルのモニターとインジェクションテストをして、その影響を調べる必要がある。将来的には、もし使用が予定されている周波数帯に大きな雑音があるようなら、IOOおよびMIFグループに、周波数の変更を提案する。Phase1でも可能ならRFアンテナを用意して環境RF磁場をモニターしたいので、アンテナの準備をすすめる必要がある。

要update
KAGRA坑内のRF環境の調査が必要。変調・復調でノイズになる。

Moku:Labで測定する予定
入力インピーダンスが50Ωなので、インピーダンスがマッチするようにアンテナを作成する
- 資料
  - [超高周波重力波検出器の信号取得系設計のための電波環境調査](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=7525)
  - KAGRA干渉計の用いられるサイドバンドは、[このページ](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/MIFIOOInterfaces)の"Modulations"という見出しの箇所にまとめられている。

original1: https://github.com/gw-analysis/detector-characterization/issues/75
original2: https://github.com/gw-analysis/detector-characterization/issues/25
### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. ループアンテナの用意
阿久津さんの時は、単純な1周のループアンテナアンテナを使用していたので、ひとまずは1周のループアンテナで測定してみるのが良いのかもしれない。
 - [ ] 2. Fアンプの購入
一応あった方が無難
ループアンテナはゲインが高いのでなくてもいけるかも…
 - [ ] 3. は
 - [ ] 4. に
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

#### 元issueのコメント
- 技官のsmdさんにアンテナについて聞いてみたところ、アンリツのダブルヘッドアンテナが良いとのこと。
ループアンテナは磁界しか検出しないため、おすすめできない。
- 電波のあるなしの定性的な測定だけなら、コイルを巻いて測定できる。
- 定量的な測定なら上記のようなアンテナを置いて測定する。
- 資料
http://www.soumu.go.jp/main_content/000036445.pdf
- アンリツのダイポールアンテナは対応範囲が25MHz～だった。
- KAGRAでは13MHzの変調も使用されていて、25MHz以下も測定できるアンテナが欲しい。
- smdさん曰く
30MHz以下は磁界検出で規定されているので
(メール追伸の資料の7序文参照)
対応する測定用アンテナは少ないと思います。
電界強度計としてアンテナと一体になった
測定器もありますよー
アンテナは磁界が中心なのでループ形式になります。
とのこと。

**Comment by yokozawa1985** [comment]
このissueも16日にTTanakaさんと議論を行っていただけたら嬉しいです。
@koji-n @TTanakaTT

**Comment by yokozawa1985** [comment]
こちらはすでにいくつかのissueで議論が開始されているので、closeします。
