### ISSUE TITLE
坑内の磁場勾配計測

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#65]
## 目的／目標
(もともとの担当者(KNとTS)はもう忙しくてできないので別の人でお願いします。)
KAGRA坑内の環境磁場勾配変動を計測する。
KAGRAで問題となる磁場勾配としては、環境磁場がそもそも持っている勾配と、一様な環境磁場が真空槽やフレーム等で歪められて生じる勾配とが考えられるが、このうち前者を測りたい（いずれは後者も）。
地震研から
Metronix ADU-07(ロガー) + MFS-06 or MFS-07e
を借りれるかも。

計測方法は、４つの磁束計を配置（原点に１つとXYZ軸上に１つずつ）し、各軸に沿った差を見れば良い。
最低２つの磁束計があれば計測は可能（配置を変えて複数回行う）。
[おおまかな計測方法](http://granite.phys.s.u-tokyo.ac.jp/shimoda/KAGRA/PEM/setup.pdf)

- 計測対象周波数：1-100Hz (容易に可能なら1kHz程度まで)

- 計測場所（候補）
　　・坑外（電磁場の散乱体が無い場所）→環境磁場自身の勾配
　　・センターエリア２階等（真空槽・ダクトのない場所）→トンネルや電線による散乱も含めた坑内磁場勾配

磁場勾配を計測する上での主な雑音源は、
・磁束計自身の雑音
・磁束計応答（Volt/Tesla）のキャリブレーション誤差による一様磁場変動からのカップリング
・磁束計配置の平行からのズレによる別軸成分の混入

キャリブレーション精度・平行度への要求値は、ざっくりと
　キャリブレーション（磁束計間の相対）：１％
　平行度：0.01rad

地震研から
Metronix ADU-07(ロガー) + MFS-06 or MFS-07e
を借りれるかも。

## ToDo
- [ ] 計測機器の準備：磁束計(MFS-06e), データロガー(ADU-08 o r07), バッテリー, ケーブル, 
- [ ] 計測場所の選定：構造物がなるべくないところ　
- [ ] 計測できる磁場勾配の限界を見積もる
- [ ] 磁束計のキャリブレーション
- [ ] 坑内で計測
- [ ] 完了
## 関連URL/JGW Docs/Files
- https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4459
- https://arxiv.org/abs/1709.02574
- http://iopscience.iop.org/article/10.1088/1742-6596/716/1/012020/meta
## その他
[打ち合わせメモ（2018/3/8@地震研）](https://github.com/gw-analysis/detector-characterization/files/1792220/memo20180308.txt)

[ScatteringCalculation.pptx](https://github.com/gw-analysis/detector-characterization/files/1922434/ScatteringCalculation.pptx)

**Comment by yokozawa1985** [comment]
@TatsukiWashimi 検討をお願いしてもよろしいでしょうか？
当面は2個をこの測定に使用できます。

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 わかりました。とりあえず上に挙げられている文献に目を通しておきます

**Comment by yokozawa1985** [comment]
S/N193,194が故障(横澤机)
S/N 141,142,192が使用可能(坑内PEM area)

**Comment by TatsukiWashimi** [comment]
磁場勾配測定の準備として、北部会館の回路室で2個のMag-13(S/N 141,142)を並行に並べて同時にデータ取得をしてみた。
standaloneとdiagguiを使用。
表示された時系列波形とパワースペクトルをexportでtextファイルにとして存し、自分のPCでrootを使ってplotしてみる。

**Comment by TatsukiWashimi** [comment]
時系列波形のplot
![a](https://user-images.githubusercontent.com/18456905/51368413-a3af4c00-1b32-11e9-9ed8-a6b6a33def99.png)

2つのMag-13それぞれのBx, By, Bzを読み込み、その絶対値と角度も計算してplotしている。
また、磁場ベクトルの差も計算し、同様に成分をplot

**Comment by TatsukiWashimi** [comment]
同様に、パワースペクトルをplotした。
フェライト磁石は近づけていないデータ。
![a](https://user-images.githubusercontent.com/18456905/51372916-14aa3000-1b42-11e9-9380-f900eae66be8.png)

**Comment by TatsukiWashimi** [comment]
200Hz以下をzoom
![a](https://user-images.githubusercontent.com/18456905/51373061-74084000-1b42-11e9-9fd1-662ca888e88e.png)
電源由来のノイズらしき成分が見えるが、60HZより微妙に低い

**Comment by TatsukiWashimi** [comment]
ちなみに、ホワイトニンアンプの電源を切って取得したデータもplot
ケーブルからエレキの間に乗るノイズ
![a](https://user-images.githubusercontent.com/18456905/51373399-85058100-1b43-11e9-8dbb-9d926285119e.png)

**Comment by yokozawa1985** [comment]
@TatsukiWashimi ありがとうございます。
1/23午前 横澤・鷲見でXend測定環境の調査(digital部)
1/23午後 鷲見 center areaの磁場が弱そうなところで測定(練習)
1/24 鷲見・開発・森でXend磁場測定(25日予備日)

**Comment by yokozawa1985** [comment]
測定は(十分かどうかは定かではありませんが、)ひとまず行えたのでcloseします。
