### ISSUE TITLE
Phase1以降の加速度計の必要数

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#66]
### 目的　（なぜそれをやりたいのか、）
現在ある加速度計数の把握と足りない数の把握。
すでに行われているようなら、その報告をお願いします。

### ToDo　(どうすればIssueをCloseできるか)
 - [x] 1. 現状いくつ持っているのか
 - [ ] 2. 今後いくつ必要なのか
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
現状
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/List

今後の必要数
PCal用4個はCAL予算で買ってもらえた。
チェンバの加速度計が全く用意できていないが、どれくらい必要なのかを来月着任のポスドクを中心に評価してもらい、来年度の予算に組み込む予定。

**Comment by yokozawa1985** [comment]
@TatsukiWashimi 来週にでもチェンバーcharacterizationの議論を開始しましょう。

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 了解しました。

**Comment by MiyoKouseki** [comment]
そろそろcloseですか？
レビューできるようにまとめてください。

**Comment by yokozawa1985** [comment]
一旦closeして、washimiさんがCRYの方々と議論を再開できたら別issueでopenにします。
