### ISSUE TITLE
ホワイトニングフィルター/アンプの検討

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#67]
### 目的　（なぜそれをやりたいのか、）
センサーにはホワイトニングフィルター/アンプが必要なものがある。
それをチェックする。
(数が多いようならセンサーごとにissueを切りましょう。)
すでに検討されているなら、それを報告して下さい。

ちなみに、CALグループと共同開発するみたいな話があったが、どうなったかは私は知らない。
https://github.com/gw-analysis/detector-characterization/issues/65

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. センサーの性能のチェック
 - [ ] 2. ADC雑音との比較
 - [ ] 3. フィルタの設計
 - [ ] 4. フィルタの作成
-  [ ] 5. テスト
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
CALはAELで作成いただいているwhitening filterの性能が十分なので独自開発は今の所検討されていない。

**Comment by MiyoKouseki** [comment]
ちょっとコメントがズレてしまうかもしれませんが、こういう一覧が作れるようになるといいのかもしれません。

https://dcc.ligo.org/public/0012/D1001575/009/aLIGO_SEI_SensorActuatorCalibration-v9.pdf

これはLIGOの地震計に関係したフィルタを一覧できるドキュメントです。

**Comment by MiyoKouseki** [comment]
地震計に関しては自分が作ります。

**Comment by yokozawa1985** [comment]
設置されているすべてのPEMに対して、ADCノイズとの比較のスペクトルを作成してみます。
(いずれ、typical ASDはwikiに載せようと思っておりましたので。)

**Comment by yokozawa1985** [comment]
すみません、命名が完了したら行います。

**Comment by yokozawa1985** [comment]
とりあえず、AEL whitening filter circuitを用いた測定が問題なく行われているため、close
