### ISSUE TITLE
測定した磁場マップの作成

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#70]
12月に測定した磁場の場所をマップとしてまとめる。
どうして、そこを測定したのかの理由もまとめてあると良い。

- [x] 磁場測定のセットアップをまとめる

- [x] 磁場の測定した場所マップの作成

- [x] 測定した理由をまとめる。

- [x] (とっているなら)とっている様子の写真をまとめる。

**Comment by imyukino** [comment]
[磁場MAP作成]
測定場所と理由
クリーンルーム外
・入り口とOMCの間(周りに回路や機械がないためnormalになるかなと思い測定)
・ラック：OMC,IX0,IY0,IMC,IOO,BS(各ラックの磁場比較)
・AirFan：OMC横,SR2横,PR3横にあるAirFan(磁場、音場両者で大きなノイズになりそうだったため測定)
・チェンバー(クリーンルーム外)：IXC,MCEN(磁場を測定したことがないエリアだったので、磁場把握のため測定)
・機械室(磁場把握のため測定)
・IYC横のKOACH FILTER(磁場、音場両者で大きなノイズになりそうだったため測定)

クリーンルーム内
・チェンバー周り：MCF,IFI,IMM,PRM,PR3,PR2,BS,SR2,SR3,SRM,OMMT,OMC(クリーンルーム内、チェンバー周りの磁場把握のために測定)

写真も撮ったので載せたいのですが、載せ方が分かりませんでした。

**Comment by yokozawa1985** [comment]
Attach files by dragging & dropping
ですね。

**Comment by imyukino** [comment]
![kagra-full](https://user-images.githubusercontent.com/45890168/50755689-20256d80-129d-11e9-8980-c2d68627eafc.png)

センターエリアでの測定箇所です。
この画像を卒論でもMAPとして使用したいと考えていますが、もっと分かりやすく具体的な図を作成したほうが良いでしょうか？

**Comment by yokozawa1985** [comment]
ありがとうございます。僕にとっては非常にわかりやすいMAPなのですが、先生方に聞くのがいいかもしれません。

**Comment by yokozawa1985** [comment]
review待ちに変更
