### ISSUE TITLE
測定した音場マップの作成

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#71]
12月に測定した音場の場所をマップとしてまとめる。
どうして、そこを測定したのかの理由もまとめてあると良い。

- [x] 音場測定のセットアップをまとめる

- [x] 音場の測定した場所マップの作成

- [x] 測定した理由をまとめる。

- [x] (とっているなら)とっている様子の写真をまとめる。

**Comment by KiichiKaihotsu** [comment]
[音場測定のセットアップをまとめる]
マイクはACO社製TYPE 7147Aの拡散型のものを使用。マイクスタンドにマイクを吊り下げ、離れて測定した。

[音場の測定した場所マップの作成]
<img width="813" alt="kagra-map" src="https://user-images.githubusercontent.com/45889411/50808224-e5751100-1340-11e9-93f4-19cbc0e65141.png">
<img width="803" alt="kagra-map-2" src="https://user-images.githubusercontent.com/45889411/50808232-ec9c1f00-1340-11e9-971e-569086fa3ab6.png">

赤丸がクリーンルーム外、緑丸がクリーンルーム内で測定をした場所です。
卒論では数字とデータを紐づけして書いていこうかと考えています。

[測定した理由をまとめる]
主に開いている空間の音と、Koach filterや各チェンバー、送風機や冷風機といった機器類特有の音を測定するために、図のような場所を選んだ。

[(とっているなら)とっている様子の写真をまとめる。]
![img_1391](https://user-images.githubusercontent.com/45889411/50808572-84e6d380-1342-11e9-8e69-acb71d407bec.JPG)
![img_1390](https://user-images.githubusercontent.com/45889411/50808578-8a441e00-1342-11e9-97e0-bf3c6fb4896d.JPG)

**Comment by yokozawa1985** [comment]
ありがとうございます。次は、基準測定場所の設定とスペクトル表示ですね。
