### ISSUE TITLE
基準となる磁場スペクトルの図を作成する。

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#72]
一箇所基準となる磁場のスペクトルの図をここに載せる。
その後、どのようにcharacterizationをしていくのかの議論にうつる。

- [x] 基準となる磁場測定場所を決定する

- [x] 磁場測定のパラメータを載せる

- [x] スペクトルをこのページに貼る

**Comment by imyukino** [comment]
![entrance](https://user-images.githubusercontent.com/45890168/50755795-772b4280-129d-11e9-90ad-5ca254356882.png)
![](https://files.slack.com/files-pri/T8UTSA3PT-FF7LBCNAG/img_9289.jpg)
基準となるスペクトルは、ノイズフロアは他と比べてオーダーが1桁ほど高いですが、ピークが小さくcomb波も落ち着いている入口付近にしようと考えています。
比較例としてOMCrackでのスペクトルを載せておきます。
![omc](https://user-images.githubusercontent.com/45890168/50756223-d2aa0000-129e-11e9-8815-6bf157bf0d3e.png)

**Comment by imyukino** [comment]
![img_9289](https://user-images.githubusercontent.com/45890168/50756301-13a21480-129f-11e9-94e4-efd004642332.JPG)

入口付近の写真です。

**Comment by yokozawa1985** [comment]
review待ちに変更いたします。

**Comment by imyukino** [comment]
ご確認、新しいissueの作成ありがとうございます。
取り組みます！
