### ISSUE TITLE
基準となる音場スペクトルの図を作成する。

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#73]
一箇所基準となる音場のスペクトルの図をここに載せる。
その後、どのようにcharacterizationをしていくのかの議論にうつる。

- [x] 基準となる音場測定場所を決定する

- [x] 音場測定のパラメータを載せる

- [x] スペクトルをこのページに貼る

**Comment by yokozawa1985** [comment]
> 音場測定のパラメータとは何でしょうか？
説明不足で申し訳ございません。
スペクトルの図を作る時に使用したパラメータ、つまり、diagguiに入力したパラメータです。
平均回数とか、bandwidthとかです。

**Comment by yokozawa1985** [comment]
あと、使用したマイクは、1Hz以下に感度がありましたっけ？
感度がない場合は、そこの値はあまり信用できないので図に結果を載せないほうがいいでしょう。

**Comment by KiichiKaihotsu** [comment]
使用したマイクは20[Hz]~10[kHz]までが感度です。

パラメータは1日目(赤丸①②③④⑧⑫⑬⑰)はBW=0.1[Hz],AV=100[回],Overlap=50[%]
2日目(上記以外)はBW=0.05[Hz],AV=20[回],Overlap=50[%]
で測定しました。

**Comment by KiichiKaihotsu** [comment]
横澤さんのアドバイスをもとに、プロットし直してみました。
またMAPの番号も配置を少し変えました。基準点にしようと考えている機械室は9番です。
![map-1-9](https://user-images.githubusercontent.com/45889411/50887606-fb64fd80-1436-11e9-8856-0d4290ccd329.png)
<img width="803" alt="kagra-map-1-2" src="https://user-images.githubusercontent.com/45889411/50887609-fe5fee00-1436-11e9-99ff-2a84aa7c3776.png">

**Comment by yokozawa1985** [comment]
ありがとうございます。review待ちに移します。
では、基準と大きく違う場所のスペクトルを一つここに載せてください。

**Comment by yokozawa1985** [comment]
ありがとうございます。では、磁場と同様、No3の特徴や基準との違いを考察してみてください。

**Comment by KiichiKaihotsu** [comment]
マイクの自己雑音についてカタログを見たところ、17dB(A)と書いてありました。
どの周波数においての値かをアコー社に問い合わせたところ、17dB(A)はオールパス値で、dB(A)→dBにすると40dBであると回答が来ました。
音圧レベルの定義式より、40dBのときの音圧が10^(-2.699) [Pa]と計算できるのですが、この値は瞬時音圧の実効値です。
基準点音場スペクトルがself noiseに埋もれていないことを示すのに、基準点と自己雑音を同時プロットする(縦軸が振幅スペクトル密度の)場合、実効値のままプロットしても問題ないのでしょうか？

**Comment by KiichiKaihotsu** [comment]
得られた自己雑音をそのままプロットした図
![map-1-9-2-1](https://user-images.githubusercontent.com/45889411/52277038-158eee80-2997-11e9-878d-b4114828ebcd.png)

こんな感じで示したいです。

**Comment by yokozawa1985** [comment]
すみません、返信が遅くなりました。
10^(-2.699)[Pa]
は振幅スペクトル密度ではないと思います。時系列の実効値を示してくれているのだと思います。
ホワイトノイズだとして、振幅スペクトル密度に直す必要があります。

**Comment by KiichiKaihotsu** [comment]
17dB(A)(40dB)はオールパス値とのことでした。
オールパス値を調べてみると
「AC 出力（瞬時音圧）信号を周波数分析せずに、直接平均全パワー（実効値）を求めて、レベル化して表示した値」と書かれていました。
実際に振幅スペクトル密度の直すには、10^(-2.699)[Pa]の値にどんな操作を行えばいいでしょうか？

**Comment by yokozawa1985** [comment]
そこは、自分で考えて欲しいと言いたいところですが、もしギブアップでしたら改めて連絡ください。

**Comment by yokozawa1985** [comment]
ホワイトノイズは、全周波数で同じパワースペクトル密度を持っているノイズのことです。

**Comment by KiichiKaihotsu** [comment]
わかりました。ひとまず全力で考えてみます。
ありがとうございます。

**Comment by KiichiKaihotsu** [comment]
@yokozawa1985 
横澤さん

パワースペクトルは振幅の実効値の二乗で、パワースペクトル密度にするには周波数分解能で割ってあげる。また振幅スペクトル密度はその平方根である。
自己雑音の実効値A(振幅)は10^(-2.699)[Pa]で、周波数分解能BWはBW=0.05[Hz]で測定したので、自己雑音のパワースペクトル密度Sは
S=A^2/BW={10^(-2.699)}^2/0.05
で、振幅スペクトル密度はその平方根。

と考えました。
この考え方で合っていますでしょうか？

**Comment by KiichiKaihotsu** [comment]
![map-1-9-3-1](https://user-images.githubusercontent.com/45889411/52394630-42094e80-2aee-11e9-96ad-9989f00f1cdb.png)

この考え方で出した値と機械室の音場をプロットした図です

**Comment by yokozawa1985** [comment]
係数2とかが微妙ですが、(片側スペクトルなのでいらないと思います。)多分あってそうですね。
適当なことを言ってたらゴメンなさい。。(山元さんに確認してみてください。。)

**Comment by KiichiKaihotsu** [comment]
ありがとうございます。
山元先生にも確認してみます。

**Comment by yokozawa1985** [comment]
いや、なんか積分時間でスペクトル密度の値が変わってはいけない気がする。。けど、サンプリング周波数では変わるのか？ちょっと頭冷やしてきます。。。

**Comment by KiichiKaihotsu** [comment]
山元先生に聞いてみた所、
周波数分解能ではなく、マイクの測定できる周波数範囲で割るということでした。

これでもう一度計算してプロットしてみます。

**Comment by yokozawa1985** [comment]
確かに言われてみたらその通りですね。。
お騒がせいたしました。

**Comment by KiichiKaihotsu** [comment]
こちらこそお騒がせしてすいません。
これでとりあえずは卒論完成させれそうです。

ありがとうございます。

**Comment by yokozawa1985** [comment]
お疲れ様でした！
