### ISSUE TITLE
チャンネル名一覧の並びが、場所目線になっている。

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#74]
**問題について** 何が問題か書いてください
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Channels

場所目線でいい気がするので、問題という程でもない。
かなり細かい話。
しかし#48で決まったように、チャンネル名の命名規則はセンサー目線なので、センサー目線の配置にしたほうがいいかも。

**正しい状態** どうなっているべきか書いてください
センサー目線にする。

そっちのほうが今どのセンサがどのチャンネルに使われているかがひと目で分かる。

となるとPEMEquipmentsのページとの違いは？ってなる。

**Comment by yokozawa1985** [comment]
Miyoさん的な場所目線とセンサー目線の違いを書いてください。

**Comment by koji-n** [comment]
これ↓的なことができれば最高なんですけどねー
http://taru.s223.xrea.com/index.php?diary%2F2006-11-08
一応、moinmoin wiki (KAGRA wikiで使ってる) でもできるっぽいけど。
https://moinmo.in/FeatureRequests/SortableTables

**Comment by MiyoKouseki** [comment]
@yokozawa1985

チャンネル名がセンサー名が最初に来るようになったので、

現在、目次が
KAGRA PEM Channel List
 - Ondotori
 - PSL(-2018/12/10-)
 - CS(-2018/12/10-)
 - EX(-201X/XX/XX)
 - EY(-201X/XX/XX)
 - Seismometer
 - Air Environment Sensors
 - Temporary channels in IX0
 - Temporary channels in IY0

なのを、

KAGRA PEM Channel List
 - Ondotori
 - Seismometer
 - Air Environment Sensors
 - Accelerometer
 - Magnetometer
 - Microphone
 - RF anntena
 - Weather station
 
にしたいです。細かい話ですが。

**Comment by MiyoKouseki** [comment]
@koji-n なるほど。ありかも。

**Comment by MiyoKouseki** [comment]
@yokozawa1985 
よろしくおねがいします。

**Comment by yokozawa1985** [comment]
closed
