### ISSUE TITLE
チャンネル名がルール通りかどうかの自動チェック

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#75]
ルールを決めたら、ちゃんとルールに則っているかチェックしないと、意味がない。

なので、現在流れているチャンネルの名前がルール通りに名付けられているかチェックするスクリプトが欲しいです。

自動化できれば、pemのチャンネル名が常にルール通りになってるかどうか気にしなくて済みます。

こういうチェックの自動化は、pemの質を常に保ってくれます。これはCI(継続的インテグレーション)ってやつでしょうか。チェックスクリプトを実行すれば質が保証されるという仕組みは、精神的な負担を減らしてくれます。

チェックスクリプト(テストスクリプト)を走らせて合格したものをpemグループは提供する、という仕組みができれば、開発している我々もユーザーも安心して開発や利用ができます。このissueはそのための第一歩になります。

ともあれ、この話は今のpemでは優先順位が低いです。
誰か暇な人がちょちょっと書いてくれたらありがたい程度です。CIの考え方が浸透したころにとりかかるのがいいかも。

**Comment by yokozawa1985** [comment]
自動スクリプトはいずれ作りたいと思いますが、手動でチェックできるツールは早急に作りたいです。
資料finalizeしたら作ってみます。

**Comment by MiyoKouseki** [comment]
項目リストを、現在の[JGW-D1809553-v6](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9553)を元にして、iniファイルを作りました。

kagra-pem/channelname/definition.ini
にあります。"JGW-D1809553-v6"というタグをつけてコミットしました。

**Comment by MiyoKouseki** [comment]
完成して、実際に使っているのでレビュー待ち。

**Comment by yokozawa1985** [comment]
今日のmeetingでreviewしてください。

**Comment by yokozawa1985** [comment]
ありがとうございます、meetingできなくてすみません。Closeしますが、後でどんな感じか見せてください。
