### ISSUE TITLE
3つの地震計からCARMとDARM成分をつくってDQ

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-pem/kagra-pem#79]
**改善案** どのように改善してほしいか書いてください。

手元で地震計の信号を引くのは面倒。
モデルの中に組み込みたい。

IXV と  EXV のXアーム方向から、同相・逆相の信号（2つ）
IXV と  EYV のYアーム方向から、同相・逆相の信号（2つ）
上記の同相信号から、CARMとDARM（２つ）

合計で6つ。

**Comment by MiyoKouseki** [comment]
Verticalはどうする？

**Comment by yokozawa1985** [comment]
とりあえず、腕方向のモニター部は作ってみてもいいのではないでしょうか？
問題はどのモデルで作成するかですね。
IXV, EYV, EXVから信号をshared memoryで持ってこれるマシンを探すことからスタートですかね。

**Comment by MiyoKouseki** [comment]
横澤さんが指摘しているように、リアルタイムで演算するにはちょっと手間がいる。オフラインで良い気がしてきた。なのでClose
