### ISSUE TITLE
OMC rackの磁場測定の結果の考察

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#80]
**改善案**
どのように改善してほしいか書いてください。

- [ ] 基準とした場所での磁場測定に比べて、今回示してくれたOMC rack付近の磁場測定の結果がどのような特徴があるのか自分なりにまとめてください。

**Comment by imyukino** [comment]
![2019-01-09 14 41 22](https://user-images.githubusercontent.com/45890168/50879154-4114cc80-141d-11e9-9785-760eb0e0c561.png)

OMCrackの解析での疑問点(今日中に解析結果をあげたい)
上図の周波数範囲での60Hzの倍波は5700Hz,5760Hz,5820Hzだが、少し(2Hzくらい)ずれてピークがたっているのはなぜなのか。
高周波につれてこのずれる周波数が多くなっている。

無視しても良いものなのでしょうか？
そもそも60Hzのノイズについての知識を深める必要あり

**Comment by yokozawa1985** [comment]
これはPEM以外のものも見てみたいですね。
とりあえず、ハムノイズ(60Hz)が載っているものは見ていってみます。
->60Hzの知識を深めるのは重要!

**Comment by imyukino** [comment]
normal(entrance)とOMCrackの磁場比較
自分なりに解析してみたのでたくさんダメ出しお願いします。

まず、normal(entrance)について
スペクトル図
![normal](https://user-images.githubusercontent.com/45890168/50900344-3d526b80-1458-11e9-931d-ac570067afda.png)
ノイズフロアは10Hzあたりから安定してx,y軸は3×10^-12、z軸は4×10^-12あたり。
ピークが高い周波数を表1にまとめる。
![2019-01-09 22 16 35](https://user-images.githubusercontent.com/45890168/50901681-46ddd280-145c-11e9-9294-85087e5d2584.png)
全体を通して60Hzのハムノイズの倍波あるが大人しめ。

次にOMCrackのスペクトル図
![omcrack](https://user-images.githubusercontent.com/45890168/50900400-6bd04680-1458-11e9-8092-f5071dab1432.png)
ノイズフロアは10Hz~400Hzまでは3軸同じオーダーだが、400Hz以降からz,x,y軸の順に大きい。
しかしピークの大きさはだいたいx,y=z軸の順に大きい。
ピークが高い周波数を表2にまとめる。60Hzの倍波以外で気になったピークをピックアップした。
![2019-01-09 22 30 04](https://user-images.githubusercontent.com/45890168/50902397-20b93200-145e-11e9-93d0-d1f130b4b924.png)

normalとOMCrackの比較
比較画像として軸ごとの比較グラフを載せる。
![normal-omc-x](https://user-images.githubusercontent.com/45890168/50902592-a89f3c00-145e-11e9-8653-5b48020b4f0d.png)
![normal-omc-y](https://user-images.githubusercontent.com/45890168/50902595-a9d06900-145e-11e9-9a2e-4cb6ce42c418.png)
![normal-omc-z](https://user-images.githubusercontent.com/45890168/50902604-af2db380-145e-11e9-8dd2-30a6d3c7b11d.png)

・ノイズフロアはnormalのほうが高いが安定している。
・OMCrackはノイズフロア自体の揺れ？が大きい。ぐらつきがある。
・ピークは全体を通してOMCrackのほうが高い。
・OMCrackのcomb波の主な要因は、ハムノイズであることが分かったが、表2から分かるように他の要因も混じっている。これを細かくノイズハンティングするのは大変そう。
→ハムノイズを削減させればその細かい他のノイズも消えるのか？全く違う要因から来ているピークなのか？
・OMCrackに対してx軸が並行方向、y軸が垂直方向になるように、磁場測定を行ったが、x軸でのスペクトルが3軸の中で最も高かった。

ノイズハンティングするためにOMCrackに入っている回路を参考に載せる。
![omcrack](https://user-images.githubusercontent.com/45890168/50903082-0ed88e80-1460-11e9-9936-016c08aba3a7.jpg)


この中のどの回路がノイズになっているかはどうやって考えていったら良いですか？
回路を１つずつ磁場測定するべきなのですが、卒論までにそれをして解析する時間がなさそうなので、どのレベルまで解析できるか考えています。

**Comment by neouniverse** [comment]
> 上図の周波数範囲での60Hzの倍波は5700Hz,5760Hz,5820Hzだが、少し(2Hzくらい)ずれてピークがたっているのはなぜなのか。
高周波につれてこのずれる周波数が多くなっている。

基本波の60Hzってどのくらい正確に60Hzなんでしょうか？

**Comment by imyukino** [comment]
neouniverseさん
基本波の60Hzのスペクトル図は以下です。
上図の3540Hzと比べると、60Hzの時はピークが鋭いです。
![2019-01-10 15 48 14](https://user-images.githubusercontent.com/45890168/50951038-2b6fd780-14ef-11e9-9bc3-33e552da1a2a.png)

**Comment by yokozawa1985** [comment]
おつかれさまです。いま坑内から出てきたので結果見ていきます。
> この中のどの回路がノイズになっているかはどうやって考えていったら良いですか？
> 回路を１つずつ磁場測定するべきなのですが、卒論までにそれをして解析する時間がなさそうなので、どのレベ> ルまで解析できるか考えています。
一番確実なのは、回路の電源を一つ一つ落としていくことだと思います。
それか、同じ回路を使用しているラックで同様の振る舞いが見られるのかチェックするですね。

ただ、ノイズ源の特定をすべてのデータに対して行うのは時間的に難しいそうなので、今やっていただいているようなピークの周波数の数値化(載せていただいた表みたいなやつ)とかy軸結果だけもっこりしているみたいな考察がいいと思います。

**Comment by imyukino** [comment]
お疲れ様です。
磁場雑音MAPの解析方法についてですが、
１、各測定場所でのノイズフロア(3軸)。
２、各測定場所でのピークが立っている周波数とそのときのスペクトル値を表でまとめる。
３、各測定場所での特有のラインや盛り上がりを探す。
４、normalと各測定場所の比較(3軸)
にしようと思うのですが、どうですか？

**Comment by yokozawa1985** [comment]
すごくいいと思います。
4. が具体的にどのように比較するのかが別途議論が必要だと思いますが、まずは、1-3を進めるのがいいと思います。

**Comment by neouniverse** [comment]
@imyukino たとえば60Hzの10倍波、100倍波はそれぞれ600Hz, 6000Hzですが、
基本波が60.02Hzとか50.98Hzとか0.02Hzくらいズレていれば
10倍波で0.2Hz, 100倍波なら2Hzくらいズレていても不思議ではないです。

ピークの広がり方も基本波成分がどのくらい揺らいだときに
倍波成分がどのくらい揺らぐのかを考えてみると
結果が妥当そうかどうか判断できると思います。

逆に倍波成分の挙動から基本波成分の挙動を類推するという手もありなんでしょうか。
そうすると周波数分解能の要求値は下がります。
何にせよBW〜0.09Hzだと0.02Hzのズレは評価するのは出来ないですね。

**Comment by imyukino** [comment]
お疲れ様です。
今、磁束計のデータ解析の方法として、上記した
１、各測定場所でのノイズフロア(3軸)のスペクトル値。
２、各測定場所でのピークが立っている周波数とそのときのスペクトル値を表でまとめる。
３、各測定場所での特有のラインや盛り上がりを探す。
４、normalと各測定場所の比較(3軸)
をしているのですが、解析を進めてみて、
２、各測定場所でのピークのスペクトル値を細かく見ていくことに意味があるのか悩んでいます。
例えば、BS裏にあるAirFan近くでのスペクトル値のピークはハムノイズとその倍波以外で60箇所以上あり、それを3軸分、24データ分見ていくのは時間的にも厳しく、もっと意味のある解析はないかなと思い相談しました。
卒論的にもデータの表が並んでいるだけより、他の解析をしたほうが面白いものができるのではないかなと思います。

**Comment by yokozawa1985** [comment]
そうですね、
2の解析は1-2箇所自分で選択して行う。
他の場所の解析は3の解析に回す。
3の解析では、目での確認にとどめる。

その他の解析では、
- 2で表にしたライン値から、倍波となっていそうなラインを探してみて
その大きさがどのように変化しているかをみてみる
- booth内と外である周波数のラインがどれくらい小さくなっているか、
- booth内の磁場測定でのビーム方向(PRだったらX軸), SRだったら(Y軸)
を比較して大きさが変わっていたりするか？
などが浮かび上がります。
こういう解析は面白そうですか？などというアイディアが浮かんだら書いてみてください。

**Comment by yokozawa1985** [comment]
(理想は、自動ライン検知プログラムを作成しちゃうことです。)

**Comment by imyukino** [comment]
横澤さん、鷲見さん
お疲れ様です。
![2019-01-23 15 34 15](https://user-images.githubusercontent.com/45890168/51587670-dedfbf80-1f24-11e9-82cb-8513290e4bca.png)
上図のスペクトル図はSRMチェンバーとnormal(KAGRAセンターエリア入り口付近)を比較したグラフです。
①で囲ってある箇所は、ほぼ同じ形(ラインやピークの立っている位置が似ている)でオーダーが違うグラフです。これは同じ磁場発生源からの磁場で、磁場の強さが違うという解釈で大丈夫でしょうか？
また、②で囲ってある箇所はノイズフロアの厚さ?が違うのですが、この要因は何ですか？
測定時のパラメーター(BW=0.05[Hz],AV=20 回)は等しいです。

**Comment by imyukino** [comment]
横澤さん
①については、その考え方で納得です!今後のやりたいこととして、SRMと入り口付近の間で磁場測定を行い、ノイズハンティングするという書き方でまとめます。
②については、diagguiのパラメータは全く同じで、磁束計の向きも全く同じです。山元先生も全く同じ条件なら、不思議だねと言っていました。

**Comment by yokozawa1985** [comment]
今回測定したデータで、どちらのパターンが多いか確かめて見てください。
あと、時系列も。

**Comment by imyukino** [comment]
分かりました。
逆フーリエ変換すればよいのは分かるんですが、diaggui上でのtime series の見方が分からなかったので、明日神岡に行ったときに時間があれば教えて欲しいです。すみません。。

**Comment by imyukino** [comment]
お疲れ様です。

チェンバーの測定結果を見ていた際に、低周波(約17.2,23.5,25.5,30,36,45Hz)と
高周波(約140,320,420,500Hz)でノイズフロアに盛り上がりがあるのが分かりました。
<img src="https://user-images.githubusercontent.com/45890168/52027663-8bd2c180-254f-11e9-8747-71d80c4c32c9.png" width=300px>
図1:ノイズフロアの盛り上がりが大きい例
<img src="https://user-images.githubusercontent.com/45890168/52027700-ac028080-254f-11e9-9dff-8b24cc2bb06c.png" width=300px>
図2:ノイズフロアの盛り上がりが小さい例

ノイズフロアの盛り上がりの大小をそれぞれ低周波と高周波でパターン分けし、図に色分けしました。
<img src="https://user-images.githubusercontent.com/45890168/52026851-aeafa680-254c-11e9-97b4-dc62e3fe088a.png" width=300px>
図3:赤色は低周波でノイズフロアの盛り上がりが大きいチェンバー、黄色は小さいチェンバー
<img src="https://user-images.githubusercontent.com/45890168/52026758-5678a480-254c-11e9-9281-51356105c256.png" width=300px>
図4:赤色は高周波でノイズフロアの盛り上がりが大きいチェンバー、黄色は小さいチェンバー

この結果のまとめを悩んでいます。
また、ノイズフロアが盛り上がる時と、ピークとしてでる時は雑音にどのような違いがあるのでしょうか？

**Comment by yokozawa1985** [comment]
お疲れ様です。
一つ、確認です。マイクでも同様の盛り上がりが見えたりしていますでしょうか？
純粋に磁場の影響かもしれないですし、音の信号と相関があるのかもしれないですし、Human activityの可能性もあると思います。
> また、ノイズフロアが盛り上がる時と、ピークとしてでる時は雑音にどのような違いがあるのでしょうか？

純粋に磁場の測定だと仮定した場合は、Q値の違いというのが一般的です。振幅の時間変化が不安定なほど盛り上がるようになります。サインガウス信号のフーリエ変換が良い例です。
が、単純に何かの作業のノイズがはいってしまったか、人が歩いているのに反応して生じる盛り上がりの可能性もあります。<-何かの作業の場合は、短時間で振幅が変化するので。

**Comment by imyukino** [comment]
横澤さん
まず初めに、
<img src="https://user-images.githubusercontent.com/45890168/52108821-a20b7b00-263e-11e9-8842-682116799a88.png" width=300px>
<img src="https://user-images.githubusercontent.com/45890168/52108839-b8193b80-263e-11e9-8dac-751bb7592b39.png" width=300px>
マイクにも同様の盛り上がりがありました。
ということは、共通部のBNCケーブルやADC,WHF回路などからのノイズということでしょうか？
そもそも、低周波でのノイズフロアの盛り上がりが見えやすいのは当たり前のことで、その盛り上がりの大きさを比較することは意味ありますか、、？着眼点を間違えたのかなと思っています。

磁束計がマイクからどのくらい影響を受けているかマイクとスペクトルの形を比較してみました。
入り口付近では磁束計のみで測定を行いました。
<img src="https://user-images.githubusercontent.com/45890168/52107184-b9476a00-2638-11e9-844a-65e72a8b1a2d.png" width=450px>

<img src="https://user-images.githubusercontent.com/45890168/52108200-7be4db80-263c-11e9-8c7d-fb8ee803a214.png" width=450px>
44Hz,55Hz手前,59Hzで共通のピークあり。

<img src="https://user-images.githubusercontent.com/45890168/52108223-91f29c00-263c-11e9-8aaa-b2f94a80ff8c.png" width=450px>
全体的にラインの形が似ている。55Hz手前と59Hzで共通のピークあり。

という感じです。
マイクと磁束計共通のピークとして、44Hz,55Hz(11Hzの倍波),59Hzがあり、磁束計のみで測定を行った際にはそのピークがないため、これらはマイクの影響を受けているというよりかは、先程同様の共通部のBNCケーブルやADC,WHF回路からのノイズと考えて大丈夫でしょうか、、？

Q値についての説明ありがとうございます！タスクにもあったので卒論までにきちんと勉強します。

**Comment by yokozawa1985** [comment]
ノイズの盛り上がりを調べるという着眼点は素晴らしいと思います。
"純粋に環境磁場だったら"時間変化が大きいラインノイズの可能性等があると思うからです。
しかし、今回の場合、マイクにも載っているとのことなので、ケーブルノイズの可能性が高い気がします。
本日の測定でもファンや送風機をすべてオンになっていたら、音などの振動によりエンドの磁場測定が非常に困難になるという事象が発生しました。鷲見さんに聞いてみて、似たようなスペクトルになるか確認してみてください。

**Comment by imyukino** [comment]
マイクにも同じような盛り上がりがあるということは、マイクスタンドの共振による影響も考えられますか？
マイクスタンドの共振調べてみたいです！

エンドの磁場測定が非常に困難というのは、空気の揺れ(音場の変化)で磁束計が揺れ、本来みたい磁場と区別がつかないということですか？

**Comment by yokozawa1985** [comment]
マイクスタンドの共振はとりあえず後日測定してみます。(もしくは測定しに来ます？？)
鷲見さんに、ファン、送風機のオンオフの結果だけ送ってもらってみます。

**Comment by yokozawa1985** [comment]
あと、diagguiでのtime seriesはxml fileからは再生できないようです、リアルタイムで撮ったデータからしか見れなさそう。
要望がありましたら、その時間のtime seriesのdat fileを作成いたします。

**Comment by yokozawa1985** [comment]
昨日、現場で話していたら、音場が周辺の金属を揺らし、そのせいで磁場に乗るというのが考えられるそうです。なので、音場によるケーブルノイズというよりは、音場による環境磁場の発生という結論の方が考察として正しいかもしれません。

**Comment by imyukino** [comment]
横澤さん
なるほど！とても納得がいきました。
音によって空気が振動し、金属が振動することで、ファラデーの電磁誘導の法則から、誘導電場が発生するっていうイメージで大丈夫ですか？
マイクでの測定により、音による振動の影響だと分かったとまとめます！

周りになにもない空間で、中心に金属を置き、両端にそれぞれ同じ距離離れた位置にマイクと磁束計を設置し、アンプから音をだし、それぞれのスペクトルを見るという実験をしてみるとさらにはっきりしそうです！

**Comment by yokozawa1985** [comment]
そうですね！色々と追実験のアイディアが出てくるのはいいと思います。
マイクスタンドの共振と、金属実験は取っておきます。

**Comment by imyukino** [comment]
お疲れ様です。
センターエリア,OMCチェンバーとSR2チェンバー横にある送風機についてなのですが、
一般的な送風機のrps(1分間の回転数)は1800[rps]なので300[回転数/s]です。
この300[Hz]を磁束計で見られる磁場の周波数?に変換したいのですが、コイルを4つ使ったモーターの場合だとどのように計算していけば良いですか？

**Comment by yokozawa1985** [comment]
そうですね、送風機は回転しているので多くの磁場が予測されます。
本観測でも使用が必要な場合にノイズ源となる可能性となるますというsuggestionが
ノイズハンティングのkeyとなるかもしれません。
カタログを見ながら議論を続行させましょう。

**Comment by yokozawa1985** [comment]
rpsは一秒間の回転数で、rpmが1分間の回転数では？？そして、1800rpmは、30rpsですね。
コイルとモーターの関係がよくわからないので調べてみる必要あります。

**Comment by imyukino** [comment]
すみません、間違えていました！その通りです！

このモーターの回転数[rps]と磁場の関係を計算したいです。
1/[rps]=[Hz]だと考えて、磁束計に現れるピーク[Hz]と一致したら、そのピークの原因はモーターだと考えるのはおかしいですか、、？
![2019-02-06 22 05 21](https://user-images.githubusercontent.com/45890168/52343412-5819ff00-2a5b-11e9-92c9-66b43757270e.png)


少し話が変わるのですが、I/Ochassisについているファンが影響で立つピークは550Hzらしいです。(LIGO情報)
これは0.0018[rps]という考えで大丈夫ですか?

**Comment by imyukino** [comment]
訂正です
モーターにコイルが4つついている場合は、iochasshisの例でいくと、550Hz/4=137.5Hzなので、0.0073[rps]ですか？

**Comment by yokozawa1985** [comment]
物理量を正確に書きましょう。
[rps]~[Hz]と考えてよいと思います。1/[rpm]=[Hz]ではないです。
この場の議論では、[rpm]は使わないようにしましょう。
モータにコイルが4つ付いていたら周波数は4倍になると思います。
送風機の型番は今調べてもらっております。

**Comment by yokozawa1985** [comment]
あと、基準点と同じ周波数だけど、振幅が全然違うラインがあるのは、電源からの磁場の可能性が高いと思っております。近くで、100Vコンセントから供給される機械を動かすとそのぶん電流が大量に流れて、そのノイズが機械があまりないところで測定されているものよりも増幅されてしまう。ということも考えられます。
これは、電源モニターとの同時観測で何かしらのヒントを得られるかもしれません。現在、他のサブグループとモニター方法を議論中です。

**Comment by imyukino** [comment]
この送風機のモータの種類を勘違いしていてものすごく遅くなりましたが分かりました！
まずこの送風機は4極電動機です。
4極電動機は固定子コイル2組を3相用意し固定部分の円周に並べます。
![2019-02-07 19 49 34](https://user-images.githubusercontent.com/45890168/52406781-dcc75480-2b11-11e9-826d-64092ea898ab.png)
各コイルABCに対称な3つの交流電流を流します。
![2019-02-07 19 54 12](https://user-images.githubusercontent.com/45890168/52406900-2879fe00-2b12-11e9-9477-fe6fc20f4db5.png)
図のような磁束分布となり、4極の回転磁界ができます。
![2019-02-07 19 55 48](https://user-images.githubusercontent.com/45890168/52407076-9faf9200-2b12-11e9-9817-8ea504af64b9.png)
電流1周期で中心の固定子コイルが1組分回転するので、回転磁界が1回転するためには2周期必要。
![2019-02-07 19 58 44](https://user-images.githubusercontent.com/45890168/52407171-dab1c580-2b12-11e9-8457-0c0a0a2a4c15.png)
つまり、回転数N[rps]は
N=2f/P
f:交流電源の周波数、P:極数
です。

なので今回はf=60Hz,P=4なので、N=30[rps]です。

この送風機の近くで測定した結果を見てみましたが、30Hzでのピークはないです。。
![2019-02-07 18 46 07](https://user-images.githubusercontent.com/45890168/52402854-ad601a00-2b08-11e9-9c3c-812e5795fa63.png)

**Comment by yokozawa1985** [comment]
ありがとうございます。
一瞬送風機を止めてみればよかったですね。
次やりましょう。

**Comment by imyukino** [comment]
簡単に卒論にまとめてのせておきます

横澤さんお忙しいのにわざわざありがとうございます！

**Comment by TatsukiWashimi** [comment]
今さっきこのissueの存在に気づきました。
私の方で進めているEXC磁場データの解析の進捗は#115に挙げていくので、共通する部分は一緒に理解していきましょう

**Comment by yokozawa1985** [comment]
お疲れ様でした!
closeします。
