### ISSUE TITLE
バードウォッチング＠クリーンブース

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#81]
クリーンブースに生息するとされるオンドトリを見つけ、写真におさめる。

以下に記されているように、オンドトリはBOOTHに生息しているとしかわかっていない。
ある個体はChamberに貼り付けられていたりする。

> $ less /opt/rtcds/kamioka/k1/target/k1rack/db/example_rack.db | grep -e 'K1:PEM-TEMPERATURE.*BOOTH_.*'

- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_EYC1F")
- [ ] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_EYC2F")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_EXC1F")
- [ ] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_EXC2F")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_EYV")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_MCF")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_PRM")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_BS")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_PSL")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_PR2")
- [ ] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_PR3")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_SR2")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_IXA")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_IYA")
- [x] grecord(ai,"K1:PEM-TEMPERATURE_BOOTH_SR3")

チェックできたら、PEMMAPにその場所を反映する。

**Comment by MiyoKouseki** [comment]
BS Chamber 
![image](https://user-images.githubusercontent.com/24282734/50810620-d6e12680-134d-11e9-9ef9-ed0f94fb221f.png)

SR2  Chamber
![image](https://user-images.githubusercontent.com/24282734/50810645-fbd59980-134d-11e9-9c89-3e964387c34a.png)

SR3 Chamber
![image](https://user-images.githubusercontent.com/24282734/50810648-08f28880-134e-11e9-997c-acf729e2cf81.png)

PR2 Chamber
![image](https://user-images.githubusercontent.com/24282734/50810665-1e67b280-134e-11e9-8844-ce99cd9ac3ca.png)

**Comment by MiyoKouseki** [comment]
#82 ではクリーンブースから飛び去ったオンドトリの生息場所を特定する試みがなされている。

**Comment by MiyoKouseki** [comment]
@TomohiroY クライオブースのバードウォッチよろしくおねがいします。

**Comment by yokozawa1985** [comment]
PR booth(おそらくPRM)
![img_2080](https://user-images.githubusercontent.com/6629732/50887944-cefdb100-1437-11e9-919a-23297b8bfa2e.jpg)

**Comment by yokozawa1985** [comment]
MCF(クリーン入ってすぐのところ)
![img_2078](https://user-images.githubusercontent.com/6629732/50888042-0cfad500-1438-11e9-9d0e-4d7efb58e3f5.jpg)

**Comment by yokozawa1985** [comment]
PSL(入ってすぐのところ)

![img_2075](https://user-images.githubusercontent.com/6629732/50888111-42072780-1438-11e9-8798-bbcd613014fe.jpg)

**Comment by TatsukiWashimi** [comment]
親機@計算機室入って右側すぐ
![oyaki](https://user-images.githubusercontent.com/18456905/50936283-669fe580-14b2-11e9-9b37-9ef2ca77de30.jpg)

digital room@計算機室入って右側の壁の中央付近
![digitalroom](https://user-images.githubusercontent.com/18456905/50936439-08273700-14b3-11e9-867f-77136640c818.jpg)

FieldOutDR@中央部入り口ドア付近
![fieldoutdr](https://user-images.githubusercontent.com/18456905/50936595-a4e9d480-14b3-11e9-98e9-33602e9099e1.jpg)

FieldCenter@中央部入り口から見て右側の壁中央付近の配電盤?の上
![fieldcenter](https://user-images.githubusercontent.com/18456905/50936629-cd71ce80-14b3-11e9-90ad-343ae8e32807.jpg)
![fieldcenter_unzoom](https://user-images.githubusercontent.com/18456905/50936771-6274c780-14b4-11e9-8667-2f27652089d9.jpg)


中継2@BS付近の角
![chukei2](https://user-images.githubusercontent.com/18456905/50936322-92bb6680-14b2-11e9-9811-e270510e2486.jpg)

ioo@エレキラックIOOの上部
![ioo](https://user-images.githubusercontent.com/18456905/50936357-b41c5280-14b2-11e9-99d9-517ff6ac5213.jpg)

ixa@IXAビームダクトの、Aチェンバーのブースに一番近い支柱
![ixa](https://user-images.githubusercontent.com/18456905/50936464-1bd29d80-14b3-11e9-8d80-e4179c8c6ba3.jpg)

iya@IYAビームダクトの、Aチェンバーのブースに一番近い支柱
![iya](https://user-images.githubusercontent.com/18456905/50936520-5ccab200-14b3-11e9-90a1-774eba836a28.jpg)

crydr@中央低温鏡機械室の奥側のテントの棚
![crydr](https://user-images.githubusercontent.com/18456905/50936909-f6df2a00-14b4-11e9-812f-4047257f6382.jpg)

crydr2@中央低温鏡機械室の手前側のテントの棚
![crydr2](https://user-images.githubusercontent.com/18456905/50937022-51788600-14b5-11e9-9c27-2409ee745ae6.jpg)

**Comment by TatsukiWashimi** [comment]
すみません、#82に投降するものを間違えてこちらに書いてしまいました。
私の載せた写真は全てfieldです。

**Comment by MiyoKouseki** [comment]
## IXA Booth
![image](https://user-images.githubusercontent.com/24282734/50939752-7672f600-14c1-11e9-84a0-925a90547606.png)

**Comment by TomohiroY** [comment]
EXC
入って右側中央, 冷凍機機械室の扉の前
![img_0716](https://user-images.githubusercontent.com/46213521/50940857-fd29d200-14c5-11e9-924d-f395c5452b4c.jpg)

**Comment by TomohiroY** [comment]
EXA
EXAタンクのアーム側（写真奥行きがEXC）
![img_0720](https://user-images.githubusercontent.com/46213521/50940927-3bbf8c80-14c6-11e9-9642-873c32f9cf8b.jpg)

**Comment by TomohiroY** [comment]
EYC
写真右手がBRT, 冷凍機の上に置いてある。
![image](https://user-images.githubusercontent.com/46213521/50941018-9b1d9c80-14c6-11e9-8276-ef91eff8b729.png)

**Comment by yokozawa1985** [comment]
みなさま、ありがとうございます。
ただ、写真や図のこのサイトでの公開は控えていくべきだと思いますので、まとめ次第このページの写真は削除致します。

**Comment by yokozawa1985** [comment]
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9589
に移行して、写真は削除致しました。

**Comment by yokozawa1985** [comment]
残りPR3、なぜか見つからなかったです。。。

**Comment by yokozawa1985** [comment]
あと、EndClean booth2Fの写真がまだ取れていない。。。

**Comment by yokozawa1985** [comment]
命名という目的は達成できたと思うのでこの部分のissueとしてはcloseします。
