### ISSUE TITLE
バードウォッチング＠FIELD

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#82]
せっかくなのでFIELDのバード撮影も行ってみる。
> $ FrChannels /frame0/full/12304/K-K1_C-1230400000-32.gwf | grep K1:PEM-TEMPERATURE_FIELD_

- [x] K1:PEM-TEMPERATURE_FIELD_DR
- [x] K1:PEM-TEMPERATURE_FIELD_OUTDR
- [x] K1:PEM-TEMPERATURE_FIELD_CENTER
- [x] K1:PEM-TEMPERATURE_FIELD_MCRACK
- [x] K1:PEM-TEMPERATURE_FIELD_EYA
- [x] K1:PEM-TEMPERATURE_FIELD_CRYDR
- [x] K1:PEM-TEMPERATURE_FIELD_CRYDR2
- [x] K1:PEM-TEMPERATURE_FIELD_IXA
- [x] K1:PEM-TEMPERATURE_FIELD_IYA
- [x] K1:PEM-TEMPERATURE_FIELD_PSL
- [x] K1:PEM-TEMPERATURE_FIELD_PSL2
- [x] K1:PEM-TEMPERATURE_FIELD_EXA
- [ ] K1:PEM-TEMPERATURE_FIELD_PX

**Comment by MiyoKouseki** [comment]
## 
### FIELD_DR
![image](https://user-images.githubusercontent.com/24282734/50878188-cf3a8400-1418-11e9-996e-5b2426a9a198.png)

### CRYDR
![image](https://user-images.githubusercontent.com/24282734/50878225-f1340680-1418-11e9-8588-c391ffe97982.png)


### CRYDR2
![image](https://user-images.githubusercontent.com/24282734/50878230-fbee9b80-1418-11e9-913c-51e07c511f46.png)

**Comment by TatsukiWashimi** [comment]
親機@計算機室入って右側すぐ
![oyaki](https://user-images.githubusercontent.com/18456905/50936283-669fe580-14b2-11e9-9b37-9ef2ca77de30.jpg)

digital room@計算機室入って右側の壁の中央付近
![digitalroom](https://user-images.githubusercontent.com/18456905/50936439-08273700-14b3-11e9-867f-77136640c818.jpg)
![digitalroom_unzoom](https://user-images.githubusercontent.com/18456905/50938750-fb0f4580-14bc-11e9-85ad-462dcfd665b4.jpg)


FieldOutDR@中央部入り口ドア付近
![fieldoutdr](https://user-images.githubusercontent.com/18456905/50936595-a4e9d480-14b3-11e9-98e9-33602e9099e1.jpg)
![fieldoutdr_unzoom](https://user-images.githubusercontent.com/18456905/50938742-f34fa100-14bc-11e9-9102-8812fc48675e.jpg)


FieldCenter@中央部入り口から見て右側の壁中央付近の配電盤?の上
![fieldcenter](https://user-images.githubusercontent.com/18456905/50936629-cd71ce80-14b3-11e9-90ad-343ae8e32807.jpg)
![fieldcenter_unzoom](https://user-images.githubusercontent.com/18456905/50936771-6274c780-14b4-11e9-8667-2f27652089d9.jpg)


中継2@BS付近の角
![chukei2](https://user-images.githubusercontent.com/18456905/50936322-92bb6680-14b2-11e9-9811-e270510e2486.jpg)
![cukei2_unzoom](https://user-images.githubusercontent.com/18456905/50938765-082c3480-14bd-11e9-945a-9c2d4f959c48.jpg)

ioo@エレキラックIOOの上部
![ioo](https://user-images.githubusercontent.com/18456905/50936357-b41c5280-14b2-11e9-99d9-517ff6ac5213.jpg)
![ioo_unzooom](https://user-images.githubusercontent.com/18456905/50938769-0f534280-14bd-11e9-87c3-a7b7affede2b.jpg)

ixa@IXAビームダクトの、Aチェンバーのブースに一番近い支柱
![ixa](https://user-images.githubusercontent.com/18456905/50936464-1bd29d80-14b3-11e9-8d80-e4179c8c6ba3.jpg)
![ixa_unzoom](https://user-images.githubusercontent.com/18456905/50938783-1f6b2200-14bd-11e9-976b-42faca2e5142.jpg)

iya@IYAビームダクトの、Aチェンバーのブースに一番近い支柱
![iya](https://user-images.githubusercontent.com/18456905/50936520-5ccab200-14b3-11e9-90a1-774eba836a28.jpg)
![iya_unzoom](https://user-images.githubusercontent.com/18456905/50938789-26923000-14bd-11e9-97e0-3f1cc70fe05d.jpg)


crydr@中央低温鏡機械室の奥側のテントの棚
![crydr](https://user-images.githubusercontent.com/18456905/50936909-f6df2a00-14b4-11e9-812f-4047257f6382.jpg)

crydr2@中央低温鏡機械室の手前側のテントの棚
![crydr2](https://user-images.githubusercontent.com/18456905/50937022-51788600-14b5-11e9-9c27-2409ee745ae6.jpg)

**Comment by TomohiroY** [comment]
EXA
EXAチェンバーとEXCクライオスタットのちょうどあいだ
![img_0721](https://user-images.githubusercontent.com/46213521/50941396-1b90cd00-14c8-11e9-9619-97965be46508.jpg)

![img_0723](https://user-images.githubusercontent.com/46213521/50941421-2b101600-14c8-11e9-8340-9915e6c0f8b6.jpg)

**Comment by TTanakaTT** [comment]
PSL
![img_4229](https://user-images.githubusercontent.com/44667886/51006040-b8b13b80-1584-11e9-9fee-444dbe378650.jpg)

MCRACK
![img_4230](https://user-images.githubusercontent.com/44667886/51006041-b9e26880-1584-11e9-8fb9-2ac4bc750988.jpg)

**Comment by yokozawa1985** [comment]
あとPXで完了。

**Comment by MiyoKouseki** [comment]
- [] PXは自分が取りに行きます。
たぶん２月終わり？GIFでメンテに行く時に。

**Comment by yokozawa1985** [comment]
坑内写真をKAGRA officialではないところに置いておくのはどうかなと思いますので、確認後別の場所に移します。

**Comment by yokozawa1985** [comment]
みなさん、ありがとうございます！

**Comment by yokozawa1985** [comment]
三代さん、山田さん、鷲見さん、T田中さん、写真ありがとうございます。先ほどGitHub上から削除致しました。
現在、以下のdocumentにまとめております。
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=9589

**Comment by MiyoKouseki** [comment]
とりあえず、PX1は場所もわかるし写真を取るだけ。
何処にあるか調べるという点でこのIssueは片付いている。
なのでレビュー待ち。

**Comment by yokozawa1985** [comment]
今日のmeeting後にcloseしましょう。

**Comment by yokozawa1985** [comment]
PX1のおんどとりの写真をとるissueを立ててclose
