### ISSUE TITLE
12月 ~1月にかけてのPSLの加速度計とマイクの時間変化

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#83]
年末の人もファンもない静かな時と、新年に入ってファンが入った後でPEMに変化があるのかを調べる。
すぐにやります。

**Comment by MiyoKouseki** [comment]
openしてから2週間が経ちました。

目的やcloseするためのタスクリストが書かれていると、他の人が参加しやすいです。

**Comment by yokozawa1985** [comment]
- [ ] dataviewerのminutes trendを使ってPEMの時間変化の図を書いてみる

- [ ] GWpyを使って、スペクトログラムを書いてみる。

- [ ] 今週末までまだopenだったら一旦closeする。

**Comment by MiyoKouseki** [comment]
優先順位が高くないので、good first issue ラベルをつけました。
だれか手の空いた人にやってもらいましょう。

**Comment by yokozawa1985** [comment]
dataviewerでminute RMS trendが書ければいいけど、minutes min, max, meanは意味ないことにやり始めてから気がついた。。
RMSも保存されていたはずなので、そちらでやってみる。

**Comment by yokozawa1985** [comment]
べつissueを立ち上げたのでclose
