### ISSUE TITLE
MokuLabのノイズ源？

### ISSUE THREAD

**Issue by TTanakaTT** [gw-pem/kagra-pem#84]
**問題について** 
PSLルームでケーブルだけをMokuLabにつないだ状態でもMokuLabにRFノイズが入った

**正しい状態** 
RF測定におけるノイズを無くす
候補としては地面やケーブル、定盤を伝って何かの信号が取得されたか
MokuLabの電源がノイズを出している

## ToDo
- [ ] 電源を変えるもしくは離した場所に置いた場合とのノイズの比較
- [ ] 電源由来のノイズがない状態でケーブルのみでPSLルーム内などを測定
- [ ] 電源ノイズの評価および対策

**Comment by yokozawa1985** [comment]
RF測定における、ですね。

**Comment by koji-n** [comment]
@TTanakaTT くん、
雑音が増えたというのは、具体的にはどういう感じでしょうか。
ブロードですか?ピークですか?コーム状ですか?
その典型的な周波数は何Hzでしょうか。
ケーブルというのはBNCケーブルですか。
また、ケーブルは何mでしょう。
それから、ケーブルの終端処理はどうしていましたか。
MHz程度の測定をする際は、インピーダンスマッチを考えないと、反射などの影響ですぐにちゃんとした測定ができなくなります。

予想ですが、これは単にケーブルがアンテナになって環境電波を拾っているのではないかと思います。
ケーブルの長さを変えたら測定される雑音の典型的な周波数は変わりませんか?

**Comment by TTanakaTT** [comment]
その時のことについては記録していないので、あまり具体的には覚えていないのですが、
EoMやAoMの周波数、あとよく分からない周波数でいずれもピーク状に雑音が入っていました。特にAoMのものが大きかったと記憶しています。
ケーブルはBNCで終端は何も繋がっていない状態です。長さは覚えていません。

インピーダンスマッチやケーブルのアンテナ化などについては全く考えていなかったため、意見をいただけて非常に嬉しいです。
後日改めてアンテナ化などについては評価しようと思います。

**Comment by yokozawa1985** [comment]
OKです。おそらくアースがうまく行っていなかったり、(主に僕自身の)知識不十分で解析が進行していたと思われます。closeします。
