### ISSUE TITLE
XアームのCMRR

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#85]
### 目的　（なぜそれをやりたいのか、）
Xアーム共振器のCMRRを求める。Xアームコミッショニングのまとめで必要。
共振器は差動増幅器なので、ITMXとETMXの2つの鏡の同相揺れは、理想的には出力信号である基線長変動に現れない。しかしそれぞれの鏡の外乱応答に差があると現れてしまう。CMRRはそれを評価するための指標。

CMRRは、CMRR = H_diff/H_commで定義する。
同相伝達関数：Commonの地面振動揺れからPDH信号への伝達関数＝H_comm
差動伝達関数：Differentialの地面振動揺れからPDH信号への伝達関数＝H_diff

Commonの地面揺れは、EXVとIXVの2台の地震計からもとめる。Differentialの地面揺れも。
CSDから伝達関数を計算。

予想
- 脈動以上では、2点間でコヒーレンスを持たないので、Common揺れもDifferential揺れも2点の地面振動の2乗和になって両者同じPSD。なのでCMRRは、振り子由来のものを反映する。
- 脈動では2点でコヒーレンスを持っているので、すこしCommonのほうがDifferentialよりも大きい。なのでその場合、CommonとDifferentialのPSDが両者違うので、CMRRは、地面と振り子どっちの寄与なのか区別できない。たぶん。
- 脈動以下では、地震計は並進をみれていないので、CommonとDifferentialの揺れは意味を持たない。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 伝達関数をもとめてCMRRを求める。
 - [ ] 完了。Klogに投稿

### 参考
[Definition of Xarm Commissioning](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=8343)

### レビュー用まとめ　（ToDoが終わっているかどうか簡潔に示す）
1.
2.
3.
4.

**Comment by MiyoKouseki** [comment]
これそろそろ復活させたい。

**Comment by MiyoKouseki** [comment]
たしかにそろそろ復活させたい。

**Comment by yokozawa1985** [comment]
こちらすでにD論として進んでいるようですので、closeします。
再開が必要な場合は、再度issueを開いてください。
