### ISSUE TITLE
マイク測定の原理

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#86]
そもそもマイクってどのように信号取得をするのか？
今用いているマイクはどのようなものかを可能なかぎりまとめてみる。

**Comment by yokozawa1985** [comment]
本で測定原理を見てみたり、ネットから情報を集めて、まずはここにコメントをして最終的には卒論のレポートにする。

**Comment by KiichiKaihotsu** [comment]
アコー社に直接問い合わせたところ、丁寧な回答がありました。

以下まとめ

- TYPE 7147Aはエレクトレット型コンデンサーマイクロホン。
- 耳の鼓膜の役割を果たす振動板があり、小さい隙間を隔てて電極は設置されている。振動板と電極でコンデンサーの役割を果たしている。
- 振動板が揺れるとコンデンサーの静電容量が変化し、それが電圧の変化となる。

コンデンサーマイクロホンにはバイアス型とエレクトレット型という2種類がある。

- バイアス型は直接直流電圧を加える方法。-->直流電圧電源が必要となる。しかし構造は簡単。

- エレクトレット型は直流電圧の代わりに永久双極子である高分子フィルムを設けて、直流電圧電源の代わりを担っている。-->電源を必要としないので便利。

**Comment by yokozawa1985** [comment]
ありがとうございます。直接会社に聞いたんですね、すばらしいです。
(一般的なマイクのPa->Vに変える原理くらいに考えてました。)

**Comment by yokozawa1985** [comment]
OKです。closeします。
