### ISSUE TITLE
磁束計測定の原理

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#87]
そもそも磁束計はどのような原理でデータ取得を行っているのかをまとめる。

**Comment by yokozawa1985** [comment]
本で測定原理を見てみたり、ネットから情報を集めて、まずはここにコメントをして最終的には卒論のレポートにする。

**Comment by TatsukiWashimi** [comment]
Mag-13 製品ページ
[https://www.rockgateco.com/product/mag-13/](https://www.rockgateco.com/product/mag-13/)

**Comment by yokozawa1985** [comment]
ありがとうございます!!
今読むと頭に入ってこないので頭が冴えているときに読みます。。。

**Comment by yokozawa1985** [comment]
OK。closeします。
