### ISSUE TITLE
Q値って何か調べてみる。

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#88]
ラインノイズを評価する際に、時々Q値というのが出てくる。
Q値で何か調べてみる。
何を言っているのかがわからない場合はここにコメントしてください。

**Comment by yokozawa1985** [comment]
卒論にかけていたらcloseします。

**Comment by TatsukiWashimi** [comment]
> 卒論にかけていたらcloseします。

どうでしたか？

**Comment by yokozawa1985** [comment]
とりあえず、closeして今度聞いてみます。
