### ISSUE TITLE
Python でフレームファイルを読む

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#90]
## 背景 
Frame file からデータを読める人が少ない。
なので簡単なPythonコードを準備して、もっと人を増やしたい。

### 説明すること/伝えたいこと
* gwpyを使って時系列データを取り出して png ファイルに保存するやり方
* オブジェクトを意識したプログラミング
* ライブラリのドキュメントの読み方
* dataviewer で時系列を取ったり diaggui で周波数列を export するのは卒業しましょう。実験する人ならフレームファイルからやりましょう。

### 説明しないこと/自力で頑張ってほしいこと
* 英語では説明しません。 gwpy やmatplotlib などの本家の英語ドキュメントから必要な情報を取ってこれない人を対象にしています。
* for とか if とかの文法。「みんなのpython」がオススメです。
* 環境の構築方法は説明しません。どこかの ctr計算機に gwpy を入れてるので ssh して使ってください。しかしリソースも限られているので、自分の計算機に構築することをお勧めします。ググって頑張ってください。
* フレームファイルのダウンロード方法は説明しません。過去の全データは柏の m31 にあるのでログインして適当にダウンロードしてください。アカウントがない場合は田越さんに申請してください。神岡にいる人は最大で2週間程度前までならctr計算機からフレームファイルが見れます。
* nds を使った TimeSeries オブジェクトの取り方は次回。これは神岡にいる人しか恩恵を得ないし、あと、実験をやる人ならせめて最低限フレームファイルから読めるようになってほしいので、まずはフレームファイルのみのやり方を説明します。

**Comment by MiyoKouseki** [comment]
https://github.com/MiyoKouseki/miyopy/blob/master/miyopy/example/gwpy/read_timeseries_with_lalframe.py

にコードを置きました。

以下のような内容です。
https://github.com/MiyoKouseki/miyopy/blob/99cb406feafda7cb3d18bae9ee6301c889e01533/miyopy/example/gwpy/read_timeseries_with_lalframe.py#L7-L15

**Comment by MiyoKouseki** [comment]
もし神岡にいるなら、
> scp k1ctr7:/frame0/full/12311/K-K1_C-1231133824-32.gwf .

でダウンロードできます。

**Comment by MiyoKouseki** [comment]
k1ctr7でGwpyが使えるようになりました。
デフォルトでPython3です。

**Comment by MiyoKouseki** [comment]
> k1ctr7でGwpyが使えるようになりました。
デフォルトでPython3です。

k1ctr7ではなく，k1ctrZZでした。IPは「にーよんご」です。
Python3.5.3です。

**Comment by yokozawa1985** [comment]
あと、柏の計算機m31でも
TimeSeries.read
のコマンドを使用できることは確認しました。
GWpy含めいくつかのsoftwareのバージョンが古いのでもどかしいところがあるかもしれませんが、
すべてのframe fileが揃っている環境で解析できることが重要なので、こちらも試してみてください。

**Comment by MiyoKouseki** [comment]
とりあえず、必要なことはここに書いたので、後で誰かが動かしてみてほしい。
もしわからないことやバグがあればOpenし直してもらう。

**Comment by ckozakai** [comment]
三代くんのコードやGWpyのドキュメント https://gwpy.github.io/docs/stable/index.html を参考に、柏サーバ向けのサンプルコードを作りました。
/home/chihiro.kozakai/detchar/analysis/code/gwpy/example/example_plot.py
時系列・スペクトル・スペクトログラム・Q変換ができます。
複数チャンネル・複数ファイルが扱えます。
png・txt 出力ができます。

**Comment by yokozawa1985** [comment]
ありがとうございます！

**Comment by ckozakai** [comment]
各種プロット用に、もう少し実用的なサンプルコードを追加しました。GPS時刻やチャンネル名を書き換えればすぐ使えます。
/home/chihiro.kozakai/detchar/analysis/code/gwpy/example/ 以下に置いておきます。
example_timeseries.py, example_spectrum.py, example_spectrogram.py

バッチジョブ用のサンプルコードもここに置いておきます。詳しくは README を読むか私に聞いてください。

**Comment by MiyoKouseki** [comment]
@ckozakai 小坂井さんのファイルは自分のアカウントだと権限がなくてみれませんでした。。サンプルコードはどこかまとめて置いときませんか？DetcharかPEMのリポジトリにでも？

**Comment by ckozakai** [comment]
@MiyoKouseki あれ、榎本くんはみれたっぽいのですが。昨日の17:50分ごろにパーミッション変更したんですが、やってみたのはその後ですか？
github におきたいと思ったんですが、どうも柏サーバからはリモートリポジトリに直接アクセスできないっぽいのでどうしようかと思っていたところです。

**Comment by MiyoKouseki** [comment]
@ckozakai その前でした。。

**Comment by MiyoKouseki** [comment]
サンプルファイルがmasterから消えていたのですが、developにありました。
https://github.com/MiyoKouseki/miyopy/tree/develop/miyopy/example/gwpy

**Comment by MiyoKouseki** [comment]
サンプルファイルがmasterから消えていたのですが、developにありました。
https://github.com/MiyoKouseki/miyopy/tree/develop/miyopy/example/gwpy

**Comment by MiyoKouseki** [comment]
サンプルファイルがmasterから消えていたのですが、developにありました。
https://github.com/MiyoKouseki/miyopy/tree/develop/miyopy/example/gwpy

**Comment by MiyoKouseki** [comment]
サンプルファイルがmasterから消えていたのですが、developにありました。
https://github.com/MiyoKouseki/miyopy/tree/develop/miyopy/example/gwpy
