### ISSUE TITLE
送風機付近の音場の特徴づけ

### ISSUE THREAD

**Issue by yokozawa1985** [gw-pem/kagra-pem#91]
通称No.3の音場スペクトルにおける特徴づけをまずは自分自身で考察してみてください。
可能だったら、基準のスペクトルとの比か差を計算するようなプログラムを書いてみてください。

**Comment by yokozawa1985** [comment]
ピークを評価する際には、絶対値の大きさもそうですが、相対的な大きさで評価することも大切です。(縦軸で、**Pa/rHz以上のラインを抽出するだけではなく、ノイズフロアから**倍のラインを抽出するということです。)
まとめるかどうか迷った際には、自分のやる気と使える研究時間を考慮しながらできるだけ多くまとめられるといいとおもいます。
->つまり、よし、まとめるぞ!という気になっていたらまとめたほうがいいでしょう。

**Comment by KiichiKaihotsu** [comment]
ノイズフロアからというのは基準点とした機械室でのデータからどれだけ大きいかということですか？
基準点からということでしたら、やはり各データと基準点との差を取ってピークをみていくのがいいですか？

**Comment by yokozawa1985** [comment]
ここで言ったノイズフロアは、ピークの裾のことです。つまり、図の青い線のことをノイズフロアと言います。
それとは別に、各データと基準点の差は取ってみるといいと思います。

<img width="858" alt="2019-01-11 18 59 51" src="https://user-images.githubusercontent.com/6629732/51027018-3865f700-15d3-11e9-9fa9-4f5b0309da0b.png">

**Comment by KiichiKaihotsu** [comment]
ありがとうございます。
各データのノイズフロアからということですね。
質問ばかりですいません、"ノイズフロアから倍のライン"というのはノイズフロアのPa/rHzの値の2倍という認識であっていますか？

[可能だったら、基準のスペクトルとの比か差を計算するようなプログラムを書いてみてください。]
差分をとるというタスクですが、gnuplotで差分をだしてプロットすることはできました。
下図はこのissueである送風機付近の音場[No.3]から基準点(機械室)[No.9]を引いて、プロットしたものです。
![map-test](https://user-images.githubusercontent.com/45889411/51037083-89391800-15f2-11e9-9814-a61b088700e4.png)

**Comment by yokozawa1985** [comment]
いえいえ、むしろもっと質問してくださったら嬉しいです。わからない単語が出てきたり、どうやって解析したらいいかわからない時は即座に聞いてください。

**Comment by yokozawa1985** [comment]
> 質問ばかりですいません、"ノイズフロアから倍のライン"というのはノイズフロアのPa/rHzの値の2倍という認> 識であっていますか？
はい、そうです。
本当にちゃんとした解析を行う場合は、この論文のような解析が必要なのですが、今回は、目で約2倍とかでもいいと思います。
http://iopscience.iop.org/article/10.1088/1742-6596/363/1/012037/pdf

すみません、差のプロットだけだとちょっと特徴をつかむのが大変なので、[3]と[9]をオーバーラップさせた図を作成していただけますでしょうか？

**Comment by KiichiKaihotsu** [comment]
ありがとうございます。

機械室[No.9]と送風機前[No.3]のオーバーラップさせた図です。
![map-over-1-3](https://user-images.githubusercontent.com/45889411/51097331-94649180-1806-11e9-80b2-333af6768750.png)

機械室は全体的のオーダーが低いのと、送風機前は高周波でピークがいくつか立っているのが目立ちます。2つに共通しているのは60Hz手前でピークを持っているところです。

**Comment by yokozawa1985** [comment]
なるほど、総じて一桁大きさが違うわけですね、しかもピークの高さも周波数も深い共通点が悪わけではなさそうなところが多いですね。
こうなってくると差はあまり参考になる指標ではないかもしれません、比の方が情報としては重要かもしれません
(ノイズフロアが何倍大きいという表現ができる。)

**Comment by KiichiKaihotsu** [comment]
わかりました。
とりあえず、各場所が機械室に比べてどれくらい大きいノイズなのかを見ていこうと思います。

**Comment by yokozawa1985** [comment]
OK!

**Comment by yokozawa1985** [comment]
一旦closeします。
