### ISSUE TITLE
おんどとりの電波強度

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#92]
**問題について** 何が問題か書いてください
おんどとりの電波強度テストをすると、電波の弱いチャンネルや繋がっていないチャンネルがある
![ondotori-check-20190110am1142](https://user-images.githubusercontent.com/18456905/50942813-49c4db80-14cd-11e9-985c-38240eceafb2.png)

**正しい状態** どうなっているべきか書いてください
すべてのチャンネルが最低でも緑色になるべきか

完了したら、Klogに投稿！

**Comment by TatsukiWashimi** [comment]
親機1 (計算機室のもの)の子供たちです

**Comment by yokozawa1985** [comment]
いくつか電波が届いていないものもありそうです。。(instrumentsが増えたのが原因か？)
なので過去データを洗ってみて電波不調そうなチャンネルを見てみます。

**Comment by yokozawa1985** [comment]
アンテナを調整して幾つかのものは改善することができました。
あと、Front2FにRelayをおきました。
cryoconみたいなデータ取得stateみたいなものを余力があったら作ってみたいです。
Review待ちに移行

**Comment by yokozawa1985** [comment]
電波強度と電池消耗の関係性や、relayを中央部に増やすことも検討か？
少なくとも、ラックに関しては、電波がよく通るアンテナ位置の調整と
温湿度ディスプレイがすぐに確認できるような設置方法に変える。

**Comment by yokozawa1985** [comment]
アンテナ方向やpositionの微調整を行うことによりcenter areaは問題なくなったと思われる。close
