### ISSUE TITLE
EYVに気象系のインストール

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#94]
### 目的　（なぜそれをやりたいのか、）
#93 で指摘されているとおり、EYVに気象系がない。
インストールする。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. 気象系のアンプをつくる
 - [ ] 2. キャリブレーションする
 - [ ] 3. 設置する
 - [ ] 完了。Klogに投稿

**Comment by yokozawa1985** [comment]
気象計の政策と動作確認をgood first issueにしておきましょう。

**Comment by yokozawa1985** [comment]
おんどとりの追加購入ができたことにより、地震計関連以外の温度計やその回路関係は、kokeyamaさん以来のもののみとなった。なので、気象計関係は一旦closeにして、新たにPEMとして興味がある方にやってもらうにします。
