### ISSUE TITLE
summary pageのseiの更新

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#95]
チャンネル名が変わっているせいでうまく描画できていない。

チャンネル名が変更されたら、変えることにする。

**Comment by yokozawa1985** [comment]
来週早々にチャンネル決着つけましょう。

**Comment by MiyoKouseki** [comment]
地震計のチャンネル名は決まっているので、もう名前を変更して、SummaryPageを更新してもいい気がする。

**Comment by yokozawa1985** [comment]
更新完了でしょうか？？？

**Comment by MiyoKouseki** [comment]
放置。チャンネル名を直すだけですが、だれかやってくれたらうれしー
