### ISSUE TITLE
有限要素解析ソフトを用いた環境ノイズの理解

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#96]
**背景**
PEMでは様々な環境ノイズを測定している(していく)が、直接測定が難しい場所における環境ノイズの推定や、ノイズ源の特定・ノイズ削減のためには、有限要素解析ソフトを用いたシミュレーションが有効であると考えられる。
(乱数を振っているわけではないので正確にはシミュレーションではないが、ここでは便宜上シミュレーションと呼ぶ。)

**提案**
ムラタソフトウェア株式会社の[Femtet®](https://www.muratasoftware.com/products/explanation/)というソフトを紹介する。

これは私がANKOKでTPC開発をするときに電場計算や熱収縮計算をするのに使っていたが、他にも磁場解析、電磁場解析、音波解析など、PEMで役立ちそうな機能がそろっている。

[#64](https://github.com/gw-pem/kagra-pem/issues/64)や[#65](https://github.com/gw-pem/kagra-pem/issues/65)のstudyを、単に測定するだけではなく、シミュレーションも合わせて行うのはどうでしょうか。
ただし、priorityは要議論。

**課題**
Femtetはwindowsでしか動かせない。
3次元解析をまともに行うには、結構いいスペックのPCが必要になる

**Comment by TatsukiWashimi** [comment]
アカデミック版のライセンス料は2万円/1年 です。(2016年までは20万円していた。)
 とりあえず、私が書いている共同利用申請の予算のところに入れておきました。

**Comment by MiyoKouseki** [comment]
すごく面白そうです。

**Comment by yokozawa1985** [comment]
比較的いいwindows PCワークステーション持ってます。スペックは明日お伝えします。
ライセンスもすぐに取ってもいいでしょう。

**Comment by TatsukiWashimi** [comment]
先ほど横澤さんからもらったスペックシートから抜粋すると、
・[DELL precision 5810 XCTO](https://i.dell.com/sites/doccontent/shared-content/data-sheets/ja/Documents/156248_jp_eu_pa_fy15q3_specsheet_ws_t5810_online.pdf)
・CPU : Xeon E5-1603 v4 (4C, 2.8GHz, 2133MHz, 10MB, 140W)
・RAM : 16GB (4x4GB) 2400MHz DDR4 RDIMM ECC
ですね。

早稲田で使っていたのは
・[Dell Precision T3600](https://www.dell.com/downloads/jp/products/precn/dell-precision-t3600-datasheet-jp.pdf)
・CPU : Xeon  E5-1620   (3.60GHz)
・RAM : 16GB
でした。

とりあえず動かしてみる分には申し分ないと思います。

**Comment by yokozawa1985** [comment]
郵送手配のメールを出しました。

**Comment by TatsukiWashimi** [comment]
あと、山本さんからの質問にあった「時間依存性の解析はできるのか」という点ですが、
調和解析、過度解析、共振解析といった時間依存性の解析が確認できました。
[https://www.muratasoftware.com/products/table/](https://www.muratasoftware.com/products/table/)

**Comment by TatsukiWashimi** [comment]
大阪市大から届いたwindows10 workstationを解析棟2階ポスドク部屋の私の机に立ち上げ、Femtetをインストールしました。
↓は静磁場解析の例題(永久磁石)をやってみた結果です。
![femtet_test](https://user-images.githubusercontent.com/18456905/51463269-1f64ff00-1da6-11e9-8997-896c6260af12.png)

**Comment by yokozawa1985** [comment]
@TatsukiWashimi さん、このissue、内容が大きいので、一旦closeして、小さなissueで再度立ち上げ直しましょう。

**Comment by yokozawa1985** [comment]
解析PCが届いたということ、今後はもう少し細かいissueでtaskをこなしていく(すでに進行している)ためcloseします。
