### ISSUE TITLE
EXVの地震計から信号が来ていない

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#97]
**問題について** 何が問題か書いてください
1/15,6ごろから、EXVの地震計から信号が来ていない。
![image](https://user-images.githubusercontent.com/24282734/51451607-74d6e700-1d79-11e9-914b-72c25db25631.png)

**正しい状態** どうなっているべきか書いてください
多分EXVのラック整理の作業でコネクタが抜けたんだと思う。
Xエンド行ってもとに戻しておく。

完了したら、Klogに投稿！

**Comment by MiyoKouseki** [comment]
明日いく。

**Comment by yokozawa1985** [comment]
一応繋いでおいたつもりではいたのですが、間違ってるのかもしれません。確認お願いします。

**Comment by MiyoKouseki** [comment]
CRYのWHフィルターに刺さっていた。写真には3つ移っているが、下の段のWHが正しいやつ。
真ん中のWHに刺さっている。工具類を一切持ってきていなかったので、また明日。
![image](https://user-images.githubusercontent.com/24282734/51507814-0310a300-1e36-11e9-85f6-d2a89d8c2e94.png)


ちなみに、CRYのMNOLが刺さっていたWHフィルターのJGWが更新されていなかったので、更新した。
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=5082

**Comment by MiyoKouseki** [comment]
Xエンドいくときのメモ
- [ ] 3mDsub9pin
- [ ] テプラ。誰が見てもわかるようにラベルを貼り直す。WHにも貼っておけば挿し間違えがおきない。
- [ ] ケーブルタイ
- [ ] 名前タグ
- [ ] 酸素濃度計
- [ ] テスター。マスセンタリングのために必要。
- [ ] 単三電池3つ。マスセンタリング。
- [ ] 精密ドライバー。
- [ ] 透明なケース。IXVでやったように水対策のためにケーブル類をここに入れる。ケーブルが床に置いてあるのでこのケースに入れる。
![image](https://user-images.githubusercontent.com/24282734/51508034-f476bb80-1e36-11e9-8b7d-007d050770c7.png)

**Comment by MiyoKouseki** [comment]
全室のマットの上に置いた明日行けるなら行く。

**Comment by MiyoKouseki** [comment]
ケーブルを挿し直した。
浸水対策でカバーにケーブルをいれた。
![image](https://user-images.githubusercontent.com/24282734/51582735-c2d22300-1f10-11e9-94b1-11fd32baabfb.png)

**Comment by MiyoKouseki** [comment]
EXVの信号が回復したことを確認した。

![image](https://user-images.githubusercontent.com/24282734/51582832-3ecc6b00-1f11-11e9-91df-fc144dcaa48b.png)

IXVTESTとして使っていたEYVの地震計を戻さなければーーー。

**Comment by MiyoKouseki** [comment]
とりあえずklogに投稿したら、レビューに移行する。
- [ ] klog に投稿

**Comment by MiyoKouseki** [comment]
Post した。
http://klog.icrr.u-tokyo.ac.jp/osl/?r=7766

**Comment by yokozawa1985** [comment]
ありがとうございます。closeします。
