### ISSUE TITLE
Cryostat内の磁場測定

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#98]
来週末(1/31)まで、EXCチェンバーが開いていて鏡が入っていないため、チェンバー内部の磁場計測ができるチャンスがある。
(鏡が入っていると、制御用マグネットがあるため、外部から染み込む磁場の評価には適さない)

来週(1/28~)はCalのヘルプに入るため、実質的に動けるのは今週中。

1/22,23 で磁束計固定具の調達と測定練習
1/24, 25 にEXCチェンバー内の測定
といった具合になるか

**Comment by TatsukiWashimi** [comment]
1/22午前の進捗
2本のMag-13を固定する機構として、とりあえず神岡オフィス3階の物置にあった(未使用っぽい)ゴミ箱を拝借した。
![20190122_112726_694](https://user-images.githubusercontent.com/18456905/51511121-59d0a980-1e43-11e9-9473-a2c8dd23baf5.jpg)

Mag-13のx軸方向に2本ならべ、z軸方向が鉛直上向きになっている。
中心間距離は160mm

**Comment by TatsukiWashimi** [comment]
今は今週末の測定に間に合わせるためのやっつけ仕事だが、
坑内の磁場勾配マップを作る際には、塩ビパイプ(もしくはそれに準ずるもの)を使ってきちんしとしたモノを組みたい。
金属を使うと測定に影響する可能性があるのと、ホコリ等を出したくないため、プラスチックが良い

**Comment by TatsukiWashimi** [comment]
これからの予定としては、
1/22 pm : windows workstationの設定のつづき。とPEM meeting
1/23 am : 横澤さんと鷲見でXendへ行き、測定できそうか下見する。
1/23 pm : Front 1Fで磁場勾配測定練習
1/24 : 鷲見、森、開発の3人でEXCチェンバー内外の磁場測定作業
1/25 : 予備日 (鷲見、森)

**Comment by TatsukiWashimi** [comment]
Xendエレキラックのホワイトニングアンプがネジ止めされていない。
周りになさそうだったので、次行くときにcenterから持っていく

**Comment by TatsukiWashimi** [comment]
1/23 pm : 小坂井さんと鷲見で、IYCにて磁場勾配測定の練習を行った。
詳細は #100 の方で。

**Comment by TatsukiWashimi** [comment]
阿久津さんより、WABに関する情報
[JGW-D1808500-v1](https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument)

**Comment by yokozawa1985** [comment]
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=8500

**Comment by TatsukiWashimi** [comment]
メールでも流した通り、本日の測定(冷凍機offのみ)は無事完了しました。
詳細は来週のPME meetingで報告します。

**Comment by TatsukiWashimi** [comment]
2/1の朝をもって、EXCクライオスタット内磁場測定を終了しました。
取得データはwikiにまとめました。
[http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Reports/Mag/](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/PEM/Reports/Mag/)

測定自体は完了したので、このissueはcloseしたいと思います。
データ解析については別のissueを立ち上げます。
