### ISSUE TITLE
Femtet練習 (磁場解析)

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#99]
#96 で導入したFemtetを習得する
まずは磁場解析から

**Comment by yokozawa1985** [comment]
- [ ] もう少し具体的なタスクをあげてください。

**Comment by yokozawa1985** [comment]
@TatsukiWashimi すぐにやるタスクをissueにあげなくても良いですが、もう少し具体的なタスクの記述をお願いします。

**Comment by TatsukiWashimi** [comment]
@yokozawa1985 
フランジが閉まった状態での、クライオスタット内部の磁場の大きさを見積もりたいと思います。

具体的には、#98 で測定したフランジが開いている状態での冷凍機由来の1Hzピーク(冷凍機直上とクライオスタット内部)の比を再現するのを目標にし、それが概ね達成できたらフランジが閉まった状態の磁場を評価する。といった方針です。

**Comment by TatsukiWashimi** [comment]
比較的タスクの少ない来週に取り組みます

**Comment by TatsukiWashimi** [comment]
磁場解析入門セミナー
[https://www.muratasoftware.com/support/download/files_seminar/femtet_gauss_1.pdf](https://www.muratasoftware.com/support/download/files_seminar/femtet_gauss_1.pdf)

Femtet2016オンラインセミナ磁場 1 ～３
[https://www.youtube.com/watch?v=Q-43N5PAdcg](https://www.youtube.com/watch?v=Q-43N5PAdcg)
[https://www.youtube.com/watch?v=0v1XurPEbTg](https://www.youtube.com/watch?v=0v1XurPEbTg)
[https://www.youtube.com/watch?v=IBoef5eG25w](https://www.youtube.com/watch?v=IBoef5eG25w)

**Comment by TatsukiWashimi** [comment]
「磁場解析実習」のスライドに従って、実際に動かしてみた。

![default](https://user-images.githubusercontent.com/18456905/52678716-00592780-2f76-11e9-816f-cbc1decea236.png)
![default](https://user-images.githubusercontent.com/18456905/52678724-04854500-2f76-11e9-872d-29bd3031ee3c.png)
p11と同様の結果が得られた

**Comment by TatsukiWashimi** [comment]
続いて、「例題35　ステッピングモータのコギングトルク」をやってみた。
![35_model](https://user-images.githubusercontent.com/18456905/52681960-2932ea00-2f81-11e9-88cb-99ce62f1da9c.png)

**Comment by TatsukiWashimi** [comment]
過渡応答にして10 deg/step, 9 step計算した結果
![plots](https://user-images.githubusercontent.com/18456905/52776506-13a6e880-3085-11e9-9509-5990628282e2.png)

**Comment by TatsukiWashimi** [comment]
1度step, 360stepにした場合。6時間ほどかかった。
![plots_1degstep](https://user-images.githubusercontent.com/18456905/52896008-34964780-3205-11e9-8898-688509de88ac.png)
![t-bxyz_1degstep](https://user-images.githubusercontent.com/18456905/52896010-3cee8280-3205-11e9-872e-d2f36ba83195.png)

**Comment by TatsukiWashimi** [comment]
やってみてわかったこと
・過渡解析は、時間ステップごとにフルの領域で計算をしているため、計算および結果表示にえらく時間がかかる。
・時間(角度)ステップ数を10->360に増やすと、計算時間は単純な36倍(15時間)より短い。使用メモリはほとんど変わらなかった。
・回転させるのは、同一回転軸・同一周波数のものしかできない。バラバラの位置に置いた複数のモーターを回転させるなどは不可能。

また、パルスチューブ冷凍機に使われているモーターについて調べたところ、回転モーターではなくリニアモーターによるピストン運動だった。
Femtetの過渡解析には、残念ながらこのような運動は対応させられていない。

**Comment by TatsukiWashimi** [comment]
Femtetで冷凍機モーターからの磁場を作るのは無理そうなので、境界条件として一定周波数の磁場を外から入れたとき、チェンバー内の磁場がどうなるのかを見ることにする。

とりあえず練習として、直径1m, 高さ1m, 厚さ3mmのステンレス(SUS304)の円筒を作り、
外から1T, 1-100Hzの磁場を与えてみた。

**Comment by TatsukiWashimi** [comment]
計算開始日時 : 2019.02.18 10:01:15
Femtet Version 2018.1.1.69647 (64bit)
注意：外部磁界が設定されているため、外部境界条件を磁気壁に変更して計算します。
磁気壁以外にしたい場合は外部境界条件ではなく個別の境界条件を設定して下さい。
-------------------- メッシャG2を使用します --------------------


メッシュの数       :   11880
メッシュの質(最悪) :   5.939870e+01
メッシュの質(平均) :   3.740802e+00
計算時間 (秒)       :   1

メッシュ生成終了
メッシュ時間 : 00:00:05
メモリ使用量 : 89[MB]

Gauss
Freq  1/11:  1.000000e+00[Hz]

行列ソルバ = 直接法（Multifrontal）
---------------------------------------------------------------
   行列タイプ                   = 複素数,対称,InCore
   ライセンスタイプ             = 高速化オプションあり
   自由度                       =     68788
   ＬＵ分解前の総非ゼロ数       =   1356517
   ＬＵ分解後の総非ゼロ数       =  14368484
   ＬＵ分解後の最大非ゼロ数     =      1472
   メモリ使用量／空容量／搭載量 =   275.037 /  11946.211 /  16306.172 [MByte]
   ディスク使用量／空容量       =     0.000 / 149014.977 [MByte]
   スレッド数                   =         4
---------------------------------------------------------------

<<1.000e+00[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  2.21213414e-29
Q              =  2.91416239e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   2.21213414e-29       --------------       --------------
合計             2.21213414e-29       --------------       --------------

Freq  2/11:  1.100000e+01[Hz]

<<1.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  4.03109082e-28
Q              =  1.75911936e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   4.03109082e-28       --------------       --------------
合計             4.03109082e-28       --------------       --------------

Freq  3/11:  2.100000e+01[Hz]

<<2.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  9.07598219e-28
Q              =  1.49159482e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   9.07598219e-28       --------------       --------------
合計             9.07598219e-28       --------------       --------------

Freq  4/11:  3.100000e+01[Hz]

<<3.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  1.48690004e-27
Q              =  1.34401813e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   1.48690004e-27       --------------       --------------
合計             1.48690004e-27       --------------       --------------

Freq  5/11:  4.100000e+01[Hz]

<<4.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  2.12853632e-27
Q              =  1.24173236e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   2.12853632e-27       --------------       --------------
合計             2.12853632e-27       --------------       --------------

Freq  6/11:  5.100000e+01[Hz]

<<5.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  2.82390960e-27
Q              =  1.16424557e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   2.82390960e-27       --------------       --------------
合計             2.82390960e-27       --------------       --------------

Freq  7/11:  6.100000e+01[Hz]

<<6.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  3.56627144e-27
Q              =  1.10265753e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   3.56627144e-27       --------------       --------------
合計             3.56627144e-27       --------------       --------------

Freq  8/11:  7.100000e+01[Hz]

<<7.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  4.35008481e-27
Q              =  1.05216980e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   4.35008481e-27       --------------       --------------
合計             4.35008481e-27       --------------       --------------

Freq  9/11:  8.100000e+01[Hz]

<<8.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  5.17071080e-27
Q              =  1.00985723e+36

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   5.17071080e-27       --------------       --------------
合計             5.17071080e-27       --------------       --------------

Freq 10/11:  9.100000e+01[Hz]

<<9.100e+01[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  6.02422128e-27
Q              =  9.73790837e+35

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   6.02422128e-27       --------------       --------------
合計             6.02422128e-27       --------------       --------------

Freq 11/11:  1.010000e+02[Hz]

<<1.010e+02[Hz]>>
Em    : 磁界エネルギー[J]
P     : 損失[W]
Q     : Q値

Em             =  1.02599522e+07
P              =  6.90726418e-27
Q              =  9.42628386e+35

ボディ属性       ジュール損[W]        ヒステリシス損[W]    鉄損[W]              
Air_Auto         0.00000000e+00       --------------       --------------
ボディ属性_001   6.90726418e-27       --------------       --------------
合計             6.90726418e-27       --------------       --------------


計算終了
メッシュ数   : 11880
計算時間     : 00:00:30 (メッシュ:00:00:05 ソルブ:00:00:25)
メモリ使用量 : 514[MB]
計算終了日時 : 2019.02.18 10:01:45

**Comment by TatsukiWashimi** [comment]
チェンバー外部で1Tだった磁場が、チェンバー内では1x10^-16にまで小さくなる。
計算も一瞬で終わった。

**Comment by TatsukiWashimi** [comment]
続いて、チェンバー側面に直径60cmの穴を開ける。
![openchamber](https://user-images.githubusercontent.com/18456905/52925096-e99a4280-3372-11e9-8cc3-1191e15c7584.png)

先程と同様、x軸方向1Tの磁場を外から入れた結果
![openchamber_bx-flux](https://user-images.githubusercontent.com/18456905/52925122-0171c680-3373-11e9-908b-24e6a3fb7987.png)
![open_bx_plots](https://user-images.githubusercontent.com/18456905/52925127-03d42080-3373-11e9-88a4-05c8bdac93df.png)

**Comment by TatsukiWashimi** [comment]
同じく、z軸方向1Tの磁場を外から入れた結果
![openchamber_bz-flux](https://user-images.githubusercontent.com/18456905/52926171-10a74300-3378-11e9-8f3c-7649a932c374.png)
![open_bz_plots](https://user-images.githubusercontent.com/18456905/52926184-1a30ab00-3378-11e9-8d7d-fb1bad8d8e62.png)

**Comment by TatsukiWashimi** [comment]
まとめると、
閉じたチェンバー : 10^-16

x方向に穴の開いたチェンバーでは
Bx : 10^-3
By : 10^-1
Bx : 10^-1 ＠中心

**Comment by TatsukiWashimi** [comment]
[Cryostatの図面](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VAC?action=AttachFile&do=view&target=LCGT_CryoStat01_110701.pdf)をもとに、おおまかな形状を作った。
![exc_closed_model](https://user-images.githubusercontent.com/18456905/52930328-5cafb300-338b-11e9-9fe5-ce824f3e4fab.png)
![exc_open_model](https://user-images.githubusercontent.com/18456905/52930367-76e99100-338b-11e9-88e4-0e3251be3abc.png)

**Comment by TatsukiWashimi** [comment]
両サイドの鏡板を閉じた状態で、0.1Hz~1kHz, Bx = 1T の外部磁場を入れたシミュレーションを行う。
ビームダクトに直接入る磁場を防ぐため、厚さ10cmのSUS304で蓋をした。

解析条件の、「周波数依存メッシュの設定」の「参照周波数」を1Hzにした場合の結果。
横軸は周波数、縦軸は磁場＠クライオスタット内中心、ビームの高さ
![exc_open_bx](https://user-images.githubusercontent.com/18456905/52982340-da75cc00-3428-11e9-9598-b23b8f443ff3.png)

「参照周波数」を0.1Hzにした場合の結果
![exc_open_bx_sanshou01hz](https://user-images.githubusercontent.com/18456905/52982349-e6fa2480-3428-11e9-8763-7f843a1e4635.png)

x軸(ビーム軸)方向成分の構造は、参照周波数によるものと考えられる。
絶対値、y, z成分の構造 (~100Hz, ~10HZ, ~10Hz) は参照周波数とは別の要因でできている。ビームダクトの蓋の厚さによるものか？

**Comment by TatsukiWashimi** [comment]
[電磁波解析入門セミナー説明資料](https://www.muratasoftware.com/support/download/files_seminar/femtet_hertz_1.pdf)によると、「参照周波数」は「最も興味のある周波数」を入れるものらしい。

**Comment by TatsukiWashimi** [comment]
外部境界条件を、今までは「解放境界」にしていたが、入れる磁場の向きに従ってきちんと設定する。
外部磁場に垂直な面は「磁気壁」、平行な面は「電気壁」にする。
参照周波数は、とりあえず中心の10Hzにした。

両サイドの鏡板を閉め、B = (1T, 0, 0) とした結果
![exc_open_bx_sanshou10hz](https://user-images.githubusercontent.com/18456905/52995301-8b965980-345d-11e9-90c6-78c64beb5edf.png)

最初にてきとうにやった密閉チェンバーのときと同程度の10^-16になった

**Comment by TatsukiWashimi** [comment]
両サイドの鏡板を消して、同じ条件で解析してみる。
![exc_open_bx_sanshou10hz](https://user-images.githubusercontent.com/18456905/52996933-59d3c180-3462-11e9-9e5d-c74b5494b942.png)
数割の変化はあるが、ほとんど同じ

**Comment by TatsukiWashimi** [comment]
練習という意味では終わったと思うので、closeします。
より詳細なstudyは、また改めて
